XXX                        XXX
XX    XXXXXXXX   XXXXXXXXX XXX
X      XXXXXXX   XXXXXXXX X XX
X X     XXXXXXX XXXXXXXX    XX
X X X    XXXXXX  XXXXX      XX
X X XX     XX  XX XX  XX  X XX
X X XXX   X X  XX X XXX XXX XX
X X XXXX   X  XXXX XXX XXXX XX
X X XXXXX   XXXXXXXXX XXXXX XX
X X XXXXXX            XXXXX XX
X X XXXXXX            XXXXX XX
X X XXXXXX  XX  XX  X XXXXX XX
X X XXXX              XXXXX XX
X X XXXX              XXXXX XX
X X XXX X  XXXXXXXXX X XXXX XX
X X XXX XXXXXXX XXX  X XXXX XX
X X XXXX   XXXX X X    XXXX XX
X X XXXXXX XXXXXX XX XXXXXX XX
X X XXXXXX XXXXXXX  X XXXXX XX
X X XXXXX XXXXXXXXX  X XXXX XX
X X XXXXX X X XXXXXX X XXXX XX
X X XXXXX XX XXX     X XXXX XX
  X XXXXX  X XXXXXXXXX XXXX   
  X XXXXXX XX XXX  XX  XXXX   
  X XXXXXX  XX   XXX  XXXXX   
  X XXXXXXX  XXXXX  XXXXXXX   
   X XXXXXXXX     XXXXXXXXX   
   X  XXXXXXXXXXXXXXXXXXXX    
    X                         
     XXXXXXXXXXXXXXXXXXXX     
