XX  XXX XXX XX  XX XXX X XX   
XXXX  XXX XXXXX XXXXXXXX X   X
  XXXXXXXXXXXXXXXXXXXXXXX XXX 
 XXXXXXXXXXXXXXXXXXXXXXXXXXX  
   XXXXXXX   XXXX   XXXXXXXX  
 XXXXXXX  XXX XX XXX  XXXXX XX
 XXXXXX XX  X    X  XX XXXXXXX
 XXXXX XX XX X  X XX XX XXXXXX
  XXX XXXX XXX XXX XXXXX  XXX 
 XXX  XXX   XX XX   XXXX X XXX
 XX  XXXXX XXXXXXX XXXXXX  XX 
 XX X XXXXXXX X XXXXXXXX X XXX
 XX  XXXX  XXXXXXXX  XXXX  XX 
  XX  XXXXX  XXXX  XXXXX  XXXX
  X X    XXXX    XXXX    XXXX 
  X   XXX    XXXX    XX    X X
    XXXXXXXXX    XXXXXXX    X 
   XXXXXXXXXXXXXXXXXXXXXXX    
  XXXXX XXXXXXXXXXXXXXXXXXX   
XXXXXX  XXXXXXXXXXXXX  XXXXX  
XXXXX  XXXXXXXXXXXXXXX  XXXXX 
XXXX  XXXXXXXX XXXXXXXX  XXXXX
 XX   XXXXXXXXXXXXXXXXX   XXXX
 XX   XXXXXXXXXXXXXXXXX   XXXX
 X   XXXXXXX    XXXXXXXX    X 
     XXXXXX      XXXXXXX      
     XXXXX        XXXXXX      
     XXXXX        XXXXXX      
    XXXXXX        XXXXXXX     
    XXXXXXX      XXXXXXXX     
