XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX  X X XXXXXXXXX
XXXXX  X XXX XX  X XXXXXX
XXXXX XX   XXX XXXXXXXXXX
XXX XX XXXX     X X  XXXX
XXXX     X X   X   XXXXXX
XXX X  XX  XXX XX X XX XX
XX X XXXXX X  XX  XX XXXX
XX XXXXXXXXXX XXXX  XX XX
XX XX XX X X  X X XXXX XX
XX XX  XXXX X X XX XXX XX
XXX X  XXXXXXXXXX  XX XXX
XXX X  XXXX XXXXX  XX XXX
XXX X  XXXX  XXXX  XX XXX
XXX XX  XXX  XXX   XX XXX
XXX XX  XXX  XXX  XXX XXX
XXX XX  XXX  XXX  XXX XXX
XXXXXX  XXX  XXX  XX XXXX
XXXX X  XXX  XXX  XX XXXX
XXXX X  XXX  XXX  XX XXXX
XXXXXX  XXX  XXX  XXXXXXX
XXXXXXXXXXX  XXX  XXXXXXX
XXXXXXXXXXX  XXXXXXXXXXXX
XXXXXXXXXXXX XXXXXXXXXXXX
