XXXXXXXXXXXXXXXXXXXXXXXXX
 X   XXXXXXXXXXXXX     XX
X XXX XXXXXXXXX   XXXX  X
 XX XX XXXXX    XXXXX   X
 XXXXX XXX  XXXXXXX   XXX
 XXXXX XX  XXXX XXX   XXX
X XXX    XXXX XXX       X
XX   XXX XX XX XXX     XX
XX XXXX XXXXX XX     XXXX
X XXXXX   XXXXXX     XXXX
X XXXXXXXXXX XX    XXXXXX
X  XXXXXXXXXXX    XXXXXXX
X X XXXXXXXXX   XXXXXXXXX
XX X XXXXXXXXXXX XXXXXXXX
XX  X XXXXXXXXXXX XXXXXXX
XX X XXXXXXXXXXXXX XXXXXX
XXX X XXXXXXXXXXXX XXXXXX
XXXX X XXXXXXXXXXXX XXXXX
XXXXX  XXXXXXXXXXXXX XXXX
XXXXXXX  XXXXXXXXX X XXXX
XXXXXXXXX   XX X XX X XXX
XXXXXXXXXXXX   XXX X X XX
XXXXXXXXXXXXXXX   X X X  
XXXXXXXXXXXXXXXXX    XX X
XXXXXXXXXXXXXXXXXXXXX    
