                       XX
      XXXX            XXX
     XXXXXX          XXXX
    XXXXXXXX         XXXX
   XXXX  XXXXXXXXXXXXXXXX
   XXXX  XXXXXXXXXXXXXXXX
    XX  XX  XXXX  XXXXXX 
        XX   XXX   XXXX  
        XXXX  XXXX  XXX  
  XXX   XXXX  XXXX  XXX  
 XXXXXXXXXXXXXXXXXXXXXXX 
XX XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXX X
XXXXXXXXXXXXXXXXXXXXXXX X
 XXXXXXXXXXXXXXXXXXXXX XX
  XXXXXXXXXXXXXXXXXXX XXX
        XXXXXXXXXXX  XXXX
         XX X X     XXXX 
        XX         XXXX  
       XX         XXXXX  
       X         XXXXXX  
       X        XXXXXXXXX
       XX X X  XXXXXXXXXX
        XXXXXXXX XXXXXXXX
         XXXXXX  XXXXXXXX
