XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X XXXXXXXXXXXXXXXXX     XXXXXX
XX XXXXXXXXXX      XXXXX XXXXX
  X XXXXXXX  XXXXX XXXXX  XXXX
XX X XXXXX XXXXXXXX XX X  XXXX
X         XXXXXXXXX        XXX
X   XXXXXXXX  XXXXXX    XX  XX
X   XXXXXXXX  XXXXXX   XXXX  X
XX XXX XXXXXXXXXXXXX  XXXXXX X
XXX X XXXXXXXXXXXXXX XXXXXXX X
XXXX    XXXXX XXXXX  XXXXXXX X
XXXX X X     XXXXX   XXXXXXX X
XXX XX X X XXXXXX     XXXXXX X
XX XX XX XX            XXX  XX
XXXXX XX  XX        X      XXX
XXXX XXXXXX XXX     XXXXXXXXXX
XXXXXXXXXX XXX   X  XXXXXXXXXX
XXXXXXXXX  XX   XXX XXXXXXXXX 
XXXXXXXX      X XXX XXXXXXXX  
XXXXXXXX       XXX  XXXXXXX  X
 XXXXXX       XXXX  XXXXXX  XX
X XXXXX     XXXXX   XXXXX  XXX
X           XXXX    XXXX  XXXX
 XX XX              XXX  XXXXX
 XX                 XX  XXXXXX
 XXXXXX             X  XXXXXXX
 XXXXXX               XXXXXXXX
                     XXXXXXXXX
X                   XXXXXXXXXX
