XXXXXXX                XXXXXXX
XXX  XXX               XX  XXX
XXX  XXXX             XXX  XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX  XXXXXXXXXXXXXXXXXXXX  XXX
XXX  XXXXXXXXXXXXXXXXXXXX  XXX
XXXXXXXX        XXXXXXXXXXXXXX
XXXXXXX          XXXXXXXXXXXXX
XXX  XX           XXXXXXX  XXX
XXX  XX            XXXXXX  XXX
XXXXXXX             XXXXXXXXXX
XXXXXXX              XXXXXXXXX
XXX  XX               XXX  XXX
XXX  XX                XX  XXX
XXXXXXX                XXXXXXX
XXXXXXX                XXXXXXX
XXX  XX                XX  XXX
XXX  XX                XX  XXX
XXXXXXXX               XXXXXXX
XXXXXXXXX             XXXXXXXX
XXX  XXXXXXXXXXXXXXXXXXXX  XXX
XXX  XXXXXXXXXXXXXXXXXXXX  XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX  XXX        XXXXXXXXX  XXX
XXX  XX          XXXXXXXX  XXX
XXXXXXX           XXXXXXXXXXXX
XXXXXXX            XXXXXXXXXXX
XXX  XX             XXXXX  XXX
