XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
X  XXXXXX  XXXXXX  X
XX  XXXXX  XXXXX  XX
XXX  XXXX  XXXX  XXX
XXXX  XXX  XXX  XXXX
XXXXX  XX  XX  XXXXX
XXXXXX  X  X  XXXXXX
XXXXXXX      XXXXXXX
X                  X
X                  X
XXXXXXX      XXXXXXX
XXXXXX  X  X  XXXXXX
XXXXX  XX  XX  XXXXX
XXXX  XXX  XXX  XXXX
XXX  XXXX  XXXX  XXX
XX  XXXXX  XXXXX  XX
X  XXXXXX  XXXXXX  X
XXXXXXXXX  XXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
