XXXXXXXXXXXXXXXXXXXX
XXXXXX       XXXXXXX
XXXX           XXXXX
XXX   XXXXXXX   XXXX
XX   XXXXXXXXX   XXX
X   XXXXXXXXXXX   XX
X  XXXXXXXXXXXXX  XX
X  XXXXXXXXXXXXX  XX
X  XXXXXXXXXXXXX  XX
X   XXXXXXXXXXX   XX
XX   XXXXXXXXX   XXX
XXX   XXXXXXX   XXXX
XXXX           XXXXX
XXXXXX       XXXXXXX
XXXXXXXX   XXXXXXXXX
XXXXX         XXXXXX
XXXXX         XXXXXX
XXXXXXXX   XXXXXXXXX
XXXXXXXX   XXXXXXXXX
XXXXXXXX   XXXXXXXXX
