XXX XXX XXX  XX  XXXXXX    XXX
XX XXX XXX   XXX XXXXX   X  XX
XX XXX XXX  XX X  XXX   XX  XX
XX XXX XXX  X  X  XX   XXX  XX
XX XXX XXX  X  X  X   XXXX  XX
XX XXX XXX  XX X  X  XXX X  XX
XX XXX XXX  XX X  X  XX  X  XX
XXX XXX XXX  XXX  X  X   X  XX
XX XXXX XXX  XXX  XX XX  X  XX
X XXXXXX XXX  XX  XX     X   X
 XXX     XXX   XX  XXX   XXX  
XXX XXXXX XXX  XXX  XXX  XXXX 
XX XXXXXXXXXX  XXXX  XX  XXXX 
X XXXXXXXXXX   X XXX XXX  XX  
 XXX   XXX     X XXX  XX      
XXX    XX   XXXX  XXX  XX    X
XX   X XX  XXXXXX XXX  XXXXXXX
X   XX XX  XX XXX XXX  XXXXXXX
   XXX XX XX  XXX XXX  XXXXXX 
  XXXX XX XX  XXX XXX  XXX   X
 XXX X XX XX XXX  XX   XXX XXX
 XX  X XX XX X    XX  XXX XXXX
 X   X XX  X X   XX   XXX XXX 
 XX  X  XX  XX XXX   XXX XXX X
     X   XX  XXX   XXXX XXX XX
X    XXX  XX X      XXX XXX XX
XXX  XXXX XX X  XXX  XXX XXX X
XXX  XXXX XX XX XXX  XXX XXX X
XXXX  XX  XX  XX  X  XXX XXX X
XXXX     XXXX  XXXX  XXX XXX X
