XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX X  XX     XXXXXXXXX
XXXXXXX    X   XX      XXXXXXX
XXXXXXX    X    XX      XXXXXX
XXXX  X    X     XX    X  XXXX
XXX   X   XX      X  XXX   XXX
XXX   X   X        XX  X   XXX
XX   X XX X        X   X    XX
XX   X  X X       X   X   XXXX
XX   X   XX      XX   X   X XX
XX  XX     XX    XX   XX  X XX
XX X        XX   X     XX X XX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXX  XXXXXXXXXXXXXX
XXXXXXXXXXXXXX  XXXXXXXXXXXXXX
XXXXXXXXXXXXXX  XXXXXXXXXXXXXX
XXXXXXXXXXXXX    XXXXXXXXXXXXX
XXXXXXXXXXXX      XXXXXXXXXXXX
XXXXXXXXXXXX      XXXXXXXXXXXX
XXXXXXXXXXXX      XXXXXXXXXXXX
XXXXXXXXXXXX      XXXXXXXXXXXX
XXXXXXXXXXXX      XXXXXXXXXXXX
XXXXXXXXXXXXX    XXXXXXXXXXXXX
XXXXXXXXXXXXXX  XXXXXXXXXXXXXX
XXXXXXXXXXXXXX  XXXXXXXXXXXXXX
XXXXXXXXXXXXXX  XXXXXXXXXXXXXX
XXXXXXXXXXXXX    XXXXXXXXXXXXX
XXXXXXXXXXX        XXXXXXXXXXX
XXXXXXXXX            XXXXXXXXX
