        XXXXXXXXXXXXXXX       
       XXXXXXXXXXXXXXXXX      
     XXXXXXXXXXXXXXXXXXXX     
    XXXXXXXXXXXXXXXXXXXXXXX   
   XXXXXXXXXXXXXXXX   XXXXXX  
   XXXX  XXXXXXXX XXXX XXXXX  
 XXXXXXX XXXXXXX XX XXXXXXXXX 
 XXXXXXXXXXXXXXXXXXXXXX XXXXX 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
XXXXXXXXXX   XXXX   XX  XX   X
XXX   XXX     XXX   X X XX  XX
XXX    XXXX   XX  X X X X   XX
XXX  X XXX   XXX    XXX     XX
XX     XX  XXXXX     XX   X XX
XX   X  X   XXX   X  XX   X XX
X    X  XX    X    X XX  XX  X
XXXXXXX XXXXXXXXX XXXXXXXXXXXX
XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXX  XXXXXXXXXXXXX
 XXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXX 
  XXXXXXXX XXXXXXXXXXXXXXXXXX 
   XXXXXXXXXXXXXXXXXXXXXXXXX  
    XXXXXXXXXXXXXXXXXXXXXXX   
     XXXXXXXXXXXXXXXX XXXXX   
      XXXXXXXXXXXXXXXXXXX     
        XXXXXXXXXXXXXXX       
          XXXXXXXXXXX         
