XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXX XXXXXXXXXXXX
XXXXXXXXXXXX XXXXXXXXXXXX
XXXXXXXXXXX   XXXXXXXXXXX
XXXXXXXXXXX X XXXXXXXXXXX
XXXXXXXXXXX X XXXXXXXXXXX
XXXXXXXXXX  X  XXXXXXXXXX
XXXXXXXXXX  X  XXXXXXXXXX
XXXXXXXXX   X   XXXXXXXXX
           XXX           
X  XXXXXXXX   XXXXXXXX  X
XXX     XXX X XXX     XXX
XXXX        X        XXXX
XXXXXX     XXX     XXXXXX
XXXXXXX           XXXXXXX
XXXXXXX  XXXXXXX  XXXXXXX
XXXXXXX XX X X XX XXXXXXX
XXXXXXX XX     XX XXXXXXX
XXXXXX XX   X   XX XXXXXX
XXXXXX X   XXX   X XXXXXX
XXXXXX   XXXXXXX   XXXXXX
XXXXX   XXXXXXXXX   XXXXX
XXXXX XXXXXXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXXXXXXXXX
