XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX        XXXXXXXXXXXXXXXX
XXXXXXX  XXXX   XXXXXXXXXXXXXX
XXXXXXXX XXXXXX   XXXXXXXXXXXX
XXXXXXXX  XXXXXXX  XXXXXXXXXXX
XXXXXXXXX  XX       XXXXXXXXXX
XXXXXXXXXX    XXXX   XXXXXXXXX
XXXXXXXXX  XXXXXXXXX   XXXXXXX
X XXXXXX  XXXXXXXXXXXX   XXXXX
X  XXXX  XXXXXXXXXXXXXXX  XXXX
X   XX  XXXXXXXXXXXXXXXXX  XXX
X X  X XXXXXXXXXXXXXXX  XX  XX
X XX   XXXXXXXXXXXXXXX  XXX  X
X XXXXXXXXXXXXXXXXXXXXXXXXXX X
X XXXXXXXXXXXXXXXXXXXXXXXXXX X
X XXXXXXXXXXXXXXXXXX XXXXXX  X
X XXXXXXXXXXXXXXXXXXX XXXX  XX
X XX   XXXXXXXXXXXXXXX     XXX
X X  X  XXXXXXXXXXXXXXXX  XXXX
X   XXXX  XXXXXXXXXXXXX  XXXXX
X  XXXXX   XXXXXXXXXX   XXXXXX
X XXXXX  X    XXXX    XXXXXXXX
XXXXXXX XXXXX      XXXXXXXXXXX
XXXXXX  XXXXXXXXX  XXXXXXXXXXX
XXXXXX XXXXXXXX   XXXXXXXXXXXX
XXXXX  XXXXX    XXXXXXXXXXXXXX
XXXX         XXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
