         XXXXXXXXXX    XXXXXXX
       XXXXXXXX   XXXX       X
      XXXXXXXXXX     XX      X
     XXXXXXXXXXX      XX     X
    XXXXXXXXXXXXXX     XX    X
    XXXXXXXXXXXXXX      XX   X
   XXXXXXXXXXXXXXXXX     X   X
  XX   XXXXXXXXXXXXX     X   X
  X      XXXXXXXXXXXXX   XX  X
  XX     XXXXXXXXXXXXX    X  X
   XXX   XXXXXXXXXXXXXXX  XX X
   XXXX  XXXXXXXXXXXXXXX   X  
   XXX   XXXXXXXXXXXXXXX  XXX 
  XX     XXXXXXXXXXXXXXXX   X 
 XX      XXXXXXXXXXX   XXXX XX
XX       XXXXXXXXXXX   X  XX X
XXX       XXXXXXXXXXXX X   X  
  X        XXXXXXXXXXX XX  XX 
  X        XXXXXXXXXXX  X   X 
 XXXX      XXXXXXXXXXXX XX  XX
    X      XXXXXXXXXXXXX X   X
  XXX      XXXXXXXXXXX XXXX  X
  X        XXX XXXXXXX  X XX  
  XXXX      XX XXXXXXX  XX X  
     XX       XX  XXXX   X XX 
      X      XX   XXXX   XX X 
      XX    XX    XXXXX   XXX 
       X   XXX    XXXXXX      
       X  XXX     XXXXXXX     
       X XXX      XXXXXXX     
