                XXX 
   X       X   XXXX 
  XXX     XXX  XX   
  XXX    XXXX  XXX  
 XXXXX  XXXXXX  XXX 
 XXXXXXXXXXXXX   XXX
XXXXXXXXXXXXXXX   XX
XXXXXXXXXXXXXXX    X
XXX  XXXXX  XXXX   X
XX X  XXX X  XXX  XX
X  X   X  X   XXXXXX
XX XX XXX XX XXXXXXX
XXX  XXXXX  XXXXXXXX
XXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX 
        XXXX XXXXXXX
      XXXX  XXX   XX
     XXXX  XXX   XXX
