   XXX XXXXXXXXXX  XXX   
    X XXXXXXXXXXXXX X    
    XXXXXXXXXXXXXXXXX    
    XXX  XXXXXX  XXXX    
   XXX    XXXX    XXX    
   XXX XX XXXX XX XXXX   
  XXXX XX XXXX XX XXXX   
  XXXX    XXXX    XXXXX  
 XXXXXX  XXXXXX  XXXXXX  
 XXXXXXXXX    XXXXXXXXXX 
 XXXXXXXXXX  XXXXXXXXXXX 
XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX             XXXXXX
XXXX                 XXXX
XXX   X     X     X   XXX
XX   XXX   XXX   XXX   XX
XX  XX XX XX XX XX XX  XX
XX                     XX
XX                     XX
XX       X     X       XX
XXX     XXX   XXX     XXX
XXXX   XX XX XX XX   XXXX
 XXXX               XXXX 
  XXXXXXXXXXXXXXXXXXXXX  
