      XXXXXXXXXXXXXXXXX       
     XX X X  X  X   X XX      
    XX  X X  X X    X  XX     
   XX   X X  X XX   X   XX    
  XX                X    XX   
  XX XXX     XXXXXX    XXXXX  
 X X X X   XXXXXXX XX    X X  
XX X X X XXXXXXXX XX   XXX XX 
X  X XXX XXXXXXX  X XX X    X 
X       XXXXXXXX XX XX XXX  XX
XXXX   XXXXXXXXX X XXXX     XX
XX X   XXXXXXX  XX XXXX  XXX X
XXXX  XXXXXXX   X XXXXX    X X
X  X XXXXXXXX XXX XXXXX  XXX X
XXXX         XXX  XXXXXX   X X
X XXXXXXXXXXXX X XXXXXXX XXX X
X            XXX  XXXXXX     X
X XXX XXXXXXX   X  XXXXX     X
X X X XXXXXXXXXX X XXXXX  X  X
X XXX XXXXXXXXXXX X XXX  XX  X
X X X  XXXXXXXXXXX X XX X X  X
X XXX   XXXXXXXXXXX XX XXXXXXX
XX       XXXXXXXXXXX      X XX
XX    XXXX XXXXXXXX XXX   X XX
XXX   X  X    XXX   X      XXX
 XXX    X     X     XXX   XXX 
 XXX   XX     XXX     X  XXXX 
  XXX  X      X X   XXX XXXX  
   XXXXXX     XXX     XXXXX   
     XXXXXXXXXXXXXXXXXXXX     
