    XXXXXX  X  XXXXXX    
   XXXXXXX     XXXXXXX   
  XXXXXXXX X X XXXXXXXX  
  XXXXXXXX XXX XXXXXXXX  
  XXXXXXXXXXXXXXXXXXXXX  
   XXXXXXXX   XXXXXXXX   
 XXXX  XX  X X  XX  XXXX 
XX  XX X XXX XXX X XX  XX
X   XX X XXX XXX X XX   X
X  XXX X X X X X X XXX  X
X XX   X XXXXXXX X   XX X
X X     XX     XX     X X
XXX XX  X       X  XX XXX
 XX XXX X       X XXX XX 
  X  XXXXX     XXXXX  X  
  XX  XXXXXXXXXXXX   XX  
   XX    XX   XX    XX   
    XX   XXXXXXX   XX    
 XXXXXX   XXXXX   XXXXXX 
XX XXXXX   XXX   XXXXX XX
   XXXXXXX     XXXXXXX   
  XXXXXX XXXXXXX XXXXXX  
  XX  XX         XX  XX  
 XXX  XXXXXXXXXXXXX  XXX 
 XXXXXXXXXXXXXXXXXXXXXXX 
