XX XXXXXXXXXXXX XXXXXXXXXXXXX 
XX XXXXXXXXXXXX XXXXXXXXXXXXX 
X X XXXXXXXXXXX XXXXXXXXXXXXXX
XX XXXXXX       XXXXXXXXXXXXXX
XX XXX         XXXXXXXXXXXXXXX
XXXX           XXXX XXXXXX XXX
XXX            XXXX        XXX
XX             XXXXXX   XXXXXX
X    XXXXXXXX XXXX XXX XXX XXX
X  XXXX XXX XXXXXXXXX  XXXXXXX
  XXX   XX   XXXXX     XX  XXX
 XXX     X     XXX     XX   XX
 XX      X X    XX    XXX    X
XX   XX XX XX   XXX    XX   XX
XX  XX XXXX X X  XX   XXX   XX
X   X  X  XXX XX XXX    X  XXX
X X XXXX  XXX  XX XXX  X  XXXX
X X XX X    XX  X XXXX  XXXXXX
XXX X X    X XX XXXX XXXX XXXX
XX XXXX    XX X XXXXX    XXXX 
XX X           XXXXXXXXXXXXX  
 XXX     X    XXXXXX         X
 XXX   X      XXX XX    XXXXXX
  XXX  XXXX  XXXX  XX         
X  XXX      XXX X   XXXXXXX   
X   XXXX  XXXXX    XXXX   XXX 
XX   XXXXXXXX X   XX       XX 
XXXX XX    XX    XX        XX 
XXXXXXX    XXXX   XX       XX 
XXXX X      X XXXX XX      XX 
