   XXXXXXXXXXXXXXXXXX   X
 XX XXXXX   X    XXXX XXX
   XXXX  XXX XXXX XXX   X
 XXXXX XXXXXXXXXXX XX XXX
 XXXX XXXXXXXXXXXXX X   X
XXXXX XXXXXXXXXXXXXX XXXX
XXXX XXXXXXXXXXXXXXXX XXX
XXX XXXXXXXXXXXXXXXXXX XX
XX XXX X  XX XXX XX XXX X
 X XX X XX  X   X  X  X X
X X   XXXXXXXXXXXXXXX X X
XX XX X     XX     XX X X
X X   X X X XX X X XX  XX
 XX X X   X XX   X XXX  X
X     XXXXXXXXXXXXXXX X X
 XX XXXXXXXX  XXXXXXXXX X
 X XXXXXXXX XX XXXXXXXX  
 X XXXXXXXXXXXXXXXXXX  XX
X  XXX  XXXXXXXXXXXXX XXX
XX XX XX XXXXXXX XXXX XXX
 X  XX   XXXXXX XXXX   X 
 X X XXXX      XXXX XXXXX
  XXX XXXXXXXXXXXX XX   X
 X XXX            XXX X X
 XX XXXXXXXXXXXXXXXXX   X
