XX      XXXXXXXXXXXXXX     XXX
XX XX  XXXXXXXXXXXXXXXX    XXX
X  XXX XXXXX  XXX  XXXX  XX XX
X   XX XXXXXX  X  XXXXX XXX  X
XX XXX XXXXXXX   XXXXXX XX  XX
XXXXXX XXXXXX  X  XXXXX XXXXXX
XXXXX  XXXXX  XXX  XXXX XXXXX 
XXXX   XXXXXXXXXXXXXXXXXXXX   
 XXXX XXXXX         XXXXX     
   XXXXX     XXXXXX    XXX    
X   XX   XXXXXXXXXXXXXXX XXX X
XX XX XXXXXXXXXXXXXXXXXXXX XXX
 XXX XXXXX   XXXXX   XXXXXXXX 
  X XXXXX     XXX     XXXXXX  
X X XXXXX  X  X X  X  XXXXX XX
X XXXXXXX     X X     XXXXX XX
X XXXXXX X   XXXXXX  XX XXX   
   XXXXX XXXXX XXX XXX  XX  XX
XX XXXXX        X       X  XX 
XX  XXXXX XX   XXX   X XX XX  
 XX   XXX  XXXXX XXXXXXX  XX  
 XXX   XXX  XX    X XX   XX   
  XX     XXX XXXXXX X  XXX   X
   XXX    XX XXXXXX X XXX  XXX
  XXXXXX   X XXXXXX XXXX    XX
 XX  XX    XX XXXXX XX   XXXXX
XX    X     X XXXXX X       XX
XX          X X   X X   XXXXXX
XXX        XXX XXX XX     XXXX
XXXX     XXXXXX   XX XXXXXXXXX
