    XX  XXXXX  XX        
   XX XXXXXXXXX  X       
   XXXX  XXXX  XXXX      
  XXXX XX XX XX XXXX     
 XXXX XXX XX XXX XXXX   X
 XXXX X   XX X   XXXXX X 
XXXXX X X XX X X XXXXX X 
XXXXXX   XXXX    XXXXX X 
XXX XXXXXXXXXXXXX XXXXX X
XXXX             XXXXX  X
XXXXXXXXXX XXXX XXXXXXXX 
XXXXXXXXXXX XX XXXXXXX   
XXXXXXXXXXXX  XXXXXXXX   
XXXXXXXXXXXXXXXXXXXXXX   
XXXXXX  XXXXXXXXXXXXXX   
XXXXXX    XX   XXXXXXX   
 XXXXX          XXXXXX   
 XXXXX  XX  XX  XXXXX    
  XXXX  XX  XX  XXXXX    
  XXXX  XX  XX  XXXX     
   XXXXXXXXXXXXXXX       
     XXXXXXXXXXXX        
     X X       X X XX    
   XXXXX       X XXXX    
   XXXXX        XXXX     
