XXXXXXXX        XXXXXXXXXXXXXX
XXX  X XXXXXXXXXXXXXXXXXXXXXXX
X X XXXXXX  XXXXX XXX XXXXXXXX
XXXX XXXX    XXXXX  XXXXXXXXXX
XXXX XXXX XX XXXXXX X  XXXXXXX
XXXX  X X XX XXXX        XXXXX
XXXXX X XXX XX XX X  XX  XXXXX
XXXXXXX    XX  X  X        XXX
XXXXXXXX XXX  XX  XX  X  X  XX
XXXXXXXXXX  XXX XXXXXXXXX  XXX
XXXXXXXXXX XX XX     XXXXXXXXX
XXXXXXXX XXXXXXXX     XXXXXXXX
XXXX  X  XXXXXX XXX    XXXXXXX
XXXXX   XXX  XX  XXXXXXXXXXXXX
XXXXXXXXXXXX  XX  XX    XXXXXX
X   XXXXX XXX XX   XXXXXXXXXXX
     X  XXX  XXXX  XX X XXXXXX
   XX  XXX  XXXXX XX X XX   XX
  XXX XXXXX  XXX    XXXX  XX X
  XXX XX XXXX    XX    XXXXXX 
   XX  X   XXXXXXXXX     XXX  
X   XX      XXXXXXXXXXXX  XXX 
XXX XXX     XXXXXXXXXXXX XXXXX
XXXXXXXX   XXXXXXXX XXX XXXX X
XXXXXXX   XXXXXXXXXXX   XXXXXX
XXXXX   XXXXXXXX XXXX  XXX XXX
XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXX                
 XXXXXX  XXXXXXXXX            
   XXXXX  XXXXXXXXXXXXXXXXXXX 
