  X  XX  X  XX  X  XX  X  XX  
X   X  X   X  X   X  X   X  X 
XX XXXXXX XXXXXX XXXXXX XXXXXX
XXXX XXXXXXX XXXXXXXXXXXX XXXX
XXXX   XXXXX XXXXXXXXXXXX XXXX
XXX   X XXXX XXXXXXXXXXXX XXXX
XX X  XX XXX XXXXXXXXXXXX XXXX
X    X XX XX XXXXXXXXXXXX XXXX
X  XXX  X  X XXXXXXX  XXX XXXX
XXXXXX   XX   X     X   X XXXX
XXXXXXX   X   X     XX    XXXX
XXXXXXX   X   X     XXXXX XXXX
XXXXX     XXXXX     XXXXX XXXX
XXX         X   X   XXXXX XXXX
XXX X  XX   X XXXX   XXXX XXXX
XXX X XXXXXX XXXXXX  XXXX XXXX
XXX    XXXXX XXXX   XXXXX XXXX
XXXX X  XXXX XXX XXXXXXXX XXXX
XXXXXXXXXXXX XXXX XXXXXXX XXXX
XXXXXXXXXXXX XXXX   XXXXX XXXX
XXXXXX     X XXX   X XXXX XXXX
X     X    X XX X  XX XXX XXXX
X     XX   X X    X XX XX XXXX
X     XXXXXX X  XXX  X  X XXXX
X     XXXXXX XXXXXX   XX   X  
  X   XXXXXX XXXXXXX   X   X  
XXXX   XXXXX XXXXXXX   X   X  
XXXXX  XXXXX XXXXX     XXXXX  
XXX   XXXXXX XXX         X   X
XX XXXXXXXXX XXX X  XX   X XXX
