   XXXXXXXXXXX 
  XXXXXXXXXXXXX
 XXXXXXXXXXXXXX
 XXXXXXXXXXXXXX
 XXXXXXXXXXXXXX
 XXX XXXX XXXXX
 XX   XX   XXXX
 XX   XX   XXXX
  XX XXXX XXX X
  XXXXXXXXXXX X
  XXXX  XXXX XX
   XXXXXXX  XXX
   XXXXXXXXXXX 
   X X X X XX  
   XXXXXXXXX   
