XXXXXXXXXX XXXX
XXX   XXX XXXXX
XX     X XXXXXX
XX     XXXXXXXX
XX    XXXXXXX  
XXX    XXXXX   
X     X XXXX   
 X    XX XXXX  
 X    X XXXXXX 
       XXXXXXX 
X      XXXXXX  
XX   X XXXXX   
XX XXX XXXXX   
XX XXX XXXXX   
XX  XX  XXXX   
