XXXXXXXXXX XXXXXXXXXX XXXXXX X
XXXXXXXX XXX XXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXX   XXXXXXXXXX
XXXXXX XXXXXXXXX    XXXX XX XX
XXXXXXXXXXXXXX   XXXXXX XXXXXX
X XXXXXX XXX X X XX XXXXXXXXXX
XXX XXXXXXXXXX X XXXXXXXXX XXX
XXXXX XXXXXXX XXX XXXXX XXXXXX
 XXXXXXXXXXX XXXXX XX XXXXXXXX
XXXXXXX X XX XXXXX XXXXXXX XXX
XXXXXXXXXXXX      XXXX XXXXXXX
X XXXXXXXXX XXXXXX XXXXXXXXXXX
XXXXXXXX X XXXXXXXX XXXXXX XXX
XXX XXXXXX XX XX XX XXXXXXXXXX
XXXXXXXXXX XXXXXXXX XXXXXXXXXX
XX XX XXXX XXXXXXXX XXX XX XXX
XXX X XXXX X XXXX X XXX X XXXX
X     XXXX XX    XX XXX     XX
XXX   XXXXX XXXXXX XXXX   XXXX
X  X   XXXXX      XXXX   X XXX
XXX XX  XXX XXXXXX XX  XX X XX
XX XXXX    XXXXXXXX   XXXX XXX
XXXXXXXX   XXXXXXXX  XXXXXXXXX
XXXXXX XXX XXXXXXXX X X XXX XX
X X XXXXXX XXXXXXXX XXXXXXXXXX
XXXXXXXXXX XXXXXXXX XXXXXX XXX
XX XXX X X XXXXXXXX XXXXXXXXXX
XXXX XXXXX XXXXXXXX X XXXX XXX
 XXXXXXXXXX XXXXXX XXXXXXXXXXX
XXXXX XXXXXX      XXXXXX XXXXX
