XXXXXXXX    XXXXXXXXXXX X    X
X XXXX    X   XXXXXXX X   XXXX
   XX    XX X  XXXX XX  XXXX  
 X X  XXXXX XX XX XX   XXX   X
 X X XXXX    X  X XXX    X XXX
  XX XXX XXX X  X XXXXXX    XX
X X XXXX XXXX XX XXX XXXXXXXX 
XXX XXXX  X XXXXXXXX  XXX XXXX
XXX  X XX  XXX XXXXX XXXXXXXX 
 XXX       XXX XXXX XXXX XXX X
 X XX      X X XXXX XXXXXXXX X
 XX XXXXX  XX  XXXXXXXXXXXXXXX
  XX  XXXXX XXXXXXXXXXX   XXXX
  XX      XXXXXXXXXXXX XX  XXX
X  XX   XXXXXXXXXXXXXXXX   X X
X   XX   XXXXXX XXX   XXX XX  
X    XX XXXXXXXX    XX  XXXXXX
X   X XXXXXXXX     XX    X XX 
XX XX XXXXXXXXX   XX X   X XX 
XXXXXXXXXXXXX X    XX    X XX 
XXXXXXXXXXXXX           XXXXX 
XXXXXXXXXXX            XXX XXX
XXXXXXXXXX XX          XXX X X
XXXXXXXXXX XXXX       XXXXXX X
XXXXXXXXXXX XXXXX    XX XXX XX
XXXXXXXXXXXX XXXXXXX  X XX X X
XXXXXXXXXXXX XXXXX XXXX XX XX 
XXXXXXXXXXXXX XXX XXXX XXXXX  
XXXXXXX  XXX XX   XX XXXX XXXX
XXXX X X XX XX   XXXX X  XX XX
