 XXXXXX XX XX XXX XXXXXXXXXX  
 XXX XXXXX X XXX XXXXXXXXXXXX 
 XXX XXXXXX XXX XX XXXXX  XXXX
XXXX XX XX  XX XXXXX XX  XXXXX
XXXX XX X  XXX  XXXXX  XXXXXXX
 XXX XX    XX    XXXXXXXXXXXXX
 XXX XXX    X     XXXXXXXXXXXX
XXXXXXX              XX XXXXXX
XX  X XXX      XXX    X  XXXXX
  XXXXXXXX        X      XXXXX
 XXXXXXX X    XX XX      XXXXX
XXXXXXXXXXX    X       XXX   X
XXXX XXXXXX    X       XX     
XXXXX XXX XXX X        XX XXX 
XXXXX XX X    XXX     XX   XXX
XXXXX X XXX  XX XX   XXX     X
XXXXXX       X   XX XXXXXXXXXX
XXXXXX  X X    X  XXXXX    XXX
XXXX XX X XX  X      XX  XX XX
XXXXX XXXX XX XX     X XXXXX  
XXX XX  XX  X        X XXXXXX 
XXXX XX     X    X  XX XXX  XX
XX XX  X    XX  XX  X XXX    X
XXX XX       XXXX   X XX     X
XX XX X      XXX    XXXX      
XXX            XX   XXXX      
XXXXXXXXX       XXX XXXX      
XXXXXXXXXXXX      XXXXXX      
X       XXXXX        XXXX     
 XXXXX    XXXXX         X     
