 XX XX   XX XXX
X  XXXXXXXXXX  
X XXXXXXXXXXXX 
XXXXXXXXXXXXXXX
XXXX  XXX  XXXX
XXX    X    XXX
XXX XX   XX XXX
XXX XX   XX XXX
XXX         XXX
XXX   XXX   XXX
XXX X  X  X XXX
 XX  XX XX  XXX
 XXX       XXXX
  XXXXXXXXXXXX 
   X XXXXXX  X 
