             X  X        
            XXX X        
            XX XXXX      
           XXX XXXXX     
X X X     XXXX XXX XX    
 X X X    XXXXXXX X XX   
X X X X  XXXXXX XX XXXX  
 XXXXX  XXXXXXXX XXXXXX  
X XXXXX XXXXXXXXX XXXX   
 XXXXX XXXXXXXXXXX XX    
X XXXXXXXXXXXXXXXXX      
 XXXX  XXXXXXXXXXXXX     
X XXX XXXXXXXX XXXXXX    
 XXX  XXXXXXXXX XXXXXX   
X XXX XXXXXXXXXX   XXXX  
 XXX XXXXXXXXXX XXX X X  
X XXXXXXXXXXXXXXXXXXXX   
 XXXXXXXXXXXXXXXXXXXXXX  
X XXXXXXXXXXXXXXXXXXXXX  
 X XXXXXXXXXXXXXXXXXXXX  
X XXXXXXXXXXXXXXXXXXXX   
 X XXXXXXXXXXXXXXXXXX    
X XXXXXXXXXXXXXXXXXXXXXX 
 X   XXXXXXXXXXXXXXXXXX  
  X   XXXXXXXXXXXXX      
