XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
XX    XXXXXX XXX  XXXXXXXX    
X      XXXXXXXXX XXXXXX   XXXX
  XX    XXXXXXXX XXXX  XXXXXXX
 XXXX   XXXXXX X XXX XX    XXX
XXXXX   XX XXXXX XX XX   X  XX
 XXXX   XXXXXXXX X XX    X   X
  XX    XXXXXXXX  XX     X    
X      XX XX XXX  XX     X    
XX    XXXXXXXXXX XXX X XXX  X 
XXXXXXXXXXXXXXXX XXX          
XXXXXXX XXXXXXXX XXX          
XXX XXXXXXXXX XX XXXX    X   X
XXXXXXXXX XXXXXX XXXXX      XX
X XXXXXXXXXXXXXX XXXXXX    XXX
XXXXXXXXXXXX XX  XXXXXXXXXXXXX
XXXXXX XXXXXXXX  XXXXXXXXXXXXX
XXX XXXXXXXXXX X XXXXXXXX    X
XXXXXXXXXX XXX X XXXXXXX XX X 
XXXXXXXXXXXXX XX XXXX    XXX  
XXXXXXXXXXXXX XX XXXX XX XXX  
X XXXX  XXXX XXX XXXX XX XXXX 
XXXXX   X XX XXX XXXX XXX    X
XXXXXX  XXX XXXX XXXX XXXXXXXX
XXXXXX XXXX XX X XXXX         
XX XX   XXX XXXX XXXXX X XX X 
XXXX X X XX XXXX XXXXX X XX X 
XXXXX   XXX XXXX XXXXX X XX X 
XXXX XX XXX XXX  XXXXX X XX X 
 XXX XXX XX XXX  XXXXX   XX   
