XXX      X   X     X      XXXX
XXX      XXXXX    XX     XXXXX
XXX     XXXXXXX   XXX    XXXXX
XXXX   XX XX XX   XXX   XXXXXX
XXXX   XXXXXXXXXXXXXX   XXXXXX
XXXX   XX    XXXXXXXX   XXXXXX
 XXXX   X    XXXXXXXX   XXXXX 
  XXX  XXXXXXXXXXXXXX   XXX   
   XX XXXXXXXXXXX  XX   XX    
    X XXXXXXXXXXX XXX   X     
     XXXXXXXXXXXXXXXXXXX      
     XXXXXXXXXXXXXXXXXXXX     
    XXX   XXXXX   XXXXX XX    
   XXXX   XXXXX   XXXXX  XX   
X  XXXX   XXXXX   XXXXX  XX  X
XX XXXXXXXXXXXXXXXXXXXXXXXX XX
X XX                      XX X
X XXXXXXXXXXXXXXXXXXXXXXXXXX X
X XXXXXXXXXXXXXXXXXXXXXXXXXX X
XX XXXXXXXXXXXXXXXXXXXXXXXX XX
X  XXXXXXXXXXXXXXXXXXXXXXXX  X
  XXXXXXXXXXXXXXXXXXXXXXXXX   
  XXXXXXXXXXXXXXXXXXXXXXXXX   
   XXXXXXXXXXXXXXXXXXXXXXX    
    XXXXXXXXXXXXXXXXXXXXX     
      XXXXXXXXXXXXXXXXX       
       XXXXXXXXXXXXXXXX       
        XXX XXXXXX  XXX       
        XXX   XXX   XXX       
        XXX   XXX   XXX       
