XXXXXXXXXXX  XXXXXXXXXXXXXXXXX
XX XXXX XXXX XX XX XXX XXX  XX
XXXXXXXXXXXX XXXXXXXXXXXXXX  X
X XXX XXXXXX XXXXXXXXXXXX XX  
XXXXXXXX XXXXX XXXXXX  XXXXXX 
X XXXX  XXXXX  X XXXXXX  XXXX 
XXXXX  XXX XX  XXXXXXXXX  XXX 
XXXX  XXXXXXX  XXXX XXXXX  XXX
XXX  XX XXXXX   XXXXXXXXXX  XX
XXX XXXXXXXX      XXXX       X
XX  XX                XXXXX  X
X  X                 XXXXXXX  
 XX   XXX            XXX XXX  
 X  XXXXXXX     XX   X     X X
X   XXXXXXX     XX  XX X X XX 
X   X     XX     X  XX     XX 
X  XX X X XX     X   X XXX X  
X  XX     XX     XX   X   X   
X  XX  X  XX XXX  XX   XXX    
X  XXXXXXXXX XX   XXXXX   XXX 
      XXX    XX      XX X X XX
  XXXXX XXXXXXX      XX   XX X
XXXXXXXXXXXXX        X  X  X X
XX  XXX XXX          X     X X
X   XXXXXXX         XXXXXXXX  
    X  X  X         XXXXXXXXX 
   XXXXXXXXX       XXXX   XXX 
  XXXXXXXXXXX      XXXX   XXX 
     XX  XX               XX  
    XXX  XXX              XXXX
