XXXXXX X  XXXXX           XXXX
XXX    X XXXXXXX XXXXXXX XXXXX
XX     X XXX XXXXXX   XXXXX  X
XX    XX XX   XXX       XX    
       X XX  XX XX    XX XX   
XX X X X XXX X            XX X
XX    XX  XXXX  XX     XX  XXX
    XXXX   XX  X XX   X XX XXX
XXX    X    X  XX X   XX X  X 
XXXXXXXX  XXXX XX XXXXXX    X 
        XXXXXXXX  X XXX XX  X 
XXXXXX XXXXXX XXX  XXX    X X 
       XXXXX XXXXX  X  X  X X 
      XXXXXXX X XXXXXXXX  XXX 
      XXXX XXX XXXXXXXXX XXX  
      XXXXX XXX X XXXXX XXXX  
 XXXXXXX XXXXXXX XXX   XXXX   
XXXXXXXXX XX XXXXXXXXXXX XXX  
XXXXXX  XXX XX XXXXX   XX XXX 
XXXXX XX XXXXX  XXX     X  XX 
XXXXX XXX XX            X  XX 
XXXXXX XXX XX          XX  XX 
XX XXXX XX XXX       XXX  XXXX
XXX XXXX  XXXXXXXXXXXXX  XXX  
XXXX XXXXXX  XXXXXXX     XX   
 XXXX X XX    XXXXXXXX   XX   
X XXXX XXX    XXXX   XX  XX   
XXX XXXXXXX    X      X   XX X
 XXXXX    X           X    XXX
   XXXXXXXX          XX  XXXXX
