     XXXXXXXXXXXXXXXXXXXX     
    XXXXXXXXXXXXXXXXXXXXXX    
    XXXXXXXXXX XXXXXXXXXXX    
   XX XXXXXX XXXXXXX  X XXX   
 XX XX   X  XXXXXXX XX  X XX  
XXX XXX    XXXXX X XX XXXX XX 
XXX XXXXXXXXXX    X  XXXX   X 
XXXX XXXXXXXX     XX    XX  X 
XX    XXXXXXXXX          X XX 
XX      XX    XXX        XXX  
X   X  XX XXXXXX     XXX XX   
X   XX  XXX  X XX   XX  XX X  
  X XX  XX X XX X  XXXXX X XX 
  X XXX  X  XXX    XX X XX  XX
 XX X X XX         X XX X X XX
 X XX XXXX         X   XX XX X
XX X   XX         XX   XXX X X
XXXX    XX        X    X XXX X
XXXXX   XX       XX   XX   XXX
X XXXX   XX    XXXX   XX   XXX
X  X X   XXX    XX   XX XXX XX
   X XX  X XX       XXXXX X  X
XX X  XX XX XXX    XXXXX XX  X
XXXXX  XX X  XXX XXXXXX XXX  X
XXXXX   XXX    XXXXXXX  XXXX  
XXXXX     XX   XXXXXX  XXXXXX 
XXXXXX     X    XXXXX     XXX 
XXXXXXXX   XX   XXXXX  XXXXXXX
XXXXX  XXX XXX   XXXX     XXXX
XXXXXX    XXXXX  XXX    XX XXX
