      XXXXXXXX      
      X      X      
     XX      XX     
     X  X  X  XX    
    XX XX XXX  XXX  
   XX XXXXXXXXX XXX 
 XXXXXX XXXXX XXXXXX
XXXXXX XXXXXXX XXXXX
XXXXXX X XXX X XXXXX
XXXXXX  XXXXX  XXXXX
XXX XXXXXXXXXXXXX XX
XXX   XXXXXXXXX   XX
XXXX             XXX
X X X           XXXX
X X XX  XXXXX  X X X
X X XXXX     XXX X X
XXXXXXXXXXXXXXXX X X
 X   XXXXXXXXXXXXXXX
 XXX XXXXXXXXXX   X 
X X XXXXXXXXXXX  X X
