XXXXXXXXX X XXXXXXXXX X X
XX XXXX       XXXXXXXX X 
X   XXXXX       XXXXXXX X
XX XXXXX  XX        XXXX 
XXXXXXXX X X     XXX XXXX
XXXX XXXX   X   X   X XXX
XXX   XXXXX X  X  XX X XX
XXXX XX  XXX    XX  X X X
XXXXXXX XXXX   XX  XXX  X
 XXXXX  XX X  XX   XXX   
  XXXX  XXXX  XX  XXXX   
X  XXX   XXX XX   XX X   
XX  XX   XXX XX   XXXX   
 XX  XX   X  XX   XXXX   
  XX  X  XXX XX    XXX   
   XX  XX   XXX     XX  X
    XX      XXXX   XXX  X
X    XXX      XXXXXXX   X
XX     XXXX     XXXX   XX
XXXX      XXX      XX XXX
X XXX       XXXXXX  XXX X
   XXXXX           XXX   
X XXX XXXXXXXXXXXXXX XX X
XXXX   XXXX     XXX   XXX
XXXXX XXXXX     XXXX XXXX
