  XX XX  XXXX XX XXX XXXX   XX
  XX X  XXXX  XX XX  XXXXXX  X
 XX  X  XXXX XX  X    XX XXX X
 XX  X  XXX XX XX     X  XXX X
 XX  XX XX XX X  X     XX X XX
XX  XXX XXXX XX XX    XXX XXXX
XX  XXXX XXX X X X    X X XXXX
X  XXXXXXXXX   XXX    XX XXXX 
X  XXXXXX  XX  XXX   XXX XXX  
  XXXXXXX  XX         X   X   
  XXXXXXXX XX             X   
 XXXXXXXXXXXXX    X   X   X   
 XX XXXXXXX XX     XXX   XX   
 X XXX   XX XX          XXX   
 X XX     X XX XX      XXXXX  
   X      XXXXX XXX  XXXX XXX 
  XX    XX XXXX  XXXXXXXX XXXX
X XX    XX XXXX    XXXXXX XXXX
XXXX    XX XXXX   XXX  XX  XXX
XXXX    X  XXXXX XX    XXX XXX
XXXX    X  XXXXX        XX XXX
 XXX    XX XXXXX        XX  XX
 XXX    XX  XXXX XX      XX XX
  XX     X  XXX   XX  XXXXX  X
  XX     XX XXXXX XX XXX  XX X
X XX    XXX  XXXXXXXXX XXXXXX 
X XX    XXXX X   XXXXXX    XXX
XXXX    XXXXXXXXXX XXXXXXXXXXX
 XXX    X  XXXXXX XXXX XXXX XX
  X     XXX      XX  XX    XXX
