XXXXXXX    XXX X XXXXXXXX
XXXXXX XX   X X   XXXXXXX
XXXXX  X XXXXX XX  XXXXXX
XXXXX   XXXX XX XX  XXXXX
XXXX    XXXXX XX X  XXXXX
XXXX   XXXXXXX XX X  XXXX
XX X X XXXXXXXX X     X X
X X XXXX X X  X XX X  X X
XX XXX  XXX  XXX XXX  X X
XX XXXXXX       XXX XX X 
XX  X   XX     XX XX X X 
XX    XXXXX   XXXX  XX   
X X  XXX X X X X XX  X   
  XXXXXXX XX  X X XX     
  XX XXX   X   X  XXX   X
   X XXXX X     X XXX  XX
   XX XX XX   X XXXX   X 
  XXX XXXXXXXX  XXX  XXX 
 XX X  XXX    XXXXX XX X 
 XX    XXXXXXX XXX     X 
 X      XXX   XXXX      X
X X     XXXXXXXXXX     X 
XXX    XXXXXXXXXXXX    XX
X X    XXXXXXXXXXXX    XX
 X    XXXXXXXXXXXXXX    X
