XXXXXXX      XXXXXXXXXXXXXXXXX
XXXXXX  X     X XXXXX X X XXXX
XXXXXX    XX    X X X X   XXXX
XXXXXX     XXX    X       XXXX
XXXXXX       XX           XXXX
XXXXXX XXXXX  XX     XXXXXXXXX
XXXXXXXXXXXXXX      XXX   XXXX
XXXXXX  X XX XX    XX     XXXX
XXXXXX  XXX   X    XXXX   XXXX
XXXXXXX  XXX      XX XXXX XXXX
XXXXXXX           XXXX  XXXXXX
 XXXXXXX          X XXX XXXXX 
 XXXXXXXX        X     XXXXX  
 XXXXX XXX       X     XXXXX  
XXXXXXX  XX      X    XXXXX   
XXXXXXXX   X    XX    XXXXX   
X XXXXXXX            XXXXXX   
XXXXXXXXX   XXXX     XXXXXX   
XXX XXXXXX   X XX   XXXXXXXX  
XXXXXXXXXX   XX    XXXXXXXXX  
 XXXXXXXXXX       XXXXXXXX XX 
XXXXXXXXXXX     XXXXXXXXXX  X 
 XXXXXXXXXXX   XX XXXXXXXXX  X
  XXXXXXXXXX XXX    XXXXXXXX  
     XXXXXXX       X XXXXX XXX
   X   XXXXXX      X  XXXX  X 
   XX   XXXXX     XX   XXX XX 
   XX     XXX    XX    XXX X  
X   X      XX   XXX     X XX  
XX  XX      X  XXX      X XX  
