 XXX  XXXXXXX  XXXXX XXX 
XX XXXXXX XX XXX XXXXXXXX
XXXXXX XXXXXXXXXXXXX X XX
 XXXXXXXX XX XXXX XXXXXXX
XX XX XXXXXXXXXXXXX XXXX 
XXXXXXXX         XXXXX XX
XXX XXX           XX XXXX
X XXXX XXXX   XXXX XXXXXX
 XX X  XX X   X XX  XXXX 
XXXXX  XX X   X XX  X X X
XXXXX  X XX   XX X  XXXXX
XX     XX X   X XX     XX
X      XXXX   XXXX      X
X          XX           X
XX        XXXX         XX
XXXXX     XXXX      XXXXX
X XXX     XXXX      XXX  
XXXX X    XXXX     XX XXX
XXXXXXX    XX     XXX XX 
X  XX XX         XX XXX X
XXX  XXXXXXXXXXXXXXX  XXX
 X XXXXXXX     XXXXXXX  X
X XXXXXXXX XXX XXXXXXXX X
 XXXXXXXX XX XX XXXXXXXX 
 XXXXXX  XX XX X  XXXXXX 
