     XXXXXXXXXXXXXXXXXXXXX    
    XXXXXXXXXXXXXXXXXXXXXXXX  
    XXXXXXXXXXXXXXXX XXXXXXXX 
   XXXXXXXXXXXXXXXXX  X XXXXXX
   XXXXXXXXXXXXXXXX     XXXXXX
   XXXXXXXXX XX XX     XXXXXXX
   XXXXXXXXX X XXXX   XXXXXXXX
  XXXXXX XXX XX X XX   XX XXX 
  XXXXX   X   X XXX   XX XXXX 
  XXXXX   X     XX   XXXXXX   
  XXXXX  X           X XX     
  XXXXXX X           XXX      
 XXXXXXXX           XX X      
 XXXXXXXX        XXX   X      
XXXXXXXXXX      X  X  XX     X
XXXXXXXXXXX     XXXX  X      X
XXXXXXXXX XX     XX  XX      X
XXXXXXXXX  XXX      XX      XX
XXXXXXXXX    XXX   XX       XX
XXXXXXX XX     XX XX       XXX
XXXXXX   XX     XXXXX     XX X
XXXX      XXX   XXXXX    XXX X
XXXXXX      XXX XXXXXX XXXXX X
X    XX    XXX XXXXXXXXXXXX X 
XXX   XX  XX XX XXXXXX  XXXX X
  XX   XX XX XX X XXX     XX X
   XX   XXXX XX X XX  X XXXX X
    X     XXX  XX X    X   XXX
    XX   XXXXXXXXXX      XX XX
     X  XXXXXX XXX      XX XXX
