XXXXXXXX  XXXXX XXXX XXXXXXXXX
XXXXXXX  X  XXXX XXXX XXXXXXXX
XXXXXX XX  XXXXX XXXXX XXXXXXX
XXXXXX X  XXXXXXXXXXXXX XXXXXX
XXXXX X  XX XXXXXXXXXXX XXXXXX
XXXXX X XX XXXXXXXXXXXXX XXXXX
XXXX X XX XXXXXXXXXXXXXX XXXXX
XXXX X XX XXXX XX XXXXXX XXXXX
XXXX X X XXXX  X   XXXXXXXXXXX
XXXX XXX XXXX X    XXXXXXXXXXX
XXXX XXXXXXX X      XXXXXXXXXX
XXXX XXXXXXX X      XXXXXXXXXX
XXXX XXXXXXXX     XX XXXX XXXX
XXXX XXXXXXXX   XXXXXXXXXX XXX
XXXX XXXXXXX     X XXXXXXX XXX
XXXX XXXXXXXXX    X   XXXX XXX
XXXXX XXX XXX          XXX XXX
XXXXX XXX X X          XX XXXX
XXXXX XXX X X          X XX XX
XXXXX XXXXX X          XXXX XX
XXXXXX XXXX X  XXX    XXXXXX X
XXXXXXX XXX X     XX  XXXXXX X
XXXXX  XX XX  XXXXX  XXXXXX X 
XXXX  XXX XXX   XX   XXXXX XXX
XXX  XX XX X X      XXXXXXXXXX
XX   XXXX XX  XX  XXXXXXXXXXXX
X    XX  XX XX  XXXXXXXXXXXXXX
     X XXX  X XXXXXXXXXXXXXXXX
      XX X XX   XX XXXXXXXXXXX
X     X XX X XXXX XXXXXXXXXXXX
