XX XXXXXXXXXXX XXX X
X XXX XXXXXXXX XXXXX
X X XXX XXXX XXX XX 
XXXXXXX X XX XXXX XX
XXX  XXXX X XX    XX
XX  XXXXXX XXXXXX XX
XX X XX XX XX XX  XX
XX  XXXX X X XX X XX
XX   XXX X XX  XX XX
 XX  XX    XX  XX X 
 XX   X X  X  XX  X 
 XX     XX XX XX XX 
X XX      XX XXX X X
XXXX    XXXXXXX  X X
XX XX  X    XXX XX X
XX XX        X XXX X
XX  XX  XXXXXX XX  X
 XX XXX  XXXX XXX XX
 XX XXXX  XXX XXX X 
 XX  XXXX  X XXXX   
