XXXXX   XXXXXX  XXXX   XXXXX  
XXX      XXXXX XXX  XXXX X XX 
XX       X XXXXXX XXXXX XX XXX
XX        X XXXXX XXX  XX XXXX
X          XXXX XXXXXXXX XX X 
X         XX XXXXX  XXXXXXX X 
XX       XXXXXXXX    X XXX XXX
XX XXXX   X X XX      X XXX XX
XXX XXXX  XX  XX     XXXXXXXX 
XX XXX X      X     XX   XXX  
XX X X XX     X       XXX XX  
XXX X   X     X      XXX X X X
 XXX       X  XX     X XX  XXX
 XXX     XXX  XXXX          XX
X XXX   XXX  XXX XX         XX
XXXXXXX      XX X X         XX
  XXXXXXX   XXXX     XXX  XXXX
 X XXXXXXXXXXXXXX   XXXX   XXX
XX  XX     X XX XX   XX   XX X
XXX  XXX  XX XX XXX      XX   
XX    XXXXX   XX XXXX   XX   X
XX      XX    XXXX XXXXXX XXXX
X            XX XXXXXX XX   XX
XXXXX        XX XXXXX   X  XXX
   XXX      XX XXXX X      X  
     XX     XX XXX X X    XX  
     XXX   XX XXXX X X   XX  X
XXXXX XX  XXX XXX XX  XXX   XX
    XXXXXXXX XXXX  XX  XX  XX 
XXXX   XXX  XXXXXX  X     XX  
