  XXXX    XXXX 
 XXXXXX XXXXXXX
 XXXXXX XXXXXXX
 XXXXXX XXX XXX
 XXXXXX XXX  XX
 XXXXXX  X   XX
 XXXXXX    XXXX
  XXXX   XXXXXX
  XXXX   XXX   
   XX    XXX   
   XX    XXX   
               
   XX    XXX   
  XXXX  XXXXX  
   XX    XXX   
