XXXXXXXX X X XXXXXXX
XXXXXX  XXXXX XXXXXX
XXXXX XX    XX XXXXX
XXXX X        X XXXX
XXX X          X XXX
XXX X X      X XX XX
XXX X         X X XX
XX X X        X X XX
XX X  XX    XX   X X
XX XX  XXXXXX  XXX X
XX X XX      XX XX X
X XX XXXXXXXXXX  X X
X X XX XXXXXX XX XX 
X X XXX  X   XXXX X 
 XXXX XXXXXXXX  XXXX
 XXX X   X    XX  XX
X   X XXXXXXXXX  X  
XXXXXX  XXXXX   XXXX
XXXXXX X     X XXXXX
XXXX   XXXXXXX  XXXX
