XXXXXX   XXXX    XXXXXXXXXXXXX
XXXXX  XXX  XXX    XXXXXXXXXXX
XXX   X    X X XX   XXXXXXXXXX
XXX  X X XX   X  XX  XXXXXXXXX
XX  XXXXXX  X  X  XX XXXXXXXXX
X XXXXXXX  XX XXX  XX XXXXXXXX
X XXXXXX XXXX XXXX  XX XXXXXXX
X XXXXXXXXXX XX XXX XX XXXXXXX
 XXXXXXXXXXX XX  XXX XX XXXXXX
 XXXXXXXXXXXXX    XXX X XXXXXX
 XX XXXXXXXXXX    XXXX X XXXXX
XXX  XXXXXXXXX  XX   X X XXXXX
XXXX XXXXXXXX   XXXX XXX XXXXX
XXXXXXXXXXX    X XX   XX XXXXX
XXXXXXXX XXXX  XX     XXX XXXX
XXXXXXX X XX   XX     XXX XXXX
XXXXXX     X    XX    XXX XXXX
XXXXXX            X   XXX XXXX
XXXXXXX            X  X XX XXX
 XXXXXX   XX  XX  XX  X XX XXX
 XXXXXX   X    XXX X X XXX XXX
  XXXXXX   XXXX  X   XXX XX XX
  X XXXX      XXX   XXXX XX  X
 XXX XXXXX         XXXXX XX   
XXXXXX XXXXX      XXXXX XX    
XX XXX XXXXX XXXXXXXXXXXXX    
X XXXXX XX XX     XXX XXX     
X XXXXXXXX   X  XXX  XXXX     
  XXXX  XX X  XXX   XXXX      
  XXX   X XXX X  X XXXX       
