 XX XX  XXXX  X
XX XX      XX X
X XX  XXX   X X
X X  XXXXX  X X
X X X XXX X X X
X XXXXXXXXX X X
X  XXX   XXXX X
XXXXXX X XXX  X
  XXXX   XX  XX
 XXXXXXXXXXXXX 
 X  XXXXXXXXX  
XX XXXXXXX   XX
   X XX  XX X X
X  X X  X XX  X
XXXX XXXX  XXXX
