XXXXXXXXX   XX  XXX 
XXXXXX      X XXXXXX
XXX        X XXXXXXX
X  X  XX   X XXXXXXX
   XXXXX   XXXXXXX X
  XXXXX    XXXXXX X 
 XXX XXX   XXXXXX XX
 XXXXXXXXX  XXXX XXX
  XXXXXXXXXX XXX XXX
    XXXXXXXXXXXX XX 
  X  XXXXXXXXXX     
  X  XXXXXXXXXXX    
  X   XXXXXXXXXX    
XX X  XXXX XX XX    
 XX XX XXX   XX     
     X XX   XXXX   X
    XX XXXXXXXXX XX 
XX    XX    XXXXX  X
XXXXX           XXXX
XXXXXXXXX           
