 XX X   X X   XX  XX  XXXXXXXX
 X  X   X  X XXXXX XX    XXXXX
 X  XXXXXX X X   X  X      XXX
 XX XXXXXXXX X XXX XX       XX
  X  XXXXXX  XX  XXX    X X  X
 XXXX XXXXXXX XX  X  XXXXXXXX 
XX  XX XXXX XXXXXX XXXXXXXXXXX
X    X X X   XXXX XXXXXXXXXXXX
X  X X   X X XXX XXXXXXXXXXXXX
XX  XX   XX XXX  XXXXXXXX XXXX
 XXXX     XXXX   XXXXX XX XXXX
   X      XXX   XXXXX XX   XXX
 XXX      XX     XXXXX    XXXX
XX X      XX    XXX X X  X X X
X  X      X     XXX X      X X
X XX XXX XXX    XXXX         X
X X X  X   XX    XX   XXXX   X
XXX   X   X X XXXXXX   XX   XX
 XXX       XX X    XXXX   XXXX
X XXXXXXXXXX  X    XXXXXXXXXXX
 XXXX XXX     X  XXXX X  XX XX
 XXXX XXX   XXXXXX XX XXXX   X
X XXX XXX  XX XX X  X  XX     
X  XX XXXX X X X X  XX      X 
XX XXX   X XXXXX  XXX X     X 
XXXXXXXXXX X   X  X   X     X 
XXXXXXX    X   X  XX XX     XX
XXXX  XXX  XX XX   XXX       X
XXX     X   XXX     XXXXXXXXXX
XXX    XX    X       XXXXXXXX 
