 X XX         XX  X 
X   XX       XX X X 
X XX XX     XXX X X 
X XXX XXXXXXXX XX X 
X XXXXX  XXX XXXX X 
X XXXX    X   XX XX 
XX XXX    XX   XXX  
XXXXXXX  X X  XXXXX 
 XXXX XXXX  XXX XXX 
  XX X XX    X X XXX
 XX  XXXX    XXX XXX
 XXX   X  XXXX  X XX
 XXXXXX    XXXXXX  X
 XX  XX     X X    X
 X    X X     X    X
 X    X XXXXXXX   XX
X X   XX XXX X  XXX 
X XXXXXXX   XXXXXXXX
XX XX XXXXXXXX  XXXX
XXX XX  XXXXX     XX
