XXXXXXXXXXXXXXX XXXXXXXXX     
XXXXXXXXXXXXXXXX  XXXXXXXXXX  
XXXXXXXXXXXXXXXX    XX  X  X  
XX  XXXXXXXXXXXXX    X  X  X  
X     XXXXXXXXXXX    X  XXXXXX
     XX XX XXX  XX XXXXX   XXX
    XX   XX X   XX X X X   XXX
    X  XXXX XX  XX X XXXXXXX X
      XX XXX X XXX X   X      
 XXX       X XXXXX XXXXX  XXXX
X  XX      XX XXXX        X  X
XXX X       X XXXXX     XXXXX 
XXXX        X X XXX   XXXXX  X
XXX    XX    XX  XXX  X XX XX 
 XXX  XXX   XXX  XX    XXXXXX 
 XXXXX X    X X   XX   XXX   X
  XXXXX    XX    XXX    XXXXX 
X   XX   XXXX   XXXXX   XXX  X
 XX  X     XXXXXXXX XXX XXXXX 
     X     XXXXXX     XXXXXXX 
            X          XXXXXX 
          XXX         XXXXXX  
       XXXX          XX  X X X
   XXXXX X          XXXXXXXX X
 XXX   XXX         XX  XXX XXX
 X  XXXX XX      XXXXXXXXX XXX
 XXXX   XXXX    XXX XXXXXX XX 
XX   XXXX  XXXXXX  XXXXXXX X  
XXXXX    XXXXX    XXXXXXXX XXX
XXXXXXXXXX   X  XXXXXXXXXX XX 
