 XX   XXXXXXXXX   XX
XXX XXXXXXXXXXXXX  X
XX XXXX XXXXXXXXXX X
XX X XX XXXXXX XXXXX
XXXX XX  XX XXXXXXX 
XXXXXXXX  XX   XXXX 
 XXX  XX   XX   XXX 
 XXX XXXX    XXX XX 
X XXX XXXX  XX XXXXX
X XX XXX      XXXXX 
X  X XX       XXX XX
 X XX    X       X X
 X XX            X  
XX XXX   XX X   XX X
X XXXXX         XX X
X XXXXXXX     XXXX X
XXXXXXXXXXX XXXXXXXX
XXXXXXX XXXXXXX XXXX
XXXXX  XXXXX XX   XX
XX     XXX   X      
