XXXXX      XXX    XXXXXXXXXXXX
X   XX   XXXXXX  XXXX  XXX    
X X  X XXX    XXXX   X XXX XX 
X XXXXXXXX    XXXX XXX XXX XX 
XXXXX X X      XXXXXXX XX  X  
XXXXX  XX  XXX XX XXXXXXX  X  
 XXX   XX  X  XXX  XXXX XXXXXX
 XX     XX     XX   XXX XXXXXX
XX  XXX  X     X XXX  XXXX  XX
X  X   X XX   XX X  X  XXX X X
X XXX XXX  XXXX XXX XX XXX XXX
X XXXXXXX      XXXXXXX XX  XXX
X XXXXXXX      XXXXXXX XX  X  
X XX XXXX      XX XXXX XXXXX  
XX X   XX       X    X XXXXXXX
XX  XXXX  XXXXX  XXXX  XX     
XX        X   X        XXXXXX 
XX  XXX    X X    XX  XXXXXXX 
XX   XXX    X   XX    XXXXXX X
 XX   XXXX    XXXXXX XXXXX  XX
  X XXXXXX    XXXXX XXXXXXXXXX
XXXX XXXX      XXX  X  XXX X X
X XX               X  XXXX X X
XX  XX             X  XXXXXX X
XXX  XX           XX XXXXXX  X
XXX   X          XX  XXXXXXXXX
XXXX  XXXXXXXXXXXX  XXXXX  X  
 XXXX  XXXXXXXXXXXXXXXX XXXX  
   XXXX XXXXXXXXXXXXXXX XXXX  
    XXXXXXX      XXXX   XX   X
