    XXX     XXX  XXXXXXXXXXXXX
   XXXXX  XXXXX XXXXXXXXXXXXX 
  XXX  XXXXXXX  XXXXX         
  XXX  XXXXXX  XXXXXXXXXXXXX  
  XXXXXXXXX    XXXXXXXXXXXX   
  XXXXXXX     XXXXXX          
  XXXXXXX     XXXXXXXXXXXX    
   XXXXXX    XXXXXXXXXXXX     
   XXXXXXX   XXXXXX           
   XXXXXXX  XXXXXXXXXXXX      
    XXXXXXX XXXXXXXXXXX       
    XXXXXXXXXXXXXX            
    XXXXXXXXXXXXXXXXXX        
   XXXXXXXXXXXXXXXXXX         
   XXXXXXXXXXXXXX             
   XXXXXXXXXXXXXXXXX          
    XXXXXXXXXXXXXX            
XX  XXXXXXXXXXXXXXXX          
 XX  XXXXXXXXXXXXXXXX         
X XX XXXXXXXXXXXXXXXXX        
XX XXXXXXXXXXXXXXXXXXXX       
XX  XXXXXXXXXXXXXXXXXXXX      
XX XXXXXXXXX  XXX  XXXXXX     
X XX XX XXXXX  XXXX XXXXXX    
 XX  XX  XXX   XXX   XXXXXX   
     X   XX    XXXXX  XXXXXX  
     X   XXX    XXX    XXXXXX 
        XX      XX      XXXXXX
       XX       X        XXX  
     XXXXXX   XXXXXX      X   
