  XX XXXXXXX  XXXXXXXXX  
  X XXXXXX     XXXXXXXX  
  XXXXXXXXXX XXXXX XXXX  
XXX      XX XXXXX XXXXX  
   XXXX   XXX    XXXXXXX 
XXXXXXXXXX     XXXXXXXX X
XXXXXXXX     XXXX XXXXX X
XXXXXXXXX  XXX XXX XXXXX 
XXXX X XXX XX    XXXXXXX 
XXXXX X    XXX    XXXXX X
XXXXX      XXX     XXXXX 
XX  X      XXX     XXXX  
X   X       XX    XXXX   
     X       X    XXXXX  
     X      X X  XXXXX X 
     X   XX XXXX XXXXX X 
      X XX   XXXX XXXXXX 
      X X       X XXXXXXX
      X XXXXXXXX  XXXXXXX
     XX X       X XXXXXXX
     XXX        XXXXXXXXX
    XXXXX     XXXXXX XXXX
XXXXXXX X      XXXX XXXXX
XX XXX XXX    XXXX  X XXX
XXX XX XXXXXXXXXX  X XXXX
