 XXXXXXXXX     XXXXXXXXXXXXXX 
XXX     XXX   XXXXXXXXXXXXXXXX
X         X   XXXXXXXXXXXXXXXX
X         X   XX  XXXX    XXXX
X         X   XX           XXX
          XXX XX           XXX
 XXX   XXX  X XX            XX
XX  XXX  XX X XXXXX     XXX X 
 XXXX XXXX  X  X  XXXX XXX  X 
   X   X  XX   X XX XX XX X X 
  X     X X    XX    X      X 
X XXX XX  X     X    X      XX
XXXXXXXXX X     X    XX     XX
 XX     XXX   XXXX          XX
XXX XXX XXXX XXX X  XXXXX  X X
X XXXXXX XX XXXX XXXX   XXXX X
XX      XX XXXXX  XX XXX XX  X
XXXXXXXXX XXXXXX   XXXXXXX  XX
XXXX XXX XXXXXXX X  XXXXX  XXX
XXX   X  XXXXXXX XX       XXX 
XX XX  XXXXXXXXXXXXXX   XXXXX 
X XX X XXXXXX XXXXXXXX XXXXX X
 XX XXXXXXXXX XXXXXXXX XXXXX X
XX XXX  XXXXX XXXXXXXXXXXXXX X
X X  XX XXXXX XXXXXXXXXXXXXX X
 XX  XX XXXXX  XXXXXXXXXXXXX X
XXXXX    XXXXX XXXXXXXXXXXX XX
XX       XXXXX XXXXXXXXXXX XXX
 X       X                XXXX
 XX      X XXXXXXXXXXXXXXXXXXX
