  XX X XXX     XXX XXXX  XXXXX
 X  X XXX         XXXXXX  XXXX
 X XXXXX          XXXXX XX XXX
 X XXXXX           XXXXX X XXX
 X X XXX           XXXXXXXXXXX
 XXX XX           XX XXXX XXXX
XX XXXX             XXXXX  XXX
X XXXXX   XXXXXX  XXXXXXXX XXX
XXXXXX  XX  XXX  XXXXXXXXXXXXX
XX XX  X   XXXXX XXXXX XXXX XX
XX XX    XX XX    XXX  XXX XXX
 X XXX             XX  XX   XX
  XXXX             XXX XXXX XX
X XXXXX       XX    XXXXXX XXX
X X XXXXX    XXXXXXXXXXXX XX X
 XXXXXXX   XXX  XXXXXXXXX XXX 
 XX XXX  XXXXXXXXXXX XXXX X X 
XXXXXXXX  XXXX      XXXX XXXX 
XX XXXXX   XX  XXXXXXXXXXXXX  
X  X XXXX   X   XXXXXXXXXXX  X
X XX XXXXXXX       XXXXXXXX XX
XXX XXXX XXXXX      XXXXX XXX 
 XXX XXXX XXXXXX   XXXXXX XX  
 X XX XXX    XXXXXXXXXXX  XXXX
 XXXXXXXXX    XXXXXXXX  XXXXXX
  XX XXXXX   XXXXXXXX XXXXX XX
 XX  XXXXXX   XXXXXXXXXXX     
XX XXXXXXXX XXXX XXXXXXX      
X XXXXXXXXX X    XX XXX  XXXXX
X XXXXXXXXXXXX   X  XX  XXX   
