X XX  XXXXXXXXXXX   
 XXX XX X XXX X XX  
XXX  XXX XXXXX XXX  
 XXX  XXXXXXXXXX    
X XXXXX  XX XXX     
X  XX          XXXX 
XXXX         XXXXXXX
 XX  XXXXXXX XXXXXXX
XXX   X X X   X XXXX
XX    XXXXX  X X XXX
XX    X   X  X   XXX
XX   XXX XXX XX   XX
XX   XXX XXX X   XXX
XXXXXX XXX XXXXX XXX
XXX  XXX XXX  XXXXXX
XX XXXX  XX  XX  XXX
XXXX XXXX XXXX    XX
XXXXXXXXXXXXXX      
XX          XX  X   
XXX         XX  X   
