 XXX     XXX XXXXXXX
X  X    X  X   XXXXX
X  XXXX X  X      XX
XXXXXXXXXXX         
 XXXXXXXXX   XX    X
XXXXXXXXXXX X  X  X 
XXX  XXX  X X XXXXX 
XXX XXXXX X  XXXXXXX
XXXXX XX XX XXXXXXXX
XXXX   X  X X XXXX X
XXXX XX X X XX X  XX
 XXXX    X  XX XX XX
   XXXXXX    XX  XXX
  XXXXXXXX    XXXXXX
 XXX XXXX X  XXXXX X
 XXX  XX  X XX XXX X
XXXXX    XX XXX   XX
XXXXXXXXXXX XXXXXXXX
XXXXXXXXXXX XXXXXXXX
 XXXX XX XXXXX XX XX
