    XXXXXXX    
   XXXXXXXXX   
  XXXXXX XXXX  
  XXXXXX XXXXXX
  XXXXXXXXXX   
   XXXXXXXX    
    XXXXX X    
   XXX XX  X   
  XXXX XX  XX  
 XXXXX XX   X  
 XXXXX XX   X  
XXXXX XXX  XX  
XXXX XXXX  X   
  XXXXXX  X    
XXXXXXX XXXXXX 
