   XXXXXXXXXXXX   XXX X X
  XXXXXXXXXXXXXX   X X XX
 XXXXXXXXXXXXXXXX   X XX 
 XXXXXXXX  XXXXXX    XXX 
XXXXXXXXXXXXXXXXXX   X XX
XXXXXXXXXXXXXXXXXX    X X
XXXXXXXXXXXXXXXXXX    X X
XXXXXX XXXXXX XXXXX    X 
XXXXX XXXXXX   XXXX     X
XXXXXXXXXXX   XX XXX    X
 XXXXXXX    XX   XXX     
 XXX       XXXXX  X      
 XX XXXXX   XX XX        
 XX  XXX   XX      X     
 XX XXX X  X      XX     
  XX X      X     XX     
  XX        XX    XXX    
  XXX        X    XXXXXXX
  XXX      XX     XXXXXXX
 XXXXX       XX   XXXXXXX
 XXXXXX   XXXX   XXXXXXXX
  XXXXXX         XXXXXXXX
  XXXXXXX       XX X XX X
  XXXXXXXXX    XXX X   X 
   XXXXX  X XXXXXX X   X 
