    XXXXXXXXXXXXXXXXXXX  
    XXXXXXXXXXXXXXXXXXX  
    XXXXXXXXXXXXXXXXXXX  
 XXXX              XXXX  
XXX   XXXXXXXXXXXX    XXX
X  XXXXXXXXXXXXXXXXXXX  X
XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX  XXX XXXX  XXXXXXX
 XXXX XXXXX XX  XXXX XXXX
 XXX     X  XX       XX X
XXXX    XX  XXX     XXXXX
XXXXX  X       X   XXXXXX
X XXXX XXX XXXXX XXX X XX
XXXXX  XXXXXXXX   XX X XX
XX XXX  XXX      XX XX XX
XX XXX   X XX   XXX X XXX
XXXXXXX XXXXXX  XX XXXXXX
X XXXXX X   XXX X  XXXXXX
X XX XX       X X XXXXX X
XX XX X XXXXXX  XXXXXX XX
 XXXXXX XXXXXXX  XXXXXXXX
 XXXXXX  XXXX   XXXXXXXXX
  XXXXX        XXXX XXX  
    XXXX      XXXX  XXXX 
   XXXXXXXXXXXXX  XXXXXXX
