       XXXXXXXXXXXX     XXX   
 XXXXXX XXXXXXXXXXXX  XXX     
    XXXXX XXXXXXXXXX XXXX     
XXX  XXXXX XXXXXXXXXXXXX XXXX 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
XXX XXXXXXXXXXXXXXXXXXXXX XXX 
 XXXXXXX XXXXXXXXXXXXXXXXXXX  
  XXXXX XXXXXXXX XXXXXXXXXX   
 XXXXX XXXX XXXX  XXXXX XXXX  
 XXXXXXXXXXX XXX   XXXXX XXX  
XXXXX XXX  XXXXX  XXXXXX XXXX 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
XXX X XXX X   XXXXX  XXXXXXXXX
X   X XX  XX   XX XX  XX  XXX 
    X  X     X XX     XXX XXX 
    XX XXXXX X  XXXXX X XXXXX 
     XXXXX       X XXXX XX X  
       XX X XXXX    XXXXX  X  
        XXX    X XX XXX       
         XXX      XXX       XX
          XXXXXXXXXX      XXXX
  XXXXX  XXXXXXXXXX      XX XX
 XX   XXXXXXXXXXXXXX     X XXX
XX     XXXXXXXXXXXX    XXXXX X
X       XX X  XXXXXX   X  X  X
XXXXX    XXXXX XXXXXXX XX XXXX
XXXXXX  XX XXXX XX XXXX XXXXX 
