XX XXXXXXXXXXXXXXXXX
X XXXXXXXXXXXXXXXXXX
 XXXXXXX XXXX XXXXXX
X XX XX XXXX XXX XXX
 XX XX XXXX XXX XXXX
XX XX X XXXXXX XXXXX
X XX             XXX
XXX  XXXX  XXXX  XXX
X X  X  X  X  X  XXX
X X                X
X X     X          X
XXX X X X    X X   X
XXX               XX
XXX     XXXX      XX
XXXX    XXXX     XXX
XXXXXX  XXXX    XXXX
XX  XXX       XXXXXX
X  XXXXXXXXXXXXXX   
  XXX  X     XXXX   
  X X  XX   XX  X   
