XX XX XXXXXXXX XX XXXXXXX
 XX XX XXXXXXX  X  XXXXXX
X XX XX XXXXXX X XX  XXXX
X XX XX XXXXX XXX XXX XXX
X XX XX XXXX XX XX  XX XX
X XX XX XXX XX X XXX XX X
X XX XX XXX X  X  XX  X  
 XX XX  XX XX  X    XX   
 X XXX  XX X   XX       X
XX XX  XX XX X  XXXXXXXXX
X XX   X XX  X    XX  X X
X X     XX  XXX       X X
X X    XXX XXXXXX   XXXXX
XX X  XXX XX    XXXXXXXXX
 X X  XX XX      X  XXXXX
 X X XX XX       XX XXXXX
  XX XX XX       XX  XXXX
X XX XX XX       XX  XXXX
XX X XX XX       XX  XXXX
XXXX XX XX       X  XXXXX
XXXXX XX XX     X   XXXXX
XXXXX  XX X   XX  XXXXXXX
XXXXXX       XX XXXXXXXXX
XXXXXXXX  XXXXXX    XXXXX
XXXXXXXXX      XXXXXXXXXX
