    XXXXXXXX   
   XXXXXXXXXX  
   XXX X X XX  
   XX       X  
   X XXXXXXXXX 
  XXXXXXXXXXXXX
XXXXXXXXX XXXXX
XXXX  XX  XX XX
XXXXX     X  XX
XXXXXXXXX  X XX
XXXXXX    XXXXX
XXXXX   XXX   X
 XXX           
XXXXX          
XXXXXXX X     X
