      X  XXX        
XX    XXXXXXX X     
 XXXXX XXX XXXX  XX 
  XXXXXXX   XX   XX 
  XXXXXXX   XX   XX 
X    XXXX   XX   XX 
 X X XXXXX XXXX   X 
 XXXXXXXXXXXXXXX XXX
     XXXXXXXXXXXXX X
   XX XXXXXXXXXX X X
  XXXX      X XX  X 
 XXXXXXXXXXXXX XXXX 
XXXXXXXXXXXXXXX     
XXXXXXXXXXXXXXXX    
XXXXXX  XXXXXXXX    
 XXXX     XXXXXX    
   XXX     XXXXX    
   XXX    XXXXX     
  XXX     XXXX      
           XXXX     
