 XXX XX X  XXXXX         
XXX XXXXXXXXXXXXXX       
XXX XXXX XXX XXXXXX      
XXX XXX XXX   X   X      
XXX XXXX    XXXXX X      
XXX X X XX  XXXX XXXX  X 
 XX XX XXX XX       XX XX
 XX X  XXXXX XXXXXXX XXXX
X X    XXXX XX X  XXX XXX
XX     XXX XX    X XXX XX
     XXXXX XXXXXXXXXXX XX
     XX XX XXXXXXXXXXX XX
    XXX XX XXXXX XXXXX XX
   XXXX XX XXXXXXXXXXX XX
  XX XX XX XXXXXXXXXXX XX
 XXX XX  X XXXXXXXXXXX  X
XX X XX  XX XXXXXXXXX  XX
XX X XXX XXX XXXXXXX  XXX
 X X XXX XXXX        XXXX
 X X  XXXXXXXXXXXXXXXXXXX
XXXXXXXXX X            X 
XXXXXXXXX   X XX XXX XXX 
 X  XXXXXXXXXXXXXXXXXXX  
XXXX  X  X           X   
    XXXXX XXXXXXXXXXX X  
