  XXXXXXXX           XX  
X          XXXXXXXXXXXXXX
X        XXXXXXXXXXXXXXX 
XXX XXXXXXXXXXXXXXXXXXXX 
        XXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXX
XXX XXXXXXXXXXXXXXXXXXXXX
X X    XXXXXXXXXXXXXXXXXX
X X    XXXXXX XXXXXXXXXXX
XXX XXXXXXX    XXXXXXXXXX
       XXXX      XXXXXXXX
X X    XXXX        XXXXXX
X X XXXXX X XXXX    XXXXX
X X    X    X        XXXX
 X     X    X XX      XXX
    XXXXX     XX   XXX XX
XXX    XX  X  XX      XXX
X       XXXXX    X   XXXX
XXX XXXXXXXXXX  X   XXXXX
X       XXX XXX XXX X XXX
XXX      XXXX XX  XX XXX 
    XXXXXX XX  XXX XXXX  
            XXXXXXXXXXX  
XXXXXXXXXXXX    XX     XX
         XX              
