XXXXXXXX XX XXXXXXX  XXX  X XX
XXXXXXXXXXXX XXXXX XXX      X 
XX XX X XX  X  XXXXXXXXXX   XX
XXXX   X  XXX XXXXX  XXX X  XX
XXXXX XX XXXXXXX XXXXXXXX X   
X X  X XX  X XXXXXX X X XX X X
XX   XXX XXXXX X     X XX XXXX
XX XX XXXX X   XX  XXXXXX  X X
XXX XX XX  X X    X   XXXXX XX
XXXXXX XXX  XX     X  XX X XX 
XX  XXXX  X     X   XX XX  XX 
X  XXXX      X          XX    
XXXXXX XXXXX       X  XX XX X 
XX  X  X X   X           XXX X
X                XX  X  X X X 
 X XXXXXXXXX    XXX       X   
XX   XXXXXXXX  XXX    XXX    X
XXX    XXXXXXX  XX   XXXXXX   
X XX      XXXXX XX XXXXXXXXXX 
 X  X X X  XXXXXXXXXXXXXXXXXXX
 XXX         XXXXXXXXXXXXXX   
X X X         XXXXX          X
X  X  X XXXX XXXXXXXX     X  X
     XXXXXXXXXXXXX  X  X XX XX
  XXXXXXX  XXXXXX  XX      XXX
X          XXXXXX      XX XXXX
           XX XXX     XX XXXXX
X X       XX   X   XX   XXXXXX
  XX      X   XX  X    XXXXXXX
        XX    X     XXXXXXXXXX
