          XXXXXXXXXXXXX  
               XXX       
                X        
             XXXXXX      
X           XXXXXXXXX    
XX X       XXXXX  XXXX   
XXXXXXXXXXXXXXXX  X  XX  
 XXXXXXXXXXXXXXX  X   XX 
  X    XXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXX
            XXXXXXXXXXXXX
               X    X    
               XX   XX   
      XXXX     XX   XX   
     XX  XX              
    XX  XXXX        XXX  
   XX  XXXXXXX     XXXXX 
  XX   XXXXXXXX  XXX XXXX
 XX   XXXXXXXXXXXX   XXXX
XX    XXXXXXXXXX    XXXXX
X    XXXXXXXXX     XXXXXX
     XXXXXXXX    XXXXXXXX
    XXXXXXXX    XXXXXXXXX
   XXXXXXXX    XXXXXXXXXX
  XXXXXXXX     XXXXXXXXXX
 XXXXXXXX     XXXXXXXXXXX
XXXXXXXX      XXXXXXXXXXX
XXXXXXXX     XXXXXXXXXXXX
XXXXXXX    XXXXXXXXXXXXXX
XXXXXX    XXXXXXXXXXXXXXX
