  XXX    XXXX  
 XX   X    XXX 
XX X XX   X  XX
XXXXXXXX   XX X
X XX  XXX X XXX
X X    XXXXX X 
XXX    XXX XXX 
XXX  X XXXXXXXX
XXXX  XXXXX XXX
XX XXXX X XX XX
XX X       XXXX
XX    XX    X X
XXX  XXXX X   X
 XXX  XXXXX  XX
  XXXX     XXX 
