            X            
         XXXXXXX     XXXX
  XXXX  XX XX XXX  XXXX X
  X XXX XX XX XXX XXXX  X
  X  XXXXXXXXXXXXXXXX   X
  X   XXXX  X   XXXX   XX
  XX XXXX XXX X XXXXXX X 
   X XXXX X X   XXXXXXXX 
   XXXX X  XXX  X XXXXX  
    XX   XXXXXXX    XXXX 
  XXXXX    XXX  XXXX XXX 
   XX       X        XXX 
  XXXXX     X  XXXX   XX 
   X X     XXXXXXXXX  XX 
   X XXXXXXXXXXXXXXX  XX 
   X  XXXXXXXXXXXXXX  XX 
XXXX   XXXXXX    XXX XXX 
X  XX  XXXX       XX XX  
X   X   XX      XXX XXX  
X   XX   XXXXXXXX   XX   
XXXXXXX           XXXXX  
  XXXXXXXXXX   XXXXXXXX  
   XXXXXXXXXX XXXXXXXXXX 
     XXXXX       XXXXXXXX
       XXXXXX XXXXXXXXXXX
