  XXXXXXXXXXXXXXXXXXX         
   XXXXXXXXXXXXXXXXXXX        
 XXXXXXXXXXXXXXXXXXXXXXX      
XXXXXXXXXXXXXXXXXXXXXXXXX     
XXXXXXXXXXXXXXXXXXXXXXXXXXX   
 XXXXXXXXXXXXXXXXXXXXXXXXXXX  
   XXXXXXXXXXXXXXXXXXXXXXXXXX 
  XXXXXXXXXXXXXXXX XXXXXXXXXXX
  XXXXXXXXXXXXXX    XXXXXXXXXX
   XXXXXXXXXX   XXX  XXXXXXXXX
      XXXXXX  XXXXXX  XXXXXXXX
     XXXXXX XXXX X XX XXXXXXXX
     XXXX X    X XX X  XXXXXX 
        X X    X XX    XXXXX  
        XXX    X XX   XXXX XX 
        XX            XXX X X 
        XX   XX        X XX X 
       XX     XXXXX      X  X 
       X   XX     XX     XX X 
       XXXXX       X       XX 
         XXXXXX    X   XXXXX  
         XX   XXX X  XXXX     
        XX      XXX XX  XXX   
    XXXXXX         XX  XX X   
  XXXXXXX       XXXX   XX XX  
 XXXXXXXXX   XXXXX    XXX  X  
  XXXXXXXXXXXXXXX    XXXX  XXX
   XXXXXXXXXXXXXX XXXX X   X X
 XXXXXXXXXXXXXXXXXXX   X   X  
XXXXXXXXXXXXXXXX   XX XX   X  
