 X      X                
 XX    XX                
 XXXXXXXX                
XXXXXXXXX                
XXX  X  X                
XXX XXX X                
XXXXXXXXXXXXXXXXX        
XXXXXXXXXXXXX X X        
XXXXXXXXXXXXXXXXX XX  XXX
XXXXXXXXXXXXXXXX   XX X  
 XXX  XXXXXXXXX     XXXX 
  XXXX    X X      XXXXX 
  XXXXXX          XXXXXX 
 XXXXXXXXXXXXX   XXX XX  
XXXXXX XXXXXX   XXX  XX  
XXXXXXX        XXX XXXXX 
XXXXXXXX      XXX  X  XX 
XXXXXXXXXXXXXXXX  XXX XX 
XXXXXXXXXXXXXXX   XXXXXX 
XXXXXXXXXXX        XXXXX 
XXXXXXXXXXXX         XX  
XXXXXXXXXXXX        XXXX 
XXXXXXXXXXXX       XXXXXX
XXXXXXXXXXXX      XXXXX X
XXXXXXXXXXXX      XXXXX  
XXXXXXXXXXXX      XXXXXX 
XXXXXXXXXXXX       XXXX  
XXXXXXXXXXX        X  X  
XXXXXXXXXXX       XX XX  
XXXXXXXXXX               
