XXXXXXXX      XXX    XXXX
XXXXXX           XXXX  XX
XXXXX           XX XXXX X
XXXX              X  XXXX
XXXX              XXX XX 
XXXXX XXX          XXXXXX
XXXXXXXXXX         XX X X
XXXXX XXXXXX       X XXXX
XXXX   XX         XXXXXX 
XXX     XX        X X  XX
XX   X            XX XX X
XXX   X        XXXX XXX X
XXXXXXXX     XXXX  XXX  X
XXXXX XXXX  XXX XX X   XX
XXX    XXXXXXXX XXXXX  XX
XXXXX    XXXXX  X X   XXX
XXXXXX  XXXXXX XX X  XX X
XXX  XXXX  XX  X  XXXX  X
XXXXXX  XX  X X  XXX   XX
XXXXXXX  X      XXX  XXXX
XXXX        XX XX  XXXXXX
XXX       XX  XX XXXXXXXX
XX      XXX  XXXXXXXXXXXX
XXXXXX XXX  XXXXXXXXXXXXX
     XX   XXXXXXXXXXXXXXX
