XXX XXX XXXXXXXX XXXX XX XX XX
XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
XXXXXXX     XXXXXXXX   XXXXX X
XX XXXX       XXXX     XXXXX X
XXXXXXX  XXX           XXXX XX
XX XXXX       XXXX     XXXXXXX
XX XXXX   XXXX     XX  XXXXX X
XXXXXX          XXX     XXXXXX
XXXXX  XXXXXX  X   XXXX  XXXXX
XX XX XXXXXXXX X XXXXXXX XXX X
X   X  XX  XXXX  XXXX  X XX  X
X X X XXXXXXXXXXXXXXXXX    X X
X XX   XXXX XXX XXXXX  XX XX X
X XX X  X  X  X  XX   X X XX X
X XX XX  XX  XX  X XXX XX X XX
XX X XXXX   XXX  XX   XXX X XX
XX   XXXXXX XXX  XX XXXX XX XX
XXX X XXXX XXX    XX XXX X XXX
XXXXX XXXX XXXX  X XX XX XXXXX
XXXXXX XX  XX XXXX  X X  XXXXX
XXXXXX  X X  XXX X  XX  XXXXXX
XXX XXX X X XXXXXXX XX  XX XXX
X  XXXX   XXXX    XXXX  XXX XX
 XXXXXXX   XX XXX XX X XXXXX  
XXX XX XX X XX   XX    XXXXXXX
XX  XX  X X  XXXXXX X XX XXXXX
 X  XXX XXXX       XXXX XXX  X
 X  XXX  XXX  XXXX  XXX XXX  X
 X  XXXX  XXX  XX  XXX  XXX  X
 XX  XXXX  XXXXXXXXXX  XXX  XX
