XXXXXXXXXXXXX  X     XXXX
X XXXXX   XX  XXX   XX  X
XXXXXX XXX XXXXXXXXXX    
X  XXX XX     XXXXX  XXX 
X  XXX X       XXXX   XX 
XXXXXX    XX           X 
XX  XXX     XXXXX  XX    
XX  XXX   XXXXXXXXX X   X
XXXXXXXX XX  XXXXXXX   XX
XXX  XXX X  X XXX  XX  X 
XXX  X X XX  XXX X  X XX 
XXXXXXXX  XXX  XX  XX X  
XX  X XX     X  XXXX XXX 
XX  X XXX   X  X    XX X 
XXX    XXXX  XX   XX   X 
XXXXX  XXXXXX  XXXX    XX
XXX XXXXXXXXXXXXXXXX  XXX
XXX XX   XXXXXXXXXXXXXXXX
XX  X XXX X       XXXXXX 
XX  X     X          X   
X   X XXX XXX       XXXXX
XXXXXX    XXXXXXXXXXXX  X
     XX  XXXXXXXXXXXXXX  
  XXXXXXXX   XXX  XX XX X
XXXXXXXXXXXXXXX  XX   XXX
