  XXX   XX  XXXX XXXXXXXXX  XX
 XX   XXX  XXXX XXXXXXX XXX   
XXXXXXXX  XXXXXXXXXXX XXXXXXX 
X  XXXXX XXXX XXXXXX  XXX  XXX
  XXXXX  XXXX XXXXXX  XXXX  XX
 XXXXX  XXXX XXXXXX   XXXXX  X
XX XXX  XXXX XXX XXXXXXXXXXX X
X XXX  XXXXXXXXX XXX  X XXXX  
 XXXX XX XXX XXXXX X  X XXXXX 
XXXXXXXXXXXX XX   XXXXX  XXXX 
XXX XX  XX XXXX XXXX X XX XXXX
X X XXXXXXXXXXX XX X XXX XXXXX
 XX XXXX X XXXXX    X X  XX XX
XXXXXXXX  XXX XX  XXXX   XXXXX
XXX X XXX  XX XXX       XXXX X
XXXXX  XX  XX   X       XX X  
XX XXX XX  X           XX  X X
XX XXX XX  XX          XX X  X
X  XXXXXXX  X         XX    XX
X  X XXXXX   X XXX    X   XXXX
  XX XX XXX               XXXX
  XX  XXXXX   XX          XXXX
  X   XXXXXX          X   XXXX
  X   XX XXXX       XX    XXXX
X     XX XXXXX     XX     XXXX
X     X  XXXXXX  XXX      XX X
XX    X   X XXXXXXX      XXX X
XXX  X    X  XXXXXX    XXX X X
XXXX       X XX X XXXXXXX  XXX
XXXXXX        X X XX XX       
