   X XXXXX X   
  X XXXXXXX X  
 X X  XXXXXX X 
X XX  X   XXX X
 XXX    X XXXX 
XXXXXX   XXXXXX
XXXXX X   XXXXX
XXXX XXX  XXXXX
XXXXXXX X XXXXX
XXXX X XX  XXXX
 XX  X XXX  XX 
X X         X X
 X XXXXXXXXX X 
  X XXXXXXX X  
   X XXXXX X   
