    XXX     XXXXXXX           
     XXX XXXXXXXXXXXX       X 
 XXXX XXXXXXXXXXXXXXXXX     XX
XXXXXXXXXXXXXXXXXXXXXXXX   XXX
XXXXXXXXXXXXXXXXXXXXXXXXX XXX 
X  XXXXXXXXXXXXXXXXXXXXXXXXX X
 XXXXXXXXXXXXXXXXXXXXXXXXXX XX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
X XXXXXXXXXXXXXXXXXXXXXXXXXX  
 XXXXXX XXXXXXXXXXXXXXXXXXX   
XXXXXXX XXXXXXX XXXXXXXXXXXX  
XXXXX X  XXXX X  X XXXXXXXXX  
XXXXXXXX X XX XXXXXXXXXXXXXX  
XXXX  XX X  XXXX   X X XXXXX  
X XXXXXXX X XXXXXXXX  XXXXXX  
X XX    XX XX X    XX XXXXXX  
X X XXXX XX  X XXXX XXXXXXX   
  X  XXXXXXXXXX XXXX XXXXXX   
  X  X XXX XXX  X XX XX   XX  
  X  X XXX X X  X XX X  XX X  
  X XXXX X X X XXXX XX XXX X  
  XX     XXX XX    XX XX X X  
  X XXXXX X   XXXXX X XX  XX  
  X      X          X XX  X   
  X      XXX        X    XX   
  XX           X    X  XXX    
   XX         XX   XXXXX      
    XX     XXXX   XX          
     XX          XX           
      XXXXXXXXXXXX            
