XX  XX   XX XX          XX XX 
XX  XX   X X XX        X  XX  
XX  XX  XX X XX XXXXX    X    
XX  XX  X XXX XXXXXXXXX       
XX  XX  X XX XXXXXXXXXXX  XXXX
XX  XX  X X XXXX XXXXXXXXXX   
XX  XX  XXXXXXX XXXX XXXXX XXX
XX  XX   XXX   XXX XXXXXXXXXX 
XX  XX   XX XXX X XXX XXXXXX X
XX  X  XXXX XX X  X  XX XXX XX
XX   XXXXXXX XX        XXXXXX 
XX   XXXXXXXX       XX XXXX   
XX  XXX XXXX    X  XX X XXX   
XX  XXX  XX   X XX  XX XXXX  X
XX  XXXX  XX  XXX    XXXXX  XX
XX XXXXXX     XX XX  XXXXX X  
XX XXXX XX     XXX    XXX X   
XX XXX               XXX XXXXX
XX XXX            XXXX        
XX XXX             X          
XX XXXX              X        
XXX X           X  X X XXXXXXX
    XX   X     XX  X X        
    XX   X   XXX  XX XXXX     
 XXXXX   XXXXXXX  XX XXXXXXX  
XXXXXX   XXXXXX   XX XXXXXXXXX
XXXXXX   XXXXXX   XX  XXXXXXXX
XXXXX     XXXXX    XX XXXXXXXX
 XXXX X X XXXXX     XXXXXXXXXX
  XXXXXXXXXXXXX X X XXXXXXXXX 
