XXXX       XXXXXXXXX
XX  XXXXXXX XXXXXXXX
X XXXXXXXXXX XXXXXXX
 XXXXXXXXXXXX XX  XX
XXXXXXXXXXXXXX XX  X
XXXXX  XXXXXXX XXXXX
XXXX    XXXXXXXXX  X
XXX      XXXXX  XX  
XX XX     XXXX   XXX
XX  X  XX  XXX    XX
 X      X  XX     XX
 XX  XX   XX      XX
XXXX  X  XX         
XX XX   XX   XX     
X           XXXX    
    XX     XXXXXXXXX
   XXXX    XXX   XXX
  XXXXX   XXXXXXXXXX
 XXXXX    XXXXXX   X
XXXXX    XXXXXXXXXXX
