XXXXXXXXXXXXXXXXXXXXXX XXX XXX
XXXXXXXXXXXXXXXXXXXXXX XX XXXX
XXXXXXXX  X XXXXXXXXXXXX XXXXX
XXXXXX       XXXXXXXXX X XX  X
XXXXXXX       XX XXXXX XXX XXX
XXXXXXXX    XX X XXXXXXXX XXXX
XXXXXX  XXXXXXX XXXX  XX  XX  
XXXXXX   XXXXXXXXXXXXXXXX  XX 
XXXXXX  XXX XX XXXXX XXXXXX XX
X XXXXX    XX  XX XX  X XX  XX
X   XX         XXXXXX   X   XX
XX   X          XXXXXX XX  XXX
XXXX   XXXX  XXXXXXXXXXXXXXXXX
XX      XX    XXXXXX XXXXXXXXX
XX           XXXXXXX XXXXX  XX
X          XX  XXXX XXX  X   X
     XX    X  XXXXXXXX XX X   
      XX    XXXXXXXXXX  XXXX  
      XXX     X XXXXXX X X XX 
      XXXXX   XXXXX X XX    XX
XX   XX  XXXXXXXXX XX X XX   X
XXXX XXX XX XXXXX XX    XXX   
  XXXXX XX XXXXX         XX   
   XXXX  XXXXX XX  X XX   XXXX
 XXXXXXXXXXX   X  XX  XX   XXX
XXXXXXXXXX   XXX  XXX  XX XXX 
XXXXXX  XXXX X    XXXX  XXXX  
XX     X       XX   XXXXXXXXXX
     XXXX   XXXXXXXXXXXXXXXXXX
   XXXX      XXXXXXXXXXXXXXXXX
