XXXXX    XXXXXX
XXXXXX  XXXXXXX
XXXXXXXXXXXXXXX
XXXXXXXXXXXXXXX
XXXX  XX XXXXXX
XXXX     XXXXXX
XXXX     XXX   
  XX X X XXX   
  X  X X   X   
  X   X    X X 
  XX      X  X 
    XX  XX   X 
     XXXX   X  
  XXXXXXXXXXXX 
XXXXXXXXXXXXXXX
