XXXXXXXXXX  X            
XXXXXXXXX  XXX           
XXXXXXXX  XXXXX          
XXXXXXX  XXXXXXX         
XXXXXX  XXXXXXXXX        
XXXX     X     X         
XXX X    X XXX X    X    
XX XXX   X X X X   XXX   
X XXXXX  X XXX X  XXXXX  
 XXXXXXX X     X XXXXXXX 
XXXXXXXXXX  XX XXXXXXXXXX
XXXXXXXXXX XXXXXXXXXXXXXX
XXXXXXXXX XXXXXX XXXXXXXX
X        XXXXXXXX        
  XXXX  XXXXXXXXXX  XXXX 
  X  X XXXXXXXXXXXX X  X 
  XXXX  X        X  XXXX 
        X   XXX  X       
XXXXXXXXX  X X X XXXXXXXX
        X  XXXXX X       
  XXXX  X  X X X X  XXXX 
  X  X  X  X X X X  X  X 
  XXXX  X  XXXXX X  XXXX 
        X        X       
XXXXXXXXXXXXXXXXXXXXXXXXX
