XXXXXXXXXXXXXXX
XXXXXXXXXXXXXXX
XXXXXXXXXXXXXXX
XXXXXXX  XXXXXX
XXXXX      XXXX
XXXXXXXX XXXXXX
XXXXXX XXXX XXX
XXX XXXX XXXXXX
XXX  XX   XX  X
  X    XXX    X
  X   XXXXX   X
  X  XXX XXX  X
   X XX   XX  X
   X         X 
    XX    XXX  
