  XXXXXXXXXXXXXXXX  
 XXXXXXXXXXXXXXXXXX 
 XXXXXXXXXXXXXXXXXX 
 XXXXXXXXXXXX XXXXXX
XX XXXXXXXXX X XXXXX
X XXXXXXXXX  XXX XXX
X XXXXXXXXXXX XXXXXX
XXXXXXX XX   XXX XXX
XXXXXX XX XXX X XXXX
XXXXXXX  XXX X XX X 
XXXXXXX  X    XX  X 
XXX XX          X X 
 XX  X       X    X 
XXXX         XXX X  
 XXXX X       XXXX  
 X XXXX     X   X   
  X XXXX   XXXXXX   
  XX  XXX    XX     
 X      XXX    X    
XX       XXXXXX     
