XXXXXXXXX XXXXXXXXXX
XXXXX XX  XXXX XX XX
XXXX  XX   XXXX XX X
XX X   X     XX XX X
XX XXX     XXXXX X X
XXXXXXXX XXXX XXXXX 
XX  XXXXXXXXXX  XXXX
X  XXXXX XXXXXXX XXX
X XXXXX   XXXX   XXX
X   XX   X  XXX  X X
XX        X         
XX     XXXXX       X
XX  XX  X    XX   XX
XX  X XX XXX  X   XX
XX   XXXXXXXX     XX
XX                XX
XXX   XXXXXX     XXX
 XXXX         XXXXXX
  XXXXX XX   XXX XXX
   XX XXXXXXXX   XXX
