XXXX XXXXXXXXXXXX   XXXXX
XXX XXXXXXXXXXXXXX  X XXX
XX XXXXXXXXXXXXXXXX XXXXX
XX XXXX XXXXXXXXXXX XXXXX
X XXXXX  XXXXXXXXXXX XXXX
X XXX XXX  XXXXXXXXX XXXX
X XXXX    X      XXX XXXX
X XX  XXX  XXXXX XXX XXXX
X XX XXXX    XX X XX XXXX
X XX X X X     X  XX  XXX
X XXX    X        XX  XXX
XX XX             XX  XXX
XX XX    X X      XX  XXX
XX XX     XXX    XX X XXX
XXXX X  XXXXXX   XX X XXX
XXXXXX XX   XXX  XX X XXX
XXXXXX X      X XXX X XXX
XXXXXXX X XX  XXX X X XXX
XXXXXXXXXX  XXXX  X XXXXX
XXXXXXX XXXXXXX  X X  XXX
XXXXXXX  XXXXX   X XXX XX
XXXXX X         X XXXXX  
XXX  XX          XXXXXXXX
   XXXXX       XXXXXXXXXX
XXXXXXXXXXXXXXXXX XXXXXXX
