XXXXXXX               XXXX XXX
X XXX        XXXXXXX   XXXXXXX
XXXX       XXXXXX  XXX  XXXXXX
XXXX X   XXX X   XX  XX  XX  X
XXX XX  XXXXX XXXXXXX XX XX  X
  XXX  XXXXXXXXX XXXXX XX XXXX
       XXXXXXXXX  XXXXXXX XXXX
X  XX XXXXXXXX X    XXXXX XXXX
X XXX XXXXX        XX XXX  XX 
X XX  XXX  XXX       X XXX XXX
XXX   XX  X             XX  XX
XXX  XX             XX  XX  XX
XX   X    XXX      X XX XXX  X
XX X XX  XX X       XX XXXX  X
XX X XX  X XX   XX     X XX   
XXXX XXX             XXX X    
XXXX XXXX XXX          XXX   X
 XXX XXX XXX   XXXXXX  XXX   X
 XXX  X       XX   X    X   XX
 XXXX XXX      XXXXX    X   XX
X XXX  XX       XXX    XX  XXX
X XXXX  XX            XX   XXX
XX XXXXX  XX         XX   XXXX
XXX XXXXXX  XXXX   XXX XXXX X 
XXXX  XXXXXXXXXXXXXX XXX   XXX
XXXXXXXXXXXXXXXXXXXXXX      X 
X XXXX    XXXXXXX XX XX       
XXXX  XXXX      X XXXXXXX X X 
XXX  XXXXXXXX  XXXXXXXX  XXXXX
XXX XXXXXXX   XXX    XX   X X 
