XXXXXXX   XXXXXXXXXXXXXXX
XXXXX      XXXXXXXXX XXXX
XXXX     X XXXXXXXX    XX
XXXXX   XX      XX  X   X
XXXXXXX XX         XX   X
XXXXXXXXX        XXX    X
XXXXXX  XX        XX    X
XXXXX            XXX   XX
XXXXX XXX          XXX XX
XXXX XX  X     XXX   XXXX
XX   X XXX    X  XX  XXXX
XXX  X XXX    XXX X  XXXX
XX    XXX     XXX X    XX
XXX XX   XX    XXX    XXX
XXX XX   X   X    XX   XX
XXXX     XXXXX    XX  XXX
XXXXX     XXX        XXXX
XXXXXXXX  XX        XXX X
XXXXXXXXXX        XXX XX 
XXXXXXXX      XXXXXXXX XX
XXXXXXXX X X X XXX XXXXXX
      XXXX XXX  XX  X    
   XXXXX        X  XXXX  
 XXXXXXX X    X XXXXXXXX 
   XXXXXX XXXX XXXXXXX   
