XX XX X   XX  XXX        
 XXX  XX XXX  XXX XX     
  X  XXX XXX XXX XXX     
 XXX XXXXXXXXXXXXXXX XXX 
XX XXXXXXXXXXXXXXXX XX XX
     XXXXXXXXXXXXXX X   X
     XXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXX XXX 
    XX   X XX X   XX     
    XX     XX     XX     
    XXX   XXXX   XXX     
    XXXXXX    XXXXXX     
     XXXX  XX  XXXXX     
 XXX XXXX X XX XXXX      
XXXXX XXXX    XXXX       
XXXXXXXXXXXXXXXXXXX      
 XXXXXXXXXXXXXXXXXXXX    
  XXXXXXXXXXXXXXXXXXXX   
   XXXXXXXXXXXXXXXXXXXX  
    XXXXXXX  XXXXXXXXXX  
     XXXX      XXXX XXX  
     XXX        XXX      
    XXXX        XXXX     
    XXX          XXX     
    XXX          XXX     
