   X  XXXXXXXXXXXXXXXXXX  XXXX
   XXXXXXXXXXXXXXXXXXXX   XXXX
 X  XXXXXXXXXXXXXXXXXXXXX  XXX
 XXXXXXXXXXXXXXXXXXXXXX    XXX
  XXXXXX XX XXX XX XXXX    XXX
X  XXX X  X  XX  X XXXXX   XXX
X XXXX       X      XXXX   XXX
X X X XXX      XXXX  XXX   XXX
X X X X XX     X  XX  XX  XXXX
XX  X                 XX  XXXX
XX  XX XXX     XXXX   XX  XXXX
XXX  X X          X  XXX  XXXX
XX   XX X       X    XXX XXXXX
X     X XX  X   XX   X XXXXXX 
     XX    XX          XXXXXXX
XX   X                XXXXXXXX
XXXX X               XXXXX    
XXXXX X   XXXXXX    XX     XXX
XXXXX XX   XX X    XX  XXXXX  
XXXXXX XX   XX    XX    XXX   
XXXXXXX XX      XXXXXXX  XX   
   XXXX  XXX  XXX  X  XX  XX  
    XXXXX  XXXX    XXXXXX  XXX
     XXXXX    X   XXXXXXXX  XX
   XXXXXXX XXXXXXXXXXXXXXXX XX
 XXXXXX   XXX  XXX     XXXX  X
XXXXXX XXXXXXX  XX XXX  XXXX X
XXXXXX XXXXXXXX    XXXX XXXX X
XXXXX XXXXXXXXXX XXXXXX  XXX X
XXXXX XXXXXXXXX XXXXXXXX XXX  
