XXX     XXX         
XXX     XXXXX       
XX       XX XXX     
             XXXX   
   XX  XX   XXXXXX  
X  XX  XX  XXXXXXXX 
X  X    X  XXXXXX XX
XX        XXXXXX   X
 XX  XX  XXXXXX     
  XX    XXXXXXX     
  XXXXXXXXXXXX      
  XXXX XXXXXXX     X
  XXXX XXXXXX    XXX
  XXXX XXXXXX   XXXX
 XXXX XXXXXX   XXXXX
 XXXX XXXXXX  XXXXXX
XXXX XXXXXX  XXXXXXX
XXXXXXXXXX   XXXXXXX
XXXXXXXXX XXXXXXXXXX
  XXXXXX  XXXXXXXXXX
