XXXXX   XXXXXXXXXXXX
XXXX  X XXXXXXXXX  X
XXX   X XXXXXXX    X
XX   XX XXXXX   XX X
XX XXXX    X  XXX  X
X XX   XXX   XXX   X
X    XXXXXX XXX   XX
  XXX XXXX  XXX   XX
X XX   X     XXX  XX
   XX X XXX   XX XXX
       XXX X   X XXX
 XX X   XXX    X XXX
 X  XXX     X   XXXX
X XXX     XXXX  XXXX
XX  XX  X  XX  XXXXX
XXX  XXX      X  XXX
XXXXX    XX  XX X  X
X XXXXXXXX  XX   XX 
XX  XX    XXX    XXX
XXXXXXX XXXX      XX
