  XXXXXXXXXX   
 XXXXXXXXXXXX  
XXXXX    XXXXX 
XXXX  XX  XXXXX
XXXX XXXXXXXXXX
XXXX XXXXXX XXX
XXXX XXXXXX XXX
XXXX  XX XXXXXX
XXXXX    XXXXXX
XXXXXXXXXX  XXX
XXXXXXXXXX   XX
XXX    XXX   XX
XXX    XXX   XX
XXXX   XXXX  XX
 XXX   XXXX   X
