XXXX         XXX    
    XX      XXX XXX 
 XX  XX XXXXXX XXX X
 XXX  XXXXXXXXX XX X
  XXXXXXXXXXXXXX XX 
X XXXXXXXXXXXXXXX XX
X XXXXXXXXXXX  XXX X
X X XXX   XX  XXXX X
X  XXXXXX  X XX  XX 
X XXXXXXXXXXXX X  X 
X XXX  X XX   XX  XX
 XXX  XXX      X XXX
  XX  XXX  XXX XXXX 
   XX  XX   XX XX XX
    XXXXXX    XX X X
    XXXXXXXXXXX  XX 
XXX XXXXXXXXXXXX  XX
  XXX  XXXXXXXXXX XX
X  X  XX  XX XXXX  X
XX X X   X XX XXX XX
