  X X   X X  X      
 XX  X XX XXXXXXX   
  XX XX XXX X X     
 X  XXXXXXXXX XX    
  XXX XXXXXXXXX     
X X XXXXXXXXXXXX XXX
XXXXXXXXXXXXXXXX XXX
  XXXXXXXXXXXXX  XXX
 XXXX   XX   XXX XXX
 XXXX X XX X XXX XXX
  XXXXXXXXXXXXX  X  
   XXXXXXXXXXXX  X  
   XX       XX   X  
   XX       XX   X  
    XXXXXXXXX    X  
 XXXXXXXXXXX    XXX 
 X  XXXXXXXXXXXXXXX 
 X   XXXXXXX    XXX 
XX   XXXXXX      X  
      X  X       X  
