XXXXXX  XXXXXXX
X           XXX
XXXXX   XXXXXXX
XXXX   XXXXXXXX
XX       XXXXXX
X  XXXXX XXXXX 
  XXXXX  X     
XXX  XX XX XX  
 XX  XXXXX X   
      XXXXXX   
XXXX   XXXXX X 
XXXXX  XXXX  X 
XX     XXXX X  
XX XXX XXX  X X
X  XXX   X XXXX
