XXXXXXXX  XXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXX  XXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXX XXXXXXXX
XXXXXXX XXXXXXXXXXXXX  XXXXXXX
XXXXXXX XXXXXXXXXXXXX  XXXXXXX
XXXXXXX XXXXXXXXXXXXX    XXXXX
XXXXXXX XXXXXXXXXXXXX XXXXXXXX
XXXXXXX XXXXXXX    XX      XXX
XX        XXXX XXXX   XXXX  XX
XX XXXXXX XXXX  X X   X X   XX
X  X  XXX XXXX              XX
X XX   XX XXXX              XX
  X XX XX XXXX              XX
 XX  X  XXXXXX              XX
 XXX    X XXXXX    X        XX
 X  X   X  XXXX            XXX
 XX      X  XXXX   XX X   XXXX
 X X        XXXXX    X   X XXX
 XX         XXX XX      XX   X
 XXX       XXX    X    X   XX 
 X XX      XX XXX  XXXX  XXXXX
 X XXX   XX  XXXXX       XXXXX
 X X X  XX   XX XXXXXXX XXXXX 
 X X XXXX    XXX  X X  XXXXX  
XXX  XX      X XXXX XXXXXXX XX
X X XX       X  X  XX XXXX  XX
XXX X       XXX   XXX XXX XXXX
   XXX     XXXXX XXXX    XXXXX
