  XXXXXXXXXXXXXXXX  
 XXXXXXXXXXXXXXXXXX 
 XX  XX    XXXXXXXX 
           XXXXXXXX 
 X           XXXXXXX
 XXX   XXXXX  XXXXXX
 X XX XX  X   XXX  X
 XXXXXXXX  XX  X X X
  XXX XXXXX    X X X
X      XXX   X X X X
X    XX      X    XX
X  X  XX    XX   XXX
X XXXXXX  XXX     X 
XXXX   XX  XX    XX 
 XX XXXXX  XX    XX 
 XX  XXX   XX  XX XX
  XX    XX XX XX XXX
   XX XXX XX XX  XXX
 XXXX    XXXXX  XXXX
XXXXXXXXXXXX    XXXX
