 XXXX XXXXXXXXXXXXXXXXX XXXXXX
 XXXXX XXXXXXXX XX XX XXXXXXXX
 XXXXXX  XXXXXXXX X XXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXX X XXX
  XXXX XX XXXXXX XXX XXXXXXXXX
  XXXX XX  XXX X X X X XXXXXXX
  XXXX  X   X  XXXXXXXX XXXXXX
  XXXXXXXXX  XXXXXXXXXXXXXXXXX
   XXXXXXXXX XXXXXX    XXXXXXX
    XX XXXXX XXX        XXXXXX
    XX     X   XXXXXXX  XXXXXX
     X XXXXX  XX XX  X  XXXX  
     XXX X X  XXXXXXX    XXX  
      X XXXX  X           X  X
      X   XX  XXX         X  X
      X  XXX  XXX        XX  X
      X XX X    XX       X  XX
       X   X     XX     XX  X 
       X   X            XXXXX 
       XX  X  X        XXXXXXX
        XX  XXX        XXXXXXX
        XX            XXXXXXXX
        XXX XXXXX     XXXXXX X
        X X X   XX   XXXXXX  X
XXXXX   X X   XX     XXXXX   X
   XXXXXX XX   X    XXXX X   X
  XXXXXX   X   X   XXXX  X   X
XXXXXXXX   XX     XXXX   X  XX
XXXXXXXX     XXXXXXXXX  XX  XX
XXXXX         XXXXXXX   X  XXX
