         XXXXXXX    
        XXXXXXXXX   
        XXXXXXXXXX  
 XXXXX  XXXXXXXXXX  
 XXXXXX XXXXXXXXXX  
XXXXXXX  XXXXXXXXX  
XXXXXXXXXXXXXXXXX   
XXXXXXXXXX   X  XX  
XXXXXXX          XX 
XXXXXXX   XXX  XX XX
XXXXXXX   X X X X XX
 XXXXXXX  XXX XXX XX
   XXXXX  XXX XXX XX
   XX        XXX   X
   X  X      X X X X
   X XXX     XXX XX 
   X   XXX      XX X
    XXX  XXXXXXXX X 
      XXX        X  
         XXXXXXXX   
