   XXXXX XXXXXXX        XXXXX 
  XXXXXXX XXXXXXXXXXXXXX XXXX 
 XXXXXXXXXXXXXXXXXXXXXXXX  X  
XXXXXXXXXXXX   XXXXX    XXX   
XXXXXXXXXX      XXXX     XX  X
XXXXXXXX    XX   XX  XXX XXX X
XXXXXXXX  XXX          XX XX X
XXXXXXXX  X               XX X
XXXXXXXX                  XX X
XXXXXXXX     XX      XX   XX X
XXXXXXX     XXXX    XXXX  XX X
XXXXXXX    X XXX    X XX XXX X
XXXXXXX    X  XX    X  X XX  X
XXXXXXX    X   X    XX X XXX X
XXXXXXXX   XX XX     XX   XX X
XXXXXXXX    XXX  XXX       X X
XXXXXXX       XXXXXXXXX XX X X
XXXXXXX     XXX   X   XX XX  X
XXXXXX  XXXXX    XXX   X     X
 XXXXX XX  XX   XXXXXXXX XXX  
 XXXXX    XXXXXXXXXXX     X X 
   XXXX  XX   XXXXXXX         
X  XXXXX X     X  XX    XXX   
X  XXXXX       XXXX   XXXX  XX
X XXX XXX            XXXX  XXX
X X     XXXX        XXXXX  XXX
X  X   XXXX        XXXXXXX  XX
XXXX  XXXXX       XXXXXXXXX   
XXXX XXXXX       XX  XXXXXXX  
XXXX XXXXX      XX   XXXXXXXXX
