XXXXXX X XXXXX X XXX
XXXXXX XX XXXX XX XX
XXXXXX XX     XXX XX
XXXXXX XXXXXXXXXX XX
XXXXX XXXXXXXXXXXX X
XXXX XXXXXXXXXXXXXX 
XXX XXXXXXXXXXXXXXX 
XXX XX XXXXXXX XXXXX
   XX X XXXXX X XXXX
XX XX  XX  XXX  XXXX
 XXXXXXXXXXXXXXXXXXX
   XXXXXXXXXXXXXXXXX
XXXX  X  X  X  X XXX
  XXX X  X  X XXXXXX
  XXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXX
XXXX             XXX
XXX    X    X     XX
XX  X XXX  XXX  X XX
