  XXX XXXXXXXXXXXXXXXXXXXXXX  
  XX  XXXXXXX XXX XXXXXX XXXX 
  XX XXXXXXX  XXX XXXXXXX XXX 
 XX  XXXXXXXXXXXXXXXXXXXX XXX 
 XX XXXXXXX  XXX  XX XXXXXXXX 
 XX XXXXXXX XX    XXXXXXXXXXX 
 XXXXXXXX XXX    XX  X XXXXXX 
 XXXXXXX     X          XXXXX 
 XXXXXXXXXXX XX    XXXXXXXXXX 
 XXXXXXXXX  XXX   XXX X XXXXX 
 XXXXXX    XXXX         XXXXX 
 XXXXXX      XX         XXXXX 
 XXXXX       X         XXXXXX 
 XXXXX      XX         XXXXXX 
 XXXXX      XXX X      XXXXX  
 XXXXXX               XXXXXX  
 XXXXXXX  XXXXX X  X  X XXXX  
  XX XX    XX XXXXXX    XXX   
  XXXXXX    XX   XX    XXX    
XXX XXXX     XXXXX     XXXXXX 
 XX   XXX     XXX     XXXX XXX
   XXXXXXX           XXX   XX 
XXXXXX XXXXX       XXXXXXXX   
XXXXXX XXXXXXX   XXXXX XXXXXXX
    XX  XX XXXXXXX XXX XXX    
 XXXXX  XXX  XX    XX  XXXXXX 
     XX  XXX      XXX  XX     
  XXXXX   XXXX   XXX  XXXXXX  
      XX    XXXXXXX   XXX     
   XX XXX      XX    XXXX XX  
