    XXXXXXXXXXXX    
  XXXXXXXXXXX XXXX  
 XXXXXXXXXXXX XXXXX 
 XXXXXXXXXXXX  XXXX 
XXXXXXXXXXXX    XXXX
XXXXXXXXXXX      XXX
XXXXXXXXXXX XXXX XXX
XXXXXXXXX  XX  X XXX
XXXX    X  X     XXX
XXX  XXX    XXX  XXX
X X XX XX  XX XX X X
X X     X  X     X X
X                X X
XXXX            XXXX
XXXX            XXXX
 XXX   XXXXXX   XXX 
  XXX          XXXX 
 XXXXXXX    XXXXXXX 
 XXXXX XXXXXX XXXXX 
 XXXXX        X XX  
