XXXX XXXXXXX XXXXXXX XXXXXXX X
XXX XXXXXXX XXXXXXX XXXXXXX XX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
   X       X       X       X  
XX X XXXX  X XXXXX X XXXXX X X
XX X X    XXXXXXXXXXXXXXXX X X
XX X   XXXXX           XXXXX X
XX X XXXX         XXXXX  XXXX 
XX X XX   XXX      XXXXXX XXXX
XXX XX   XXX X      XXXXXXX XX
    XX   XX  X    X XXXXXXX XX
    X  X  X XXX XXX  XXXX XX X
   XX  XX  XXXXXXXXX XXXX XX X
   XX XXXX  XXXXXXXXXXXX XXX X
   X  XXX  XXXXXXXX XXXXXXX XX
   X  XXXX XXXXXXX  XXXXXXX X 
      XX XX XXX      XXXXXX   
  XXX X  XXXXX       XXX XXX  
 XXX XXX X XXX       XXX  XXX 
   X  XXX   XX        XX   XX 
   X X XX    X        XX   XX 
   XX  XX    X       XX   XX  
    XX X     XX      XX   XX  
    XXX       X     XX    X   
X X  XXX      X     X     X   
     XX  XXXX X     X    XX   
   XX  XXXXXX XXXXXX XXXXX    
XX  XXXXXXXX XXXXXX XXXX XXXXX
          XXXXXXXXXXXXXXXXXXXX
  XXX   X        XXXXXXXXXXXXX
