XX      XX       XX 
XXX    X  XXXXXXX  X
XXX    X XXXXXXXXX X
XXXX   XXXXXXXXXXXXX
XXXX     X XXX XXX  
 XXXX    XX  XXXXX  
 XXXXX   XX  XXXXX  
  XXXX   XX  XXXXX  
  XXXX    XXXXXXX   
  XXXXX    XXXXXXX  
   XXX    XXXXXXXXX 
   XX XXXXXXX XXXXXX
    X XXXXX  XXXXXXX
    XX     XXXXXXXXX
     XXXXXX XX  XXXX
      XXXXX   XXXXXX
       XXX XXXXXXXX 
       XXX XXXX     
        XXX         
         XXXX       
