   X          X     
   XX      XXX X    
   XXX    XXXX XX   
 X  XXX  XX XX XXX  
 XX   X XX   XX XXX 
 XXXX  XXXXX  XX   X
  XXX XXXX XX  XXXXX
XX    XXX X XX  XXXX
XXXXX XXX  XXXX  XXX
 XXXX XXXXXXXXXX  XX
      XXX   XX XX  X
 XXXXX XX X X X X XX
XXXXX  XX   X  XXXX 
XXX   X XXXXXXXXXX  
XX  XXXX XXXXXXXX   
   XXXX   XXXXXX    
  XXX   XX          
  XX   XXX XX XXX   
      XXXX XXX XXX  
    XXXX    XXX XXX 
