   XXXX  XXX  XXXXXXXXX  
  XXXX XXXXXXX   XX  XXX 
 XXXX XXXXXXXXXXX XXX XXX
 XXXXXXXXXXXX XXXXXXX  XX
 XXXXX XXXX XX  XXX XX  X
XXXXX  XXXX  XXX XXX XX X
XXXXX  XX XX  XXX XXX XXX
X XXX   X XX    X  XXX XX
X XXXX  XX XX XXXX XXX X 
X XXXX      XXXXX XXXXXX 
 XXXXXXXXX  XXXXXXX XXXX 
 XXXXX XXX  X X XX  XXXXX
 XX XXX XX  X      XXXXXX
  XX X     XXX    XXXXXX 
  XX X     XXX   XXXXXX  
  XXXX     X XX  XXXXXX X
   XXX    XXXXX XXXXXXXXX
   XXXX      XX XXXXXXXXX
   X XX    XXXXX XXXXXXXX
   X      XXX X XXXXXXXX 
           XXX XXXXXXXXX 
        X      XXXXXXXX X
      XXXXX   XXXXXXXXXXX
   XXXXX XXXXXXXXXXXXXX X
 XXXXXXXXX  XXXXXXXXXXXXX
