 XXXXXXX    X   XXX    XX XXXX
XX X  X  XX  XXXXXXXXXXXXXXXXX
XXXXXX  XXXX   XXXXXXXXXXXXXXX
XXXXXXX XXXX    X  XXXXXXXXXXX
XXXXXX  XXX  XXXXX    XXXXXXXX
XXXX  XX   XXXX   XXXXX  XXXXX
XXXXXXX  X XXX     XXXXXX  XXX
X XXXX XXX XXX      XXXXXXXXX 
 XXXXXXXXXXXXX XXXX XXXXXXXXXX
XXXXXXX  X XX XX XX  XXXXXXXXX
XXXXXX X XXX  X  XX    XXXXXXX
XXXXX XX XX   XX XXX  XXX XXXX
XXXXX XX XX    XXXXXXX   XX XX
XXXXX X XX      XXXX  XXXXX XX
XXX X   XX       XX  XXXX XXXX
XX  XX XXX    XXXX   XXXXXXXXX
 XX    XX   XXX      XXXXXXXXX
 XX   X    XX        X XXXXXXX
 XX X X              XX XXXXXX
  XXX XX         XX  XXXXXXXXX
  XXXX XX    XX   XXXXXXXXXXXX
   XXX  X   XXXXXX XXX XXXXXXX
   XXXX XX       XXXX XXXXXXXX
    XXXX XX   XXX XX XXXXXXXXX
X    XXXX XX    XXX XXXXXXXXXX
X    XXXXXXXX    XXXXXXX X X  
X     XXXXXXXXX XXXXXXXXXXXXXX
X     XXXXXXXXXXXXXX X  XX    
XX     XXXX  XXXXXXXXXXXXXXXXX
XX      XXXX  XXXXXXXXXXXXXXXX
