  XXXX  XXXX   
 XX  XXXX  XXX 
XX           X 
   XX     XX XX
   XXXXXXXXX   
   XXXXXXXXX   
    XXXXXXXX   
   XX XX XXX   
XX XXXXXXXXX   
   XXX  XXX XXX
XXX XXXXXXX    
    XXXXXXX XXX
    XXXXXXXX   
    XXXXXXXX   
    XXXXXXXXX  
