  XXXXXXXXXXXXXXX   
 XXXXXXXXXXXXXXXXX  
 XXX    XXXXXXXXXX  
 XX          XXXXXX 
 XX           XXXXX 
 X  XXX   XXXX XXXX 
 X XX       XX XXXXX
 X X         X XXXX 
 X   XX   XX   XXX  
X      XXX   XXXXX  
X     X  XX   XXXX X
X     XXXXX    XXXXX
XX  X       XX XXXX 
 X  XXXXXXXXX  XXXXX
 XX   X   XX   X X X
  XX   XXXX   XX X X
XXXXXX      XXXX X X
XXXXXXXXXXXXX XXXXXX
XXXXXX XXXXX  X   X 
XXXXXX  XX   XX  XX 
