 XXXXXXXXXXXXXXXXXXXXXX  
XXXXXX  XXXXXXXXX X XXXX 
XXXXX XXXXXXXXXXXXXX  XX 
XX  XXXXXXXXXXXXXXXXX  XX
X  XXXXXXXX XXX XX XXX  X
  XXXXXXX XX XX  XXXXXX X
  XXXX XX XXXXXXXXXXXXXXX
 XXX X  X  XX    XXXXXXX 
XXXXXXXXX  X XXXX X XXXXX
XXXXX   XXXX X    X XXXXX
XXXX XXX XXXX    XX XX XX
XXX  X  XXX XXXXXX  X  XX
XXXX   XXX          X  XX
XXXXXXX  XX         X XXX
XXXX      X         XXXXX
XXXXX     XX        XXXXX
 XXXX         XX    XXXXX
  XXXX      XXXX   XXXXXX
  XXXXX  XXXXXXX  XXXXXXX
   XXXXX     XX   XXXXXXX
   XXX XX   XX   XXXX XXX
  XXXXXXXX      XXXX XXX 
  XXX XXXXXXX XXX XX XXX 
 XXX XXXXXXXXXXX  XXXXXX 
XXX XXXXXXX XXX   X XXX  
