XXX   X   X X X   X X XXX
XX  X   X X X X X   X  XX
XX  X X X       X X    XX
X X   X  XXXXXX   X X X X
X   X  XXXX  XXXX   X   X
X X X XX       XXXX   X X
X X  XX          XXX X   
X X XXXXXX     XXXXX X X 
X   XXXXX X   X XXXXX  X 
XX XXX    XX XX    XXX  X
XXXX  XXXX XXX XXXX  XX X
XX X XX  XXX XXX  XX XXXX
X XX     XX   XX     XX  
X XXX   XXXXXXXXX   XX X 
X XXX XXX  X X XXX  XXXX 
XX XXX     X X      XXX X
XXX XX    XXXXX    XX  XX
XXXXX X  X X X X   XXXXX 
X XXX X  XX X XX  XX XX X
XX XX XX XX X XX XXX X X 
XXX X XXX XXXXX XXX XXXXX
XXXXXXXXXX XXX XXX XXXXXX
X  X   XXXX   XXX XXXXXXX
   XXX  XXXXXXXX X X XXXX
 XXXX   XX X XXXX X X X X
