    XXXXXXX       XX  XX 
   XXXXXXXXXX    XX  XX X
  XXXX XXXXXXXX XXXXXX XX
  XXX   X XXXXXXXXXXXXXX 
  XXX X  X XXXXXXXXXXX   
  XX       XXXXXXXXXX  XX
  XXX  XX  XXXXXXXXXXXXX 
   XXX    XXXXXXXXXX     
    XXX  XXXXXXX         
     XXXX XXXX      XXXXX
   XXX XXX  XXXX   XX   X
  XX    XXX    XX XX   XX
 XX  XXXXXXX X  XXX  XXX 
XX  XX    XX  X     XX   
X  XX    XXX  X    XX    
X  X  XXXX X XXXXXXXX   X
X    XX      X    XXXX XX
XX  XXXX     X    XXXXXXX
 XXXX  XXXXXXX     XXXXXX
      XXXXXXXXX    XXXXXX
      XXXXX XXXXX   XXXX 
      XXX  XXX XXX XXXX  
      XX  XX  XXXXXXXXX  
      XXXXXX XXXXXXXXX   
       XXXXXXXXXXXXXX    
