XXXXXXXXX     XXXXXXXXXXXXXXXX
XXXXXXXX       XXXXXXXXXXXXX X
XXXXXXXX       XXXXXXXX XXXXXX
XXX XXXX       XXXXXXXXXXXXXXX
XXXXXXXXX     XXXXXXXXXXXXXXXX
XXXXXXXXXX   XXXXX XXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXXXXXXXXXXXXXXXXXXXX XX 
XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                          X   
                   XXX    X   
  X   X           XXXXX   X   
 XX   XX         XX   XX  X   
  XX XX          XXX XXX  X   
   XXX           XX X XX  X   
  XXX            XX   XX  X   
XX XX          XXXXXXXXXXXXX  
XXXXX       X XXXXXXXXXXXXXX  
  XXXXXXXXXXXXXX  XXXXXX  X   
  XXXXXXXXX XXX  XXXXXXX      
  XXXXXXXXX XXXX XXXXXXXX     
XXXXXXXXXX  XXXXXXXXXXXXXXXXXX
X X    X X   XXXXXXXXXXXXXXXXX
  X    X X    XX           XX 
  X    X X     XXXXXXXXXXXXX  
