X XXXXX XXXX XXX    XXXX  XXXX
XXXXXXX XXXXXXX  XXXXXXXXX XXX
XXXXXX X XXXXX XXXXXXXXXX    X
XX XXXX XXXXXXXXXXXXX XXXXX   
XXXXXXX XXXX XXXXXXX XXX X XX 
XXXXXXXXXXXX XXXXXX XXXX  XXXX
XXX  XXXXXXXXXXXXXXXXXX  XXXXX
XX XX XXXXXX X  XXXXXX XXXXX X
   XXXXXXX   XXX  XXXXXXXXXX X
 XXXXXXX      XXXX XXXXXXXX XX
XXXXX  XX      XX     XXXXXXXX
XXX X   XX     X     XXXXXXXXX
XXXX   XXXXXX  XX     XXXXXXX 
XXXX  XXXX   X  XX   X  X XX  
XXXX    XX  XX   X  XXX    XX 
XXXXX  XX  X X    XX  X    XXX
XXXXX       XX        XX XXXXX
XX XX      XX          XXXXXXX
X              X      XXXXXXXX
X    X        XX     XX XXXXXX
XXX  XX    XXXX     XX XXXXXXX
XXXXX  XXXXXXX     XX XXXXXXXX
XXX       XXX    XXX  XXXXXXXX
XXXX   XXX  X   XXX   XXXXXXXX
XXXXXXXXXXXXX  XXX   XXXXXXXXX
 XXXX  XXXXXXX XX    XXXXXXXXX
  XX   XXXXXXXXXX    XXXXXXXXX
 XX    XXXXXXXXXXXX XXXXXXXXXX
XXX   XX  XXXXXXXXXXXXXXXXXXXX
X XX XX     XXXXXXXXXXXXXXXXXX
