      X    X   
      XX   XX  
     XXX  XXX  
     X XX X XX 
    XX  XXX  X 
    XXXXXXXXXXX
X  XXXXXXXXXXXX
 XXXX  XXXX  XX
X  XX X XXX X X
 XXXXXXXX XXXXX
   XXXXXXXXXXXX
 X  XXXXX XXXXX
 X X XXXX XXXX 
XXX   XXX XXX  
XX  XXXXXXXXXXX
