  X      XX         
 X X     XX         
X X X   XXXXXX      
 X X   XXXXX XX     
  X X XXXXX X XX    
   X  XXXXXX XXX    
  X XXXXXXXXXXXX    
   X XX XXXXXXX XXX 
  X XXXX XX    XXXX 
   X XXXX XXXXXXX X 
  X XXXXXXXXXXXX  XX
 X XXXXXXXXX  XXX   
  X XXXXXX      XX  
 X XXXXXXXXXXX   XX 
X XXXXXXXXXXXX    X 
 X XXXXXXXXXXX    X 
X XXXXXXXXXXXX    X 
 X XXXXXXXXXX     X 
X X XXXXXXX  XXX XXX
 X XXXXXXXXXXXXXXXXX
