  XXXXX        
 XXXXXXXX      
XXXXXXXXX      
XX  XXX  X XXXX
XX XXXX XX XX  
XXXXXXXXXX XX  
XXXXX  XXX XXX 
 XXXXXXXX  XXXX
 X      XX   XX
X        XX XXX
X        XXXXXX
XX        XXXX 
XXX  XX   XXX  
XXXXXXX    X   
X XXXX     X   
