  XX XXX XXXXXXX XXX XX  
 XXXXX XXX  X  XXX XXXXX 
XX XX XX         X  XX XX
X  X XX   XX     XX  X  X
  XX X   XX       XX XX X
  X XX   X      X  X  X X
X XXX  XXX  X   XX XXXXXX
XXXX  XXXX  XX   X  XX XX
 X X  X  X  XXX  XX XX XX
XX X  XXXX  X XX  X  X XX
X XX XX  XX X  XX X  X  X
X XX X XXXX X XXXXX  XX X
X XX XX X XXXX X XX  XX X
X XXXX XXX XX XXX X  XX X
  X X  XXX  X XXX X XXX X
 XX X  XX     XX  X X X X
 XX XX            XXX X X
XXXX XX     X    XX X X X
XX XXXXX       XXXX X X  
X XX XX   XXX   XX  X XX 
X XX  XX       XX  XX XX 
X XXX  XXX   XXX  XXX  X 
X XXXX  XXXXXXX  XXXXX X 
X XXXX  XX   XX  XXXXX X 
X XXXXXXXXX   XXX XXXX X 
