XX X  XXXXXXX XXXXX    XX
X  XXXXXXXXXXXXXXXXXX   X
    XXXXXXXXXXXXXXXXXX   
  XXX XXXXXXXXXXX  XXXX  
 XXXXX  XXXXXXX   XXXXX  
XXXXXXX         XXXXXXXX 
XX XXXXXXXXXXXXXXXXXXXXX 
X XXXXXXXXXXXXXXXXXXXXXXX
X XXXXXXXXXXXXX XXXXXXXXX
 XXXXXXXXXXXXX  XXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXX   XXXXXXXXX
XXXX  XXXXXXXXXX XXXXXXXX
XXXX  XXXXXX XX XXXX  XXX
X XXX  XXXXX XXX XXX  XXX
X XXX   XXX  XXX  XX  XX 
  XXX    X        XX XXX 
  XXXX       X X XXXXX   
  XXXX           XXXXX   
   XXXX  XXX    XXXXX    
   XXXXX       XXXX X    
   XX XXX    XXX XX      
X   XX  XXXXXXX XXX     X
XX  XX   XXXX   XXXX   XX
XXX  X XXXX   XXX XXX XXX
