 XXXXXXXXXXXXXXXXXXXXXXXXXXX  
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
XXXXXXXXXXXXXXXXX XXX XXXXXXX 
XXXXXXXXXXXX XXXX  XX  XXXXXXX
XXXXX XXX XX  XXX  XXXX XXXXXX
XXXXX XX  XX  XXX XX    XXXXXX
XXXXX XX   XX  XXXX     XX XXX
XXXX   XXXXXX  XX    XXXXXX XX
XXXXXXXX XXXX  XX XXXXX  XXX X
XXXXX          X  XXXX   XXX  
XXXXX             XX XX  XXXX 
XXXXX    XXXX      X     XXXX 
XXXXX  XXXXX       XX    XXXX 
XXXXX XXXXX         XXX  XXXXX
XXXXX   XXXXX         X   XXXX
 XXXXX   XXX         XX   XXXX
 XXXXXX             X     XXXX
  XXXXXX               XXXXXX 
X  XXXXX              XX   XX 
XXXX XXXX      XXXXXXXX   XX  
XXXX  XXXX    XX   X       XX 
  XX  XXXXX   XX X          XX
   XX  XXXXX   XXX      XXX  X
    X   XXXX    X       XX   X
    X     XXX  XX XXX    XX   
   XX       X  XX XX          
 XXXXX          X  XX         
 XXXXXXXX       XX          X 
XXXXXXXXXXXX     XX        XX 
XXXXXXXXXXXXXXX   XXX     XXX 
