  XXXXXXXXXXXXXXXXXX    XXXX  
 XXXXXXXXXXXXXXXXXXXX    XXXX 
XXXXXXXXXXXXXXXXXXXXXX   XXXXX
XXXXXXXXX XXXXXXXXXXXXX   XXXX
XXXXXXXX  XXXXXXXXXXXXXX   XXX
XXXX XX   XXXXXXXXXXXXXXX  XXX
XXX XXX   XXXXXXXXXXXXXXXX  XX
XXX XX    XXX XXX XXXXXXXX  XX
XXX XX    XXX  XX  XXX XXXX XX
XX    XX   XX   X   XX  XXX  X
XX  XXXXX  XX     XXXXX  XXX X
XX XXX  XX  XX   XX  XXX XXX X
XXX         XX           XXX X
XXX   XXX          XXXX    X X
XXX  XXXXX        XXXXXX   X X
XXX  X XXX        X XXXXX  X X
 XX XXXXXX        XXXXX    XX 
 XXX  XXXX  X      XXXX   XXXX
 XXXX  XX  XX       XX       X
 X  XX     XX                X
 XX  X                       X
XXX  X                       X
XXXX X    XX XXXX           XX
XXXXXX     XXXXXXXX      XXXXX
XXXXXXX    XXX  XX       XXXXX
XXXXXXXX    XX XX      XXXXXXX
XXXXXXXXX    XXX      XXXXXXXX
 XXXXXXXXX          XXXXXXXXXX
 XX XXXX XX        XX XXXXXXX 
 X  XX X  XXX    XXX  X XX  X 
