    X   XXX           XXX
   XX   X X           X X
  XXX   X X XXXXXXXXX X X
 XXXX   X XXXXXXXXXXXXX X
XX XX  XX XXXXXXXXXXXXX X
X  XX  XX XXXXXXXXXXXXX X
X  XX  XX XXXX X X XXXX X
X  XX  XXXX XXX   XXX XXX
X  XX XXXX    XX XX    XX
X  XX XXXXXXXX XXX XXXXXX
X  XX XXXX  XXX X XXX  XX
X  XX XXXX  XXXXXXXXX  XX
X  XX XXXXXX  XX XX  XXXX
XXXXX XXXX XXXXX XXXXX XX
  XXX XXX    XX   XX    X
 XXXXXXXX     XX XX     X
XX    XXX XXXXXXXXXXXXX X
X XXXXXXX X X XXXXX X X X
X     XXX XXX X   X XXX X
X XXXXXXXX XX XXXXX XX XX
X     XXXX  X X   X X  XX
X XXXXXXXXX XXX   XXX XXX
X     XXXXXX         XXXX
XXXXXXXX XXXXXXXXXXXXXXX 
 XXXXX X XXX XXX  XXX XX 
