XXX XXXXXXXX         XXXXXXXXX
XXXXXXXXXXXX              XXXX
XXXXXXXXXXX   X            XXX
XXXX XXXXXX  X             XXX
XXXXXXXXXXX XX            XXXX
XXXXX XXXX XXXX          XXXXX
XXXX   XXX X              XXXX
XXXX XX XX XXXXX           XXX
XXXXXXX X     XXXX       XXXXX
XXXXX   X       XXX   XXXXXXXX
XXXXX      XXXXXXX  XXXXXXXXXX
XXXXXX      XXX XX  XXXXXXXXXX
XXXXXXX XX       X  XXXXXXXXXX
XXXXXXXXXX   XXX    XXXXXXXXXX
XXXXXXXXXX          XXXXXXXXXX
    XXXXXXX         XXXXXXXXXX
      XXXXX          XXXXXXXXX
       XXXX          XXXXXXXXX
    XXXX XX      XX XXXXXXXXXX
   XXXXX XX       XXXXXXXXXXXX
X XXXXX  XX        XX XXXXXXXX
XXXXXXX  XXX XX     X  XXXXXXX
XXXXXX   XXX XXX      XXXXXXXX
XXXXXX   XXX X   XXXXXXX  XXXX
XXXXX     XXX   X   XXX    XXX
X XXX     XXXX   XXXXX XX    X
XX XXX     XXXX    XX  X      
XX XXX     XXXXX   XX         
XXX XXX     XXXXXXXX  X      X
XXX XXXX     XXXXXX  XX X    X
