 X   X X X   X 
XXX XXXXXXX XXX
 X  XXXXXXX  X 
   XXX X XXX   
   XXXXXXXXX   
   XXXXXXXXX   
    XX   XX    
XXX XXXXXXX XXX
XXX  XXXXX  XXX
XX    XXX    XX
XX    XXX    XX
XX           XX
XXXXX XXX XXXXX
XXXXX X X XXXXX
      XXX      
