XXXXXXXXXXXXXXXXXXXX
X   XXX      XXX   X
X   XXX     XXXX   X
X  XXXXX    XXXXX  X
X  XXXXXXXXXXXXXX  X
X  XX   XXX   XXX  X
X XX     X     XXX X
X XX  XX X XX  XXX X
X XX   X X  X  XXX X
XXXX  XX X XX  XXXXX
XXXX  XX X XX  XXXXX
XXXX     X     XXXXX
XXX X   XXX   XXXXXX
XXX  XXXXXXXXX   XXX
XX X    XXX     X XX
X X X          X X X
X  X XXXXXXXXXX X  X
X   X          X   X
X    XXXXXXXXXX    X
XXXXXXXXXXXXXXXXXXXX
