XX XXX          XXX 
XX XXXX XXXXXX XXXX 
XX  XXXXXXXXXXXXXX  
XX  XXXXXXXXXXXXXX  
X  XXXXXXXXXXXXXXXX 
  XXXX XXXXXXXX XXXX
 XXXX   XXXXXX   XXX
 XXXX  XXXXXXXXX XXX
XXXXX  XX XX X X XXX
XXXXXX   XXXX   XXXX
XXXX  XXXX  XXXX  XX
XX      X  X X      
X       X    X      
X   XXXXXX  XXXXXX  
XX X   X XXXX X   X 
 XXX      X       XX
 X XX XX      XX XX 
  X XX XX XX XX XX X
X XX    XXXXXX    XX
X  XXX X   X  X XXX 
