XX XXXXX   XXXXXXXXXXXX   XXX 
 XX XX   XXXXXXXXXXXXX XX  X X
X XXX  XXXXXXXXXXXXXXX XXX  XX
XXXX  XXXXX  XXXXXXXX XXXXX  X
XXX  XXXXX  XXXX XXXX XXXXXX X
X X XXXX  XXXX   XXXX XXXXXX  
 XX XXXXXXXXX  XXXXXXX XXXXXX 
XX  XXXXXXX   XXXXXXXXX XXXXX 
XX XXXXX    XXX XXXX XXX XXXX 
XX XXXX XXXXXX XX    XXXX  XX 
 X XXXXXXX            XXXX XX 
XX XXXXXXXXXX          XXXXXX 
XX XXXXXX  XXXX  XX     XXXXX 
XX  XXX           XXXXXXXXXXX 
X XXXXX   XXX          XX XXXX
X X  XX  X XXX     X XX   XX X
X XX  X  XXX X     XXXXX  X   
X  X  X XX         X   XX XX X
XX  X X             X     X  X
X X XXXX     X            X XX
XXX  XXX     XX           XXX 
 XXX  XX    XXX          XX   
XX XX XXX   X      X     XXX  
XXXX   XX   XXXXX  X    XXX X 
 X   XXXXX      XXXX   XXXX XX
X  XXX XXX    XX       XXXX XX
  XXX  XXXX    XX     XXXXX XX
XXXXX XXXXXXX        XX XXX  X
XXXXX XXXXXXXX     XXX  XXXX X
XXXX XXXXXXX XXXXXXX   XXXXX X
