  XXXXXXXXXXXXXXXXXXXXXXXXXX  
 XXXXX XXXXXX X XXXXXXXXXXXXX 
XXXXXX  X XX  X  XXXXXXX XXXX 
XXXXXXX  XX   XX XXXXX   XXXX 
XXXXXX  XXX    X  XXXXX X XXX 
XXXXXXXXXX         XXXX  XXXX 
XXXXXXXXX XXXXX      XXXXXXXXX
XXXXXXXXX     XXX     XXXXXXXX
XXXXXXXXX       X    XX  XXXXX
XXXXXXXXX  XXXX    XX     XXXX
XXXXXXXXX X XXXX   X  XX  XXXX
XXXXXXXX   XXX X   X X XX  XXX
XXXXXXX              XXX X XXX
XXXXXXX            X  X    XXX
XXXXXXX            X       XXX
XXXXXXX            XX      XXX
XXXXXX             XX      XX 
 XXXXX  XX   XXX  XXX      XX 
 XXXXX   XXXXX    XX       XX 
X XXXX                X   XX  
X  XXX     XX          X XXX X
XX  XXX     XXXX       XXXX XX
XXX XXX      XX XXX XXX  XX XX
XXXX XXX      XXXXXXXX   X XXX
XXXXX XXX       XXXXX   XX XXX
XXXXXX  XXX            XX  XXX
XXXXXXX  XXXX         XX  XXXX
XXXXXXX  XXXXX      XXX XXXXXX
XXXXXX  XXXXXXXXXXXXXX XXXXXXX
XXXXX  XX  XXXXXXXXXX XXXXXXXX
