XXXXXXXXXXXXXXXXXXXX          
XXXXXXXXXXXXXXXXXXXXXX        
XXXXXXXXXXXXXXXXXXXXXX        
XXXXXXXXXXXXXXXXXXXXXXXX      
XXXXXXXXXXXXXXXXXXXXXXXX      
XXXXXXXXXXXXXXXXXXXXXXXXX     
XXXXX            XXXXXXXX     
XXX                XXXXXXX    
XX                  XXXXXX    
XX                  XXXXXXX   
X                    XXXXXXX  
X                    XXXXXXX  
X                    XXXXXXXX 
X      XXXXXXXX      XXXXXXXX 
X     XXXXXXXXXX     XXXXXXXXX
X    XX  XX    XX    XXXXXXXXX
X    X  XXXX    X    XXXXXXXXX
X   XXXXXXXXXXXXXX   XXXXXXXXX
X  XXXXXXXXXXXXXXXX  XXXXXXXXX
X  X   XXXXXXXX   X XXXXXXXXXX
XX XXXXXXXXXXXXXXXX  XXX      
   XXXXXX    XXXXXX   XXX     
    XXXXXXXXXXXXXX     XXX    
     XXX      XXX       XXX   
     XXX      XXX        XXX  
