     XX  XXX         XXXXX    
   XXXXXXX X        XX   XX   
  XXXXXXXXXX        XXXXX X   
 X XXX XXXX         XXX XXXX  
 XXXXXXXXXXX       XXX   XXX  
 XXXXXXXXXXXXX     XXXXX   X  
 XXXXXXXXXX  XX     XXXXXXX   
 X XXXXXXXXX   XX   XXXXXXX X 
  XXXXXXXXXXXX  XX    XXXXX  X
       XXXXXXXX  XX     XXXX X
       XXXXXXXXX  X     XXXX X
       XXXXXXXXXX  XX    XXX X
   XX  XXXXXXXXXXX XXX   XXX X
  XXXX XXXXXXXXXXX  XX   XXX X
  XX XXXXXXXXXXXXXX XXX  XXX X
     XXXXXXXXXXXXXXX XX  XXX X
      XXXX    XXXXXX XX  XXX X
        XX XX  XXXXXX X  XXXXX
        XX XXX  XXXXXXX XXXXX 
         X XXXX XXXXXXX XXXXX 
           XXXXXXXXXXXXXXXXXX 
          XXXXXXXXXXXXXXXXXX  
          XXXXXXXXXXXXXXXXX   
X XXX     XXXXXXXXXX XXXX     
 X   X  XXXXXXXXXXX      XXXXX
X    XX  XXXXXXXXX    XXXX   X
X   XXXX             XX     XX
X  XXXXX             X    XXX 
 XXXXXXX            XX  XXX   
  XXXXXX            X         
