                  XXX         
                 XX XXX       
   X  X         XX   XX       
   X  X  X  XXXXX             
X XXXXXXXX XXXXXXX            
XXXXXXXXX XXXXXXXXX   XXXX    
 XX XX XXXXXXXXXXXX   XXXXX   
 XXXXXXXXXXXXXXXXXX   XXXXXX  
  XXXXXXXXXXXXXXXXX  XXXXXXX  
 X     XXXXXXXXXXXX   XXXXXX  
 X X X XXXXXXXXXXXX   XXXXXXX 
 X     XXXXXXXXXXXX    XXXXXXX
 XXXXXXXXXXXXX  XXXXXXXXXXXXXX
  XXXXXXXXXXX  XXXXXXXXXXXXXXX
  XXXXXXXXXXXXX XXX    XXXXXXX
  XXXXXXXXX XX  XX     XXXXXXX
  XXXXXXXX XXX  XX     XXXXXXX
  XXXXXXXX XX  XXX XXXXXXXXXXX
  XXX  XXX     XX  XXXXXXXXXXX
  XX   XX  XXXX    XXXXXXXXXX 
  XX   XX  XXXX    XXXXXX  X  
  XX   XX  XXXX    XXXX XXXX  
  XX   XX  XXXX   XXXX  X  X  
 XXX  XXX   XX    XXXX  X  X  
 XX   XX                      
