  XXXX    X         
 XXXXXX   XX        
XXX  XXX  XXX       
XXX   XX  XXX       
XX    XX  XXXX      
 X    XX   XXX      
 X    XX   XXX      
      XX  XXXXX     
     XXX  XXXXX     
    XXX  XXXXXX    X
   XXX XXXXXXXX    X
  XXXXXXXXXXXXX   XX
 XXXXXXXXXXXXXX XXXX
 XXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXX 
 XXXXXXXXXXXXXXXXX  
 XXXXXXXXXXXXXXXXX  
 XXXXXXXXXXXXXXXX   
  XXXXXXXXXXXXXX    
   XXXXXXXXXXXX     
