XXXXXXXXXXXXXX XXXXXXXXXXX XXX
XXXXXXXX X XXXXXXXXX XXXXXXXXX
XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
XXXXX XXX XXXXXXXXXXXXXX XXXXX
XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXX XXXX XXXXXXXXX XX
 XX XXX XXXXXXXXXXXXXXXXXXXXXX
  X  X XXXXXXXXXXXXXXXXXXXXXXX
X XX   XXXXX          XXXXXXXX
X     XXXXX         X  XXXXXXX
XX    XXXX         XXX  XXXXX 
XXX   XXX         XXXXX  XXXXX
XXXX  XX         XXXXXXX  XXXX
XXXX  X         XXXXXXXXX  XXX
XXXX           XXXXXXXXXXX  XX
XXXX X        XXXXXXXXXXXXX  X
XXXXXX       XXXXX  X  XXXXX  
XXX XX      XXXXXX  X  XXXXXX 
XX  XX     XXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX  X  XXXXXX 
 XXXXXXXXXXXXXXXXX  X  XXXXXX 
   XXXXXXXXXXXXXXXXXXXXXX  XX 
    XX XXX     XXXXXXXX       
    XX          XXXX          
    XX                        
