    X     X    
  XXX X X XXX  
 XXX XX XX XXX 
XXX  XX XX  XXX
XXX XXX XXX XXX
XX XXX   XXX XX
 X XX     XX X 
  X   X X   X  
   XXXXXXXXX   
  XXXXXXXXXXX  
 X XXXXXXXXX X 
  XXXXXXXXXXX  
 X XXXXXXXXX X 
    X XXX X    
   X       X   
