        XXX         
       XXX XXX      
      XXX XXX XXX   
     XXX XXX XXXX   
    XXX XXX XXXXX   
   XXX XXX XXXXXX   
  XXX XXX XXXXXXX   
 XXX XXX XXXXXXXX   
XXX XXX XXXXXXXXX   
XX XXX XXXXXXXXXX   
XX XX XXXXXXXXXXX   
XX XX XXXXXXXXXXX   
 XX XX XXXXXXXXXX   
  XXXXXXXXXXXXXXX   
          X  X  X   
XXXXXXXXXXXXXXXXXXXX
   XXXXXXXXXXXXXXX  
    XXXXXXXXXXXXX   
      XXXXXXXXXX    
       XXXXXXXX     
