     XXXXXXXXXXXXXXXX    
    XXXXXXXXXXXXXXXXXX   
   XXXXXXXXXXXXXXXXXXXX  
  XX        XX        XX 
 XX  XXXXXX    XXXXXX  XX
 X    XXXXX XX XXXXX    X
XXXXXX XXXX XX XXXX XXXX 
XXXXXXX    XXXX    XXXXXX
XXXXXXXXXXX  XXXXXXXXXXXX
XXXXXXXXXX    XXXXXXXXXXX
XXXXXXXX       XXXXXXXXXX
XXXXXX           XXXXXXXX
XXXXX              XXXXXX
XXXX XXXXXX     XXXXXXXXX
XXXX   XXX       XXX XXXX
XXXX                 XXXX
XXXX                  XXX
XXXX                  XXX
XXXX        XXX       XXX
XXXX                  XXX
XXXXX                 XXX
 XXXX     XXXXXXX    XXXX
  XXXX     XXXXXX    XXXX
   XXXX     XXXX    XXXXX
    XXXX           XXXXXX
  XXXXXXXX        XXXXXXX
   XXXXX XXXXXXXXXXXXXXX 
      XX            XXX  
     XXX              XX 
    XXXX             XXXX
