  XXXXXX                 
  XXXXXX                 
  XXXXXX                 
   X  X                  
   X  X                  
   X  X       XXXXXX     
   X  X      XXXXXXXX    
   X  X     XXXXXXXXX    
   X  X     XXXXXX X     
  XXXXXX    XXXXXXXXX    
 XXXXXXXX    XXXXXXX     
XXXXXXXXXX    XXXXX      
X      XXX    XXXXXXX    
XX    XXXX   XXXX  XXX   
XXX  XXXXX  XXXXXX  XX   
XXXXXXXXXX XXXXXXXX XX   
XXXXXXXXXX XXXXXXXXXXX   
XXXXXXXXXXXXXXXXXXXXXX   
X       XXXXXXXXXXXXXX   
X       XXXXXXXXX XXXX   
X       XXXXXXXXX   XXX  
X       XXXXXXXXX  XXXXX 
X       XXXXXXXXX XXXXXX 
X       XXXXXXXX XXXXXXX 
X       XXXXXXXXXXXXXXXX 
X       XXXXXXXXXXXXXXXX 
XXXXXXXXXXXXXXXXXXXX XXX 
XXXXXXXXXXXXXXXXXXX  XX  
XXXXXXXXXX XXXXXXX   XXX 
 XXXXXXXX   XXXXX    XXXX
