   XXX                        
  XXX X                       
  XXXXXX              XXX     
  XXXXX      X        XXX     
   XXX      XX         X      
X XXXXXXXXXXX          X      
X XXXXX   XXXX         X      
X XXXXX  XX  XX        X      
X XXXXX       XXXXXXXXXXXXX   
X XXXXX        XXXXXXXXXXXXX  
X  XXXXXXXXX   XXXXXXXXXXXXXX 
XXXXXXXXXXXX   XXXXXXXXXXXXXX 
XXXXXXXX  XX   XXXXXXXXXXXXXX 
XXXXXXXX  XX   XXXXXXXXXXXXXX 
  XXXXXX  XXXX XXXXXXXXXXXXXX 
 XXXXXXXXXXXXX XXXXXXXXXXXXXX 
XXXXXXXXXXXXXXXXXXXXXXXX    X 
XXXX   XXXXXXXXXXXXXXXX XXXX  
XXX XXX XXX  XXXXXXXXX XXXXXX 
XXX XXX XXX    XXXXXXXXXX  XXX
XXX XXX XXX           XX XX XX
XXXX   XXXX           XX XX XX
XXXXXXXXXXX           XXX  XXX
 XXXXXXXXX             XXXXXX 
  XXXXXXX               XXXX  
