  X        X   
 XX XX  XX  X  
 X          X  
 X   X  X   X  
 X          X  
 XXXXX  XXXXXX 
XXXXXX  XXXXXXX
XXXXXX  XXXXXXX
XXXXXX  XXXXXXX
XXXXXX  XXXXXXX
XXXXXX  XXXXXXX
XXXXX    XXXXXX
XXXX  XX  XXXXX
XXXXXX  XXXXXXX
 XXXXXXXXXXXX  
