  XXX     XXX  
  XXXXXXXXXXX  
  XXXXXXXXXXX  
   XXX X XXX   
   XXXXXXXXX   
  XX XXXXX XX  
  XXX XXX XXX  
XXX  XX XX  XXX
XXXXXXXXXXXXXXX
  XXXXXXXXXXX  
   XXXXXXXXX   
  XXXXXXXXXXX X
  XXXXXXXXXXX X
       X      X
       XXXXXXXX
