XXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXXX  XXXX
XXX XXXXXXXXXXX  XXX
XXXXXXXXXXXXXXX  XXX
 XXXX XXXXXXXXX  XXX
XXXXXXXXXX XXX  XXXX
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX
XXXXX XXX         XX
XXXXX XXX XXXXXXX   
X X X     X  X  X XX
XXXXX XXX XXXXXXX XX
X X X X X X  X  X X 
XXXXX XXX XXXXXXX XX
X X X X X X  X  X X 
XXXXX XXX XXXXXXX XX
X X X X X X  X  X X 
XXXXX XXX XXXXXXX XX
XXXXX XXX XXXXXXX XX
