XXXXXX  XXXXXXXXX  XXXXXX
X     XXXXXXXXXXXXX     X
X   XXXXXXXXXXXXXXXXX   X
X XXXXX           XXXXX X
X XXXXX       X   XXXXX X
X XXXXXX     X   X XXXX X
 XXXXXXXX    X    X XXXX 
 XXX XXXXX   XXX  X  XXX 
XXXX  XXXXX    X XXX XXXX
XXX    XXXXX   XX  XX XXX
XXX     XXXXX   XXX X XXX
XXX      XXXXX     XX XXX
XXX       XXXXX       XXX
XXX  XXXXXXXXXXXXXX X XXX
XXX  XXXXXXXXXXXXXX X XXX
XXX          XXXXX    XXX
XXXX          XXXXX  XXXX
 XXX           XXXXX XXX 
 XXXX           XXXXXXXX 
X XXXX           XXXXXX X
X XXXXX           XXXXX X
X  XXXXXX       XXXXXX  X
X   XXXXXXXXXXXXXXXXX   X
X     XXXXXXXXXXXXX     X
XXXXXX  XXXXXXXXX  XXXXXX
