     XXX  XXXXXXXXXXXXXXX
XX   XXXX XXXXXXXXXXXXXXX
XXX XX      XXXXXXXXXXXXX
X  X X    X XXXXXXXXXXXXX
X X  XX   X XXXXX      XX
XX   X X  X XXXX  XXXX  X
X  XXXX X X   X  XXXXXX  
XXXXXXXXXXXXX X XX  XXXX 
XX X X X XXX  X X    XXX 
XXXXXXXXXXX  XX X  X   X 
XXXXXXXXXX  XXX X     XX 
                XX   XXX 
XX  XX  XX  XX   XXX XXX 
  XX  XX  XX  XXXXX  XXX 
               XXXX  XXX 
 XX  XX XXXX  XX XX XX X 
X  XX  XXXXXXXX  XX XX X 
      XXX XXXXXXXX  XX X 
      XX   XXXXXXX  XX X 
    XXX     XXXXXXX XX X 
   XXXX  XXX XXXXXXXXX X 
  XXXXX XXXXX XXXXXXXX X 
 XXX XX XXXXXX XXXXXXX X 
XX   XX XXXXXXX XXXXX  X 
      X XXXXXXXX  X   X  
