XXXXXXXXXXXXXXXXXXXXXXXXX
X X X XX X XXX   X XXX  X
XX X XX  X X X   X X X  X
X X X X  X XXX X X XXX  X
XX X X            XX    X
X X XXXXXX       X XX X X
XX X     XX   XXXXXX X XX
X XX      X  XXXXXXXX  XX
XX  X X   X  XXXXXXXXXX X
X XX X XXXX  XXXXXXXXX  X
XXX      XXX X X X XXX  X
X X X  X X X X     XXX  X
X X      X X X X X XXX  X
X  X    XX X X     XXX XX
X   XXXX X XXX     XXXX X
X  X    X  XX XXXXX XX XX
X X      XX  X    XXX X X
XX X X X XX X    X X X XX
XXX X X X X X   X X X X X
XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX   X XX XX   X    X
X    X X X XX X XX XXXXXX
XXXX X   XXXX XXX XX    X
XXX XXXXXXXX XXX XXXXXX X
XX XXXXXXXX XXX XXXXXX XX
