            XXXX              
         XX  XXXXXX           
      XXX XXXXXXXXXXX         
    XXXXXX XXXXXXXXXXXX       
  XXXXXXXX XXXXXXXXXXXXX      
     XXX  XXXXXXXXXXXXXXX     
   XXX  XXXXXXXXXXXXXXXXXX    
  XX  XXXXXXXXXXXXXXXXXXXXX   
 XX XXXXXXXXXXXXXXXXXXXXXXXX  
XXXX  XXXXXXXXXXXXXXXXXXXX  XX
XXXXXX  XXXXXXXXXXXXXXXXXX XXX
 XXXXXXX XXXXXXXXXXXXXXXXX XXX
  XXXXXX XXXXXXXXX XXXXXXX  XX
   XXXX XXX XXXXX   XXXXXXXX  
    XXX XX   XXXX    XXXXXXX  
  XXXX XX    XXX      XXXXX   
   XXX X  XX  XX    XX XXXX   
     XX   X   X     X   XXX   
XXXXX X   X         X    X XXX
XXXX      XX        XX      XX
XXXX  X   XX        XX   X  XX
XXXXX X        X         X XXX
XXX X          X           XXX
XXX XXX                  XXXXX
XX   XX       XXXX      XXXXXX
XX   XXX      XXXX      XXXXXX
X     XXX      XX      XXXXXXX
X     XXXXX          XXXXXXXXX
XX   XXXXXXXX      XXXXXXXXXXX
XXXXXXXXXXXXXXX  XXXXXXXXXXXXX
