 XXXX XX XXXXXX
     XXXX     X
 XXXXXXXXXXXXXX
     XXXX     X
 X X X XXX X XX
 X   X XXX   XX
 XXXXX XXXXXXXX
 XXXXX   XXXXXX
X XXXXXXXXXXXX 
X XXXXXXX XXXX 
XX XXX   XXXXX 
XXX XXXXXXXXX X
XXXX   XXX  X X
X   XXX   XXXX 
 X XXXXXXX XXXX
