        XX     
       XX      
  XXX  X  XXX  
 XXXXXXXXXXXXX 
XXXXXXXXXXXXXXX
XXXXXXXXXXXX  X
XXXXXXXXXXXX  X
XXXXXXXXXXXX  X
XXXXXXXXXXXXXXX
XXXXXXXXXXXXXXX
 XXXXXXXXXX  X 
 XXXXXXXXX  XX 
  XXXXXXX  XX  
   XXXXXXXXX   
    XXXXXXX    
