       XX XX          XX      
       XXXXXXXXXXXXXXXXXX     
     XXXXXXXXXXXXXXXXXXXX     
   XXXXXXXXXXXXXXXXXXXXXXX    
  XXXXXXXXXXXXXXXXXXXXXXXXXX  
  XXXXXXXXXXXXXXXXXXXXXXXXXXX 
  XXXXXXXXXXXXXXXXXXXXXXXXXXX 
  XXXXXXXXXXXXXXXXXXXXXXXXXXX 
  XXXXXXXXX XXX XXXX  XXXXXX  
  XXXXXXXXX  XX       X  XXX  
 XXXXXXXXX  XXX      XX XXXX  
XXXXXXX    XX         XX XXXX 
XXXXXXXX  XX          XX  XXX 
 XXXXXXX XX          X X XXXX 
  XXXXXX X X XX    XXXXXXXX   
   XXXX   XXXXXX  XXXXXX XX   
    XXX X XXXXXX  XXXXXXXXX   
    XXXXX XXXXXX  XXXX XXXXX  
   XXXXXX XXX XX  XXX  X XXX  
   XXXXXX XX  XX   XX XXXXX   
    XXXX   XXXX    XXXXX  X   
    XXXX   X XX  XX  X X XX   
    XXXX         X       XX   
    XXXX        XXX      XX   
     XXXXXXXXXXXXXXXXXXXXX    
      XXXXXXX   XXX XXXX      
       XXX            X       
     XXXXX            X       
    XXXXXXX       X   X       
     XXX  X       X   X       
