    XXX       XXX   
   XXXXX     XXXXX  
  XXXXXXXXXXXXXXXXX 
 XXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXX XXXXXX
XXXXX   XXXX    XXXX
XXXX            XXXX
XXXX XXXX  XXXX XXXX
XXXX  X     X   XXXX
XXXX            XXXX
XXXXX           XXXX
    X  X    X  XX   
     X  XXXX  X     
     XX       X     
   XXXXX    XXXXXX  
  XX  XXXXXXXXX  XX 
 XX  XXXXXXXXXXX  XX
X   XXXXXXXXXXXXX   
