 XXX                     
  XXX          X         
  XXXX      XXXXX        
   XXXX  XXXXXXXXXX      
   XXXXXXXXXXXXXXXXX     
    XXXXXXXXXXXXXXX    XX
     XXXXXXXXXXXXXX   XXX
      XXXXXXXXXXXXX  XXX 
     XXXXXXXXXXXXXXXXX   
    XX  XXXXXXXXXXX XXXX 
X   X   X XXXXXXXXX  XXX 
X   X   XX XXXXXXXXX   XX
XX  X      X XXXXXXXX    
 XXXX      XXXXXXXXXXX   
   XXXXX       XXXXXXXX  
    X          X XXXXXXX 
    XX       XX    XXXXXX
     XXX    XX        XXX
 XXXXX XXXXXX        X   
XX          XXXXXX    XXX
X  XXXXXXX XXXXXXXX    XX
   XXXXXXXXXXXXXXXXX XXXX
  XXXXXXXXXXXXXXXXXXXXX  
XXXXXX  XXXXXX   XXXXX XX
XXXXX    XXXX     XXXX   
