X  X      XXXXX          
X  X X  XXXXXXXXX  X     
X  X X XX XXXXX XX X     
XXXX XXX X XXX X XXX     
 XX  X X X XXX X X X     
 XX  X XX XX XX XX X     
 XXX  XXXXX   XXXXX      
 XXXXXXXXXXXXXXXXXXXXX   
 XXXXXXXXXX   XXXXXXXXX  
  XXXX             XXXXX 
   XXXX   XX  XX  XXXXXX 
     XXX  XX  XX XXX XXX 
     XXXX       XXXX  XX 
     X XXX     XXXXX  XX 
     X XXXX   XXXXXX XXXX
     X XXXXX XXXXXXX X  X
     X XXXXXXXXXXXXX X  X
     XX XXXXXXXXXXXX    X
   XXXXXXXXXXXXXXXXXXX   
   X                 X   
   XXXXXXXXXXXXXXXXXXX   
    XXX   XXXXX   XXX    
    XXX    XXX    XXX    
     X     XXX     X     
XXXXXXXXXXX X XXXXXXXXXXX
