      XXXXXXXX      
    XXXXXXXXXXXX    
   XXXXXXXXXXXXXX   
   XXXXXXXXXXXXXXX  
  XXXXXXXXXXXXXXXX  
  XXXXXXXXXXXXXXXXX 
  XXXXXXXXXX XXXXXX 
 XXXXXXXXXXX XXXXXX 
 XXXXXXXXXXX XXXXXX 
 XXXX            X  
 XXXX            X  
 XX X XXX   XXX  X  
 X     XX    XX  X  
 X   XX          XX 
 XX XXX           X 
XXX XX        X   XX
XXXX  XXXXXXXXX   XX
XXXXX            XXX
XXX XX          XXXX
XXX  XXXXXXXXXXXX XX
