  XXXXXXX       XX XX    
 XXXXXXXXX     X XXXXX   
XXXXXXXXXXX    XXXXXXXX  
XXX  XXXXXXX  XXXXXXXXXX 
XX XXXXXXXXX  XXXX  XXXX 
XXXXXXXXXXXX XXXX XXX XXX
XXX   XXXXXXXXXX X XX XXX
XX  XX XXXXXXXX   XX   XX
X XXXXX XXXXXXXX       X 
XXXX XXX XXXXXXXXX  X XX 
XXXX  XX XXX XXXXXXXXXX  
XXX  XXXXXX XXXXXX   XXX 
XXX XXXXXX XXXXX  XX X XX
XX  XXXXX XXXXX    XXXXXX
   XXXXX  XXXX  XX    XXX
   XXXXX XXXX    XXXXXXX 
   XX XX XXXX       XX   
   XX  X XXX     XX  XX  
   XXX   XXX      XX  XX 
   XXX XXX X       X   X 
    XXX XX X      XX   X 
    XXXX         XX   XX 
     XXXXX     XXXXX XX  
      XXXXX        X   XX
        XXXXXXXXXXXXXXXXX
