   X XXXXX XXXXXXXXXXXXXXXXX  
  XX XXXXX  XXXXXXXXXXXX XXXX 
 X  XX XX    XXXXXXXXXXX  XXX 
 XX X  X      XXXXXX   X   XX 
 XXXX XX        XXXXX   X XXXX
 XXX  XX           XXX   XXXXX
 XXXXXXXXXX        XXXXXXXXXXX
 XXXXXX   XX     XXXXXXXXXXXXX
 XXXXXX    XX   XX    XXXXXXXX
 XXXXX                 XXXXXXX
 XX XXXXXXXX       XXXXX XXXXX
 X  XXX XX XX     XXXX XXX  XX
 X XXX  XXXXX     X XXX XXX XX
 X XX   XXX X       XXXXXXX XX
 X  X  XXXXXX      XXXXX X  XX
 XX X         X          X  XX
  X X         X          X XX 
  XXXX        X         X XXX 
   XXX                  XXXXX 
   XXXX     XX XXXX    XXXXXX 
   XXXXX    XXXX X    XX XXXX 
   XXX XX    XXXXX   XXX XXXX 
  XX X XXX          XXXX XXXX 
  XX X XXXX        XXXXX XXXXX
  X   XXXXXX     XXXXXXX  XXXX
 XX XXXXXXXXXXXXXXX XXXXX XXXX
 XX XXXXXXX  XXXXX  XXXXX XXXX
XXXXXXXXX X         X  XX  XXX
X XXXXXX  X         XX  XX XXX
XXXXXX   XX          XX   XXXX
