  XXXXXXXX                    
 XX      XX  XXX              
XX  XXXX  XX X X XX           
X  XXXXXX  X XXX XX X         
X  XXXXXX  X                  
X XXXXXXXX X     XXXXXXXXXXX  
X X      X X    XXXXXXXXXXXXX 
X X      X X   XXXXXXXXXXXXXXX
X  XXXXXX  X  XXXXXXXXX   XXXX
 X        X  XXXXXXXXX XXX   X
  XXXXXXXX   XXXXXXXX XXXXXXX 
            XX    XX XXXXXXXXX
           XXX X X X XXXXXXXXX
          XXXX   XXX XXXXXXXXX
         XXXXXXXXXXX XXXXXXXXX
       XXXXXXXXXXXX XXXXXXX  X
     XXXXXXXXXXXXXX XXXXXX    
 XXXX XXXXXXXXXXXXX XXXXXX    
XXXXX XX XX XXXXXX XXXXXXXX  X
XXXX XXXX XXXXXXXX XXXXXXXXXXX
XXX XXXXXXXX XXXXX XXXXXXXXXXX
 X XXX X XX XXXXXX XXXXXXXXXXX
 XXXXXXXXXXXXXXXX XXX  XXXXXXX
 XXX XX XX XXXXXX XX    XXXXXX
  XXXXXXXXX    XX XX    XXXXXX
  XXXXXX    XXXXX XXX  XXXXXXX
   X     XXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXX  XXXXXXXXX
     XXXXXXXXXXXXXXXX         
                  XXXXXXXXXXXX
