XXXX XX XXXXXXXXXXXXXXXXXXXXXX
XXX  XX  XXXXXXXXXXXXXXXXXXXXX
XXX XXXX XXXXXXXXXXXXXXXXXXXXX
XX  XXXX  XXXXXXXXX        XXX
XX XXXXXX XXXXXXX   XXXXXX    
X  X    X  XXXX   XXXXXXXXXXX 
X XX    XX XX   XXXXXXXXXXXXXX
  X      X  X XXX XXXXXXXXXXXX
 XX      XX X X       XXXXX XX
 X        X   XXX      XXXX XX
XX        XX   XXXXXX   XXX XX
XX X X X XXX  XXX   XX   XX XX
XXXXXXXXXXXX    X X  XX   X  X
XX   XXX   X    X X   XX   X X
XX   XXX   X   X  X   XXX XX  
XX   XXX   X   X      X XXX   
XX   XXX   X   X      X  XX   
XX   XXX   X   X         XXX  
XX   XXX   X    X      XXXXXXX
XX   XXX XXXX    XXXXXXXXXX   
XX   XXX X  XX    X       XX  
XX   XXX XX  XXXXXX        XX 
XX   XXX  XX X   X          X 
XX  XXXX   X X   X  X     X X 
XX  X  XX  XXXXXXX  X     X XX
XX XXX  XX X    X   X     X  X
XX X XX  X X XXXX   X     X  X
XX X  X  XXXXX    XXXXXX XX  X
XX X  X   XXXXX   X    XXX   X
XX X  X   XXXXXXX XX     X   X
