   XXXXXXXX    
 XXXXXXXXXXX   
 X X XX  X XX  
XXX X  X  XXX  
XXX X  X  XXXX 
XX  XXXX   XXX 
XX X X  X  XXX 
XX XX XXX XXXX 
XXX      XXXX  
 XXXXXXXXXXXX  
  XXXXXXXXXX X 
 XX    X X    X
XX   XXX XXX  X
X   X    X    X
XXXXXXXXXXXXXXX
