XXXX   X XXXXXXXXXXXXXXXXXXXXX
XXX      XXXXXXXXXXXXXXXXXXXXX
XX         XXXXXXXXX    XXXXXX
XX   XX    XXXXXXX  XXXX  XXXX
XX    XX  XXXXXXX XXXXXXXX XXX
X XX X XX XXXXXXX XXX   XXX XX
XX     XXX XXXXX XXX  XXX X XX
XX    XXXX XXXXX XX  XXX  XX X
XX    XXXXX XXXX XX XXXX XXX X
XXXX XXXXXX XXXX XXXXXXXXX X X
XXXX XXXXXXX XXX X XX XXX XXXX
XXX XXXXXXXX XXX X X   X XXXXX
XXX XXXXXXXX XXX X  XXX  X XXX
XX XXXXXXXXXX XX  XXXXXXX XXXX
XX XX XXXXXXX  X X   XXXXX XXX
XX XX XXXXXXX X XXXX  XX X XXX
XX XX XXXXXXX XX X XX XXX X XX
XX XX XXXXXXX XX XX XX XXX  XX
XXX XX XXXXXX XX XXX X X XX XX
XXX XX XXXXXX XXX XXX  X XX XX
XXXX XX XXXXX XXX X XX XX X XX
XXXXX XX XXX XXXX X  X XX XXXX
XXXXX XXX XX XXXX X  XXX X XXX
XXXXXX XX XX XXXX X X XX X XXX
XXXXXXX XX  X X X X X XX XXXXX
XXXXXXX   XXX X X X XX X XXXXX
XXXXXXX X XXX X X XXXX XXXXXXX
XXXXXX XX XXXXX XXXXXXXXXXXXXX
XXXX  XXX  XXXXXXXXXXXXXXXXXXX
XXXXXXX   XXXXXXXXXXXXXXXXXXXX
