  X  XXX    XXX  X  
 XXX  XXX  XXX  XXX 
XXXXX   XXXX   XXXXX
XXXXXX XXXXXX XXXXXX
XXXXXXXX XX XXXXXXXX
XXXXXXX X  X XXXXXXX
XXXXXXXX XX XXXXXXXX
XXXXXX XXXXXX XXXXXX
X XXXX  X  X  XXXX X
X XXXXX      XXXXX X
  X XXXXX  XXXXX X  
    X XXXXXXXX X    
 XXX   XXXXXX   XXX 
  XXX XX XX XX XXX  
   XXXX  XX  XXXX XX
    XX   XX   XX  XX
     X   XX   X XXX 
         XXX    XXX 
          XXXXXXX   
           XXXXX    
