  XXXXXXXXXXXXXXXX  
 XXXXXXXXXXXXXXXXXX 
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
XXXXXX     XXXXXXXXX
XXXXX       XXXXXXXX
XXXX         XXXXXXX
XXXX XX  XX  XXXXXXX
XXXX XX  XX XXXXXXXX
XXXX        XXXXXXXX
XXX         XXXXXXXX
 XX  XXX     XXXXXXX
 XX  XXX      XXXXXX
  X   X      XXXXXX 
  X X X  X   X XXX  
  XX XXXX   XX   XXX
   XX    XXXXXXXXX X
    XXXXXX       XXX
     XX            X
    XX              
