XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXXXXXXXXXXXXXXX  XXX X XXXXXXXXXX
XXXXXXXXXX X   X XXXX X  XXXXXXXXXX
XXXXXXXX X X XXXXX X X X  X  XXXXXX
XXXXXXXXXXX XX  XXXXXX XXXXXX XXXXX
XXXXXXXXX XXX XXX  X  XXXXX  XXXXXX
XXXXXXXX XX  X      XX X    XX  XXX
XXXXXXXXX   X XXXX    XX XX X  XXXX
XXXXXXXXX XXXX  XX XXX X  XXXXXX  X
XXXXXXXXX XXXXXXX X    XX   X   XXX
XXXXXXXXX XXXXX  XXXXXX XXXX  X  XX
XXXXXXXXX XX  X X  XX       XXXXXXX
XXXXXXXXX X   XXX  XX XXXX XXXX X X
X  XXXXX  X X  XXX XXXX  X  X X  XX
X   XXX  XX    XX  XX XXXX  XXX XXX
X       XXXX  XXX X X XXXXX XXX XXX
XXX XXXXXXXXXXXXX     X X XXX X  XX
XXX XXXXXXXXXXXXXXXX   XXXX   XXX X
XXXX XXXXXXXXXXXXXXX X  XXXXXXX XXX
XXXX  XXXXXXX XXXXXX  X  XX XX  X X
XXXXX  XXXXXX XXXXXX XXX XX XXXX XX
XXXXXX   XXX  XXXXXX X X   X  X XXX
XXXXXXX      XXXXXX     XXXXXX  XXX
XXXXXXXX  XXXXXX X X XX   XX X X XX
XXXXXXXXX   XXXX XXX    XXX X  XXXX
XXXXXXXXXXX   XXX   X  X XXX  XXXXX
XXXXXXXXXXXXX    XXXXX   X  XX XXXX
XXXXXXXXXXXXXXXX            XXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
