XXXX           XXXX   XXX
XXX  XXXX XXXXXXX XX  XXX
XXX XX  XXXXXXXX   XX XXX
XXX X  XXXXXXXXXX  XX XXX
XXX XX  XX XX XX  XXX  XX
XXX  XXXXXXXXXXXXXXX   XX
XX    XXX XXX XXXX     XX
XX    XX   X   XXXX    XX
XX    XX  XXX  XXXXX    X
X    X XX     XXXXX X   X
X    X XXXXXXXXXXX XX   X
X   XX  XXXXXXXX   XXX  X
X  XXX   X  X     XXXX  X
X XXXXX  X  X    XXXXXX X
  XXXXX XXXXXX  XXXXXXX X
  XXXXXXXXXXXXXXX XXXXX X
 XX  XXXXXXXXXXXXX XXXX  
 X   X XXXXXXXXXXX X  XX 
 XX XX XXXXXXXX  XX    X 
  XXX XXXXXXX  XX XX  XX 
   XXXXXX  X XXXXXXXXXX  
    XX  XXX XXX  XXXX    
   XX   XXX XX   XXXX    
   XX    XXXX     XX     
   XX    XXXX     X      
