                       XXXX   
     X      X         XXXXXX  
    XXX    XXX       XXXXXXXX 
   XXXXX  XXXXX        XXXXXX 
   XXXXX  XXXXX         XXXXXX
 XXXXXXXXXXXXXXXX        XXXXX
XXXXXXXXXXXXXXXXXX        XXXX
XX XXXXXXXXXXX XXXX       XXXX
XX    XXXXX    XXXX        XXX
XXX  X XXX X  XXXXX        XXX
XXXX    X    XXXXXX       XXXX
XXXXXXXXXXXXXXXXXXX       XXXX
XXXXXXX   XXXXXXXXX      XXXX 
XXXX XX   XX XXXXX      XXXX  
XXXX  XX XX  XXXX XXXXXXXXXXX 
 XXXX XX XX XXXX XXXXXXXXXXXX 
    XX  X  XXX  XXXXXXXXXXXXX 
  X  XXXXXXX   XXXXXXXXXXXXXX 
  XX        XXXXXXXXXXXXXXXXX 
  XXXXX  XXXXXXXXXXXXXXXXXXXX 
  XXXX   XXXXXXXXXXXXXXXXXXXX 
 XXXX  X  XXXXXXXXXXXXXXXXXXX 
 XXXXX X XXXXXXXXXXXXXXXXXXX  
 XXXXXXXXXXXXXXXXXXXXXXXXXXX  
 XXX    XXXXXXXXXXXXXXXXXXXX  
 XX     XXXXXXXXXXXXXXX   XX  
XXX    XXXX         XXX   XX  
XX     XXXX        XXX    XXX 
XX    XXXX         XXX     XX 
X    XXXX         XXX      XXX
