      XXXXXX         XXXXXX   
     XXXXX XXXXXXXXXXX XXXXX  
     XXXX XXXXXXXXXXXXX XXXX  
     XXX XXXXXXXXXXXXXXX XXX  
     XXX XXXXXXXXXXXXXXX XXX  
      X XXXXXXXXXXXXXXXXX XX  
       XXXXXXXXXXXXXXXXXX X   
       XXXXX  XXXXX  XXXXX    
       XXXX XXXXXX XXXXXXX    
       XXXX X XXXX X XXXXX    
       XXXXXXX    XXXXXXXX    
        XXXX  XXX   XXXXXX    
        XXX   XXX    XXXX     
 XX      XX X  X   X XXX      
X  X      X  XX XXX  XX       
X  XXX  XXXX        XX XX     
X  XXXXXXXX XXXXXXXXX XXXXX   
XXXXXXXXXX XX  X  XXX XXXXXX  
 XXXXXXXXX X XX XX XX XXXXXXX 
  XXXXXXX XXX  X  XXXX  XXXXXX
     XXXXXXXX XXX XXXXXX  XXXX
         XXX XXXXX XXXXXXX  XX
     XXXXXXXXXXXXXXXX  XXX   X
 XXXXXXXXXXXXXXXXXXX XXXXXX  X
X  XXXXXX XXXXXXXXX XX    XXXX
X   XXXXX XXXXXXXXX X      X  
X   XXXXXX XXXXXXXX X      X  
X   XXXXXXXXXXXXXXXXX      X  
 X  XXX             XX    X   
  XXX               XXXXXX    
