            XXXXXXXXX       X 
  X       XXXXXXXXXXXXXX    X 
 XX     XXXXXXXXXXXXXXXX    XX
XX     XXXXXXXXXXXXXXXXXXX  XX
XXX   XXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXX   XXXXXXXX XXXXX
XXXXXXXXXXXX     XXXXXX  XXXXX
XXXXXXXXXXXX      XXXXX  XXXXX
XXXXXXXXXXX  XXXX  XXXX XXXXXX
XXXXXXXXXXX XX  X   XX    XXX 
XXXXXXXXXX               XXXX 
XXXXXXXXXX  X XX       XXXXXX 
 XXXXXXXXX  XXXXX     XXX XX  
 XX XXXXX    XX X     X X XX  
  XX X  X    XXXX     XXX X   
   XXX X     X XX     X X XX  
    XX X     X  X      XX  X  
     XX       XXX   XX     X  
     XX              X     X  
      XXX                 XX  
        XX         XX    XX   
         XXX            XX    
           XXXX       XXX     
              XXXXXXXXX       
XXXXXXXXXXXXXXX  XXXXXXXXXXXXX
XXXXXXXXXXX      X     XXXXXXX
XXXXXXXX                 XXXXX
XXXXXX XX   XXXXXXXXXX  XXXXXX
XXXXX XXXXX XXXX  XXXX XX XXXX
