 X  XXX    XXXXXXXXX          
XXX  X   XXXXXXXXXXXXX     X  
 X     XXXXXXXXXXXXXXXXX  XXX 
          XXXXXXXXXXXXXXX  X  
  XXXXXX     XXXXXXXXXXXXX    
     XX        XXXXXXXXXXXX  X
    XX          XXXXXXXXXXXX  
   XX    XXXXX   XXXXXXXXXXX  
 XX        XX    XXXXXXXXXXX  
 XXXXXXX  XX      XXXXXXXXXXX 
         XXXXX     XXXXXXXXXX 
  XXXXX            XXXXXXXXXX 
    XX             XX XXXXXXX 
   XX       X     XXX  XXXXX X
  XXXXX      XXXXXXXXX  XXX  X
              XXXXXXX X     XX
               XXXXX XX XX XXX
               XXXXXXXX XX XXX
 X           XXXXXXXXXXXXXXXXX
 XXX         XXXXXXXXXXXXXXXXX
 XXXX      XX XXXXXXXXXXXXXXX 
  XXXXX    XXXXXXXXXXXXXXXXXX 
  XXXXXXXXXXXXXXXXXXXXXXXXXX  
X   XXXXXXXXXXXXXXXXXXXXXXXX  
XX  XXXXXXXXXXXXXXXXXXXXXXX   
X    XXXXXXXXXXXXXXXXXXXXX   X
      XXXXXXXXXXXXXXXXXXX     
 X X   XXXXXXXXXXXXXXXXX    X 
XXX  X   XXXXXXXXXXXXXX    XXX
 X  XXX     XXXXXXXXX   X   X 
