XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X X                        X X
X X          XXXX        X X X
XXX         XXXXX          XXX
XXX          XXXXX       X XXX
XXX       XXX XX XX        XXX
XXX       XXXX   XXX     X XXX
XXX       XXXX   XXX       XXX
XXX        XX    XXX     X XXX
XXX         XXXXXXXX       XXX
XXX         XXX  XXX       XXX
XXX                        XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X  XX  XX  XXXXXXXX  XX  XX  X
 XXX  XX   XXXXXXXX   XX  XXXX
XX   XX   XXXXXXXXXX   XX  X  
XXXXXXXXX XXXX  XXXX XXXXXXX  
    XX   XXXXXXXXXXXX   XX    
XXXXXXXX XXXXXXXXXXXX XXXXXXXX
  X  X  XXXXX    XXXXX  X  X  
XXX  XX XXXXXXXXXXXXXX XX  XXX
XX    X XXXXXXXXXXXXXX X    XX
X      XXXXXXXXXXXXXXXX     X 
XXXXXX XXXXX      XXXXX XXXX  
XXXXXX XXXXXXXXXXXXXXXX XXXX  
XXXXXX XXXXXXXXXXXXXXXX XXXXX 
XXXXXXXXXXXXXXXXXXXXXXXXXXX   
     XXXXXXXXXXXXXXXXXXXX     
XXXX XXXXXX        XXXXXX XXXX
