            X                 
X          XX                 
XX      XXXXXXXXX             
XXX  XXXXXXXXXX XX            
XXXXXXXXXXXXXXXXXXX           
 XXXXXXXXXXXXXXXXXX           
XXXX  XXXXXXXXXX              
XXX    XXXXXXXXXXX            
XX         XX                 
X           X                 
   XXXXXXXX                 X 
  XXXXXXXXXXXXXX           XX 
 XX XXX XXXXXXXXXXX       XXX 
 XXXXXXXXXXXXXXXXXXXX    XXXX 
 XXXXXXXXXXXXXXX XXXXXX  XXXX 
 XXXXXXXXXXXXXX  XXXXXXXX XXX 
 XXXXXXXXXXXXXXXXXXXXXXXXX XX 
 XXXXXXXXXXXXXXXXXXXXXXXXXX X 
  XXXXXXXXXXXXXXXXXXXXXXXXXX  
   XXX X X X XXXXXXXXXXXXXXXX 
   XX          XXXXXXXXXXXXXXX
   X  X X X X   XXXXXXXXXXXXXX
   XXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXXXXXXXX
