                       X  X   
                      XX XX   
                  X  XXXXXX   
                  XXXXXXXXX   
           X    X XXXXXXXXX   
           X X  XXXXXXXXXXX   
       X   XXXX XXXXXXXXXX    
     X XX  XXXXXXXXXXXXXX     
     XXXXX  XXXXXXXXXXXX      
      XXXX   XXXXX            
       XXXXXXXXX XXX          
        XXXXXXX XX X          
          XXXXXXX  X          
         XXXXXXXX XX          
        XXXXXXXXXXXX          
      XXXXX  XXXXXXXXX        
   XXXXXXXXX XXXXXXXXXXX      
 XXXXXXXXXXXXXXXXXXXXXXXX     
XXXXXXXXXXXXXXXXXXXXXXXXXXX   
XXXXXXXXXXXXXXXXXXXXXXXXXXXX  
XXXXXXXXXXXXXXXXXXXXXXXXXXXX  
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
 XXX  XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX  XXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXX
