   X                          
  XXXXXXXXX                   
 XXXXXXXXXXX                  
XXXXXXXXXXXXX                 
 XXXXXXXXXXXXX                
 XXXXXXXXXXXXXX               
 XXXXXXXXXXXXXXX              
 XXXXXXX  XXXXXXX   XXXXXX    
 XXXXXXX  XXXXXXX   XXX  XX   
 XXXXXXX XXXXXXXX   XXX  XXX  
 XXXXXXX XXXXXXXX XXXXX  X XX 
  XXXXXX XXXXXXXX XXXXX  X  XX
   XXXXX XXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXX XXXXXXXXXXXXX
     XXX XXXXXX XXXXXXX  XXXXX
      XX XXXXX XXXX XXXXXXXXXX
       X XXXX XXXX XXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXX
     XXX  XXX      XXX  XXX   
     XXX  XXX      XXX  XXX   
     XXXXXXXX      XXXXXXXX   
      XXXXXX        XXXXXX    
       XXXX          XXXX     
