      X X                     
    X X X                     
    XXXXX                X X  
    XXXXX                X X X
    XXXX                 XXXXX
    XXXXXX  XXXXXXXXX    XXXXX
   XXXX    XXXXXXXXXXX XXXXXXX
  XXXX    XXXXXXXXXXXXX   XXXX
 XXXX  XXXXXXXXXXXXXXXXXX  XXX
XXXX  XXXXXX   XX   XXXXXX XXX
XXX   XXXXXX XXXXXX XXXXXX XXX
XXX   XXXXXX XXXXXX XXXXXX XXX
XXX   XXXXXXXXXXXXXXXXXXXX XXX
XXXX   XXXXXXXXXXXXXXXXXXX XXX
 XXXX    X   XXXXXX   XXX  XXX
  XXXX   X    XXXX    X    XXX
   XXXX  X            X    XXX
    XXXXXX  XXXXXXX  XX    XXX
     XXXXXX   XX XX XXXXXXXXXX
      XXXXXXX  XXX XXXXXXXXXXX
       XXXXXXX    XXXXXXXXXXXX
        XXXXXXXXXXXXXXXX      
         XXXXXXXXXXXXXXX      
         XXXXXXXXXXXXXXX      
         XXXXXXXXXXXXXXX      
