XXXXXXXXXXXX XXXXXXXXXXX  XXXX
XXXXXXXXXXXXXXXXXXXXXXXXX  XXX
XXXXXXXXXXXXXXXXXXXXXXXXXX  XX
XXX XXXXXXXXXXXXXXXXXXXXXX  XX
XXXXXXXX XXXXXXXXXXX XXXX  XXX
XXXXXXXXXXXXXXX XXXXXXXX  XXXX
XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX        XXXXX XXXXXXXXX
        XXXXX    XXXXXXXXXXXX 
       XXXXXXX        XXXXXXXX
      XXXXXXXXX               
      XX X X XX               
      XX  X  XX               
      XXX   XXX               
       XXXXXXX                
        XXXXX                 
       XXXXXXX                
      XXXXXXXXX               
     XXXXXXXXXXX              
    XXXXXXXXXXXXX             
    XX XXXXXXXX XXX           
       XXXXXXXX  X XXXXXXXXXXX
       XXXXXXXX   XXXXXXXXXXXX
        XX XX      X        X 
       XXX XXX      XXXXXXXX  
