                         XXX  
                        XXXXX 
                       XXXXXXX
  XXXXXXXXXXXXXXX      XX   XX
 XXXXXXXXXXXXXXXXX     XXXXXXX
XXX XXXXXXXXXXXXXXX     XXXXX 
XX  XXXXXXXXXXXXXXXX     XXX  
XX XX XX           XX     X   
XXXX  XX            XX    X   
XXXXX X          XX  XX   X   
XXXXXXX         X  X XX   X   
XXXXXXXXXXXXXXXXXXXXXXXX  X   
XXXXXXXXXXXXXXXXXXXXXXXXX X   
XXXXXXXXXXXXXXXXXXXXXXXXXX    
 XXXXXXXXXXXXXXXXXXXXXXXXXX   
 XXXXXXXXXXXXXXXXXXXXXXXXXXX  
 XXXXXXXXXXXXXXXXXXXXXXXXXXXX 
 XXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XX   XXXXXX     XXXXXXXX    
        XXXXX     XXXXXXXX    
         XXXXXXXXXX      XXXXX
          XXXXXXXXXXXXXXXXXXXX
          XXXXXX       XXXXX  
           XXXXX       XXXXX  
            XXX         XXX   
