         XXXX                 
        XX  XX                
       XX    XX               
      XX      XXX     XXXX    
     XX        XXX  XXX XXX   
    XXXX XX   XXXXXX     XXX  
   XXXXXXXXX XXXXXX    X  XXX 
 XXXXXXXXXXXXXXXXX    XXX XXXX
XXXXXXXXXXXXXXXXX   XXXXXXXXXX
XXXXXXXXXXXXXXXX   XXXXXXXXXXX
XXXXXXXXXXXXXXXX   XXXXXXXXXXX
XXXXXXXXXXXXXXX   XXXXXXXXXXXX
XXXXXXXXXXXXXX    XXXXXXXXXXXX
XXXXXXXXXXXXX    XXXXXXXXXXXXX
 XX XX XXXXX                  
 XX XX XXXX  XXXXXXXXXXXXX    
            XX  XX   X   XX   
            X   XX   X   XX   
          XXXXXXXXXXXXXXXXX   
         XXXXXXXXXXXXXXXXXX   
         XXXXXXXXXXXXXXXXXX   
         XXXXXXXXXXXXXXXXXX   
XXX  XXX XXXXXXXXXXXXXXXXXX XX
            XXXX     XXXX     
             XX       XX      
