  XXX                         
 XXXXX                   XXX  
 XXXXXX                 XXXXX 
 XXXXXX                XXXXXX 
 XXXXX          X      XXXXXX 
 XXXX      XXX  XXX     XXXXX 
XXXXX   XXXX      XXXX   XXXXX
X    XXXX            XXXX    X
XXXXXX      XXXXXXXX    XXXXXX
 XXXX      XXXXXXXXXX    XXXX 
 XXXX     XXXXXXXXXXXX   XXXX 
 XXXX     XXXX XXXX XX   XXXX 
 XXXX    XXXX  XXX  XX   XXXX 
 XXXX    XXXXXXXXXXXXXX  XXXX 
 XXXX    XXXXXXX  XXXXX  XXXX 
 XXXXX    XXXXXXXXXXXXX  XXXX 
 XXXXXX   XXXXX   XXXX   XXXX 
  XXXXXX  XXXX XXX XXX  XXXXX 
   XXXXXX  XXXX   XXX  XXXXXX 
    XXXXXX  XXXXXXXX  XXXXXX  
     XXXXXXXXXXXXXXXXXXXXXX   
      XXXXXXXXXXXXXXXXXXXX    
       XXXXXXXXXXXXXXXXXX     
        XXXXXXXXXXXXXXXX      
        XXXXXXXXXXXXXXXX      
