               X              
            XXXXXXX           
      XXXX  XXXXXXXX          
      X     XXXXXXXXX         
     X X       X       XXXXX  
 XXXXXXXXXXX   X      XXXXXXX 
XXXXXXXXXXXXX  X     XXXXXXXXX
XXX       XXX  X     X XXXXXXX
XX   XXX   XX XX   XXXXXXXXXXX
XX XXXXXXX XX XXX  XXXXXXXXXXX
XX  X XXX  XX XXXX   XXXXXXXXX
XX XXXXXX  XX  XXXX  XXXXXXXXX
XX  XXXXX  XX  X XXX    XXXXXX
XX   XXX   XX    XXX  XXXXXXX 
XX    XXX  XXX   XXX  XXXXXX  
XX   XXXXX XXXX  XXXX   XXX   
XX  XXXXXX XXXXX  XXXXXXXXXXX 
XX  XXXXXX XXXXXX XXXXXXXXXXXX
XXXX      XXX XXXX XXXXXXXXXXX
XXXXXXXXXXXXX XXXXX   XXXXXXXX
 XXXXXXXXXXX   XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
                 XXXXXXXXXXXXX
                      XXXXXXXX
                      XXXXXXXX
