     XXX       
  XXXX XX      
 XXXXXX XXXXXX 
 XXXXXX XX    X
 X XXXX XX    X
 XXXXXX XXX  XX
 XXXXXX XXXXXXX
XXXXXX XXXXXXXX
 X   XXXXXXXXXX
 X   XXXXXXXXXX
 X   XXXXXXXXXX
 X X XXXX  XXXX
 XXX XXXX  XXXX
     XXXX  XXXX
     XXXX  XXXX
