  XXXXXXXXXXXXXXXX  
   XXXXX    XXXXX   
X   XX        XX   X
XX  X          X  XX
XXXX   X XX X   XXXX
  XX  X X  X X  XX  
XX X  X      X  X XX
XXXX  XX    XX  XXXX
XXXX   XX  XX   XXXX
XXXX    X  X    XXXX
XXXXX   X  X   XXXXX
XXXXXX  X  X  XXXXXX
XX  XX  X  X  XX  XX
  XXXXXXXXXXXXXXXX  
XXXXXXX      XXXXXXX
XXXXXXXXXXXX XXXXXXX
XX  XXX      XXX  XX
X   XXX XXXXXXXX   X
   XXXXX    XXXXX   
  XXXXXXX  XXXXXXX  
