 XXXXXXXXXXXX   XXX      
XXXXXXXXXXXXXXX  XXX   X 
XXX   XXX   XXX   XX   X 
XX XXX X XXX XXX  XXX XXX
XX X X X X X XXX  XXX XXX
XX XXX X XXX XXX  XX   X 
XXX   XXX   XXXX  X      
XXXXXXXXXXXXXXX   X  X   
XXXXX     XXXX    X  X   
 XXXX     XXXX    X XXX  
  XXXX   XXXX     X XXX  
 XXXXXX XXXXXXX   X  X   
XXXXXXXXXXXXXXXX  X      
XXXXXXXXXXXXXXXXX X    X 
XXXXXXXXXXXXXXXXX XX   X 
XXXXXXXXXXXXXXXXX XX  XXX
XXXX X X X XXXXXX XXX XXX
XXXXX X X XXXXXX  XXX  X 
 XXX X X X XXXXX XXX     
 XXXXXXXXXXXXXX  X       
  XXXXXXXXXXXXXXX    X   
XXXXXXXXXXXXX        X   
                    XXX  
XXXXXXXXXXXXXXXXXX  XXX  
                  XX X   
