    XXXXXXXXXXXXXXXXXXX       
    XXXXXX         XXXXX      
    XX                XX      
    X                  X      
  XXXXXXXXXXXXXXXXXXXXXXXX    
XXXXXXXXXXXXXXXXXXXXXXXXXXXX  
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX         XXXXXXXXXX 
 XXXXXXXXXXX  X  X  XXXXXXX   
XXXXXXX   XXXXX  XXXXXXXXXXX  
XXXXXX      XXX XXXX  XXXXXXX 
XXXXX   XXXXXXX X XXXX XXXXXXX
XXXXX       XXX XX     XXXXXXX
XXXXX        XX XXX     XXXXXX
XXXXXX       XXX XX     XXXXX 
XXXXXXX     XXXX X      XXXX  
XXXXXXXX    X     X    XXXXXX 
XXXXXX XXXXXXXXX XXXXXXXXXXXXX
XXXXXX   XXX   XXX XX XXXXXXXX
XXXXXX   XX         X XXXXXXXX
XXXXXXX  XX  XX  XX   XXXXXXXX
XXXXXXXX X  XXXXXXXX XXXXXXXX 
 XXXXX XX           XXXXX     
   XXX  XX    XXXX  XX        
    XX    X         X         
   XX X  XXX       XXXX       
 XXXX XX  XXXX  X XXXXXXXXXXX 
XXXXXX XX  XXXXXXXXXXXXXXXXXXX
XXXXXX  XX  XXXXXX XXXXXXXXXXX
