XXX  XXXXXXXXXXXXXXXX   XXXXXX
XXX XXXXXXXXXXXX         XXXXX
XX  XXXXXX                XXXX
XX XXXXXX                 XXXX
XX XXXXXX                XXXXX
XX XXXXXX                XXXXX
XX XXXXX                  XXXX
XX  XXXX                  XXX 
XXX XXX  XXXX      XXXXX  XXXX
XXXXXXX XX             XX XX X
XXXXXX    XXXX X X  XXX    X X
XXXX XX  X XX  X X X XXXX  X X
XXXX XX   XX   X X         X X
XXXXX X        X X         X X
XXXXX X        X           X X
XXXXX  X      XX          XXXX
XXXXXXXX      X           XX  
XXXXXXXX      XXXXX      XX  X
XXXXXX X                 XX XX
XXXXXX XX    XX   XX    XX  XX
XXXXXX XX   XX XXX XX   XX XXX
XXXXXXX X   XXXXXXXXX  XX  XXX
XXXXXXX XXX   XX  X    XX XXXX
XXXXXXX XXX    XXX    XXX XXXX
XXXXXXXX XXX X        XX  XXXX
XXXXXXXXX XXX   X X  XXX  XXXX
XXXXXXXX XXXXX X X XXXXXXX  XX
XXXX    XX XXXXXXXXXXXXXXXXX  
    XXXXXX  X XXXXXX  XXXXXXXX
XXXXXXXXXX  XX XX    XXXXXXXXX
