  XXXXXXXXXXXXXXX   XXXXXXXXXX
 XXXXXXXXXXXXXX   XXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXX  XXXX
XXX  XXXXXXXX  XXXXX   XX  XXX
X   XXXXXXXX  XXX XXXX  XXXXXX
    XXXXXXXXXXX      XX  XXXXX
   XXXXXX XXX     XX  XX  XXXX
  XXXXXX XX X    XX X  X XXXXX
   XXX X XXXX    XXXX XX XXXXX
  XXX XX  XXX     XX XX XXXXXX
  XX  X    X           XXX XXX
  XX  X   XX          XXX XXXX
  XX  X   X          XXX  XXXX
  XXX X  XX          X   XXXXX
   XXXX  X     X         XXXXX
     XX  XX    X        XXXXXX
      XX  XXX  X     XXXXXXXXX
      XX   XXX   X    XXX XXXX
       X     X   XXX   X XXXXX
       XX        XXXX  X XXXX 
      XXX        X XX XXXXXXX 
      XXXX       X  XXXXXXXX X
     XXXXXX            XXXXXXX
    XXXXXXX       X   XXXXXX X
   XXXXXXXXX      XXXXXXXXXX X
  XXX XXXXXXX    XXXXXXXXXX XX
XXXX  XXXX XXXXXXX    XXXX XXX
XX   XXX  XXXXXXXXXXXXXXXXXXXX
