XXXXXXXX  XXXXXXXXXX
XXXXX  XXX X XXXXXXX
XXXX XX XX XX XXXXXX
XXXXXXXXXXXXX XXXXXX
XXXXX  XXXXX XXXXXXX
XXXXX XXXXXX XXXXXXX
XXXX XX XXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXX
X   XX  XX     XXXXX
                XXXX
   XXX  X  XXX  XXXX
   XX  X XX XXX XXXX
X      X XX    XXXXX
XXX   XXXXX      X  
XX   XXXXX XX  X   X
XX   XXXXX XX   XXXX
X  X XXXXXXX XXX  XX
XXX XXXXXXXX XX  XXX
XX  XXXXXXXX  XXXXXX
XX XXXXXXXXXX XXXXXX
