   XXXX XXXXXXX
  XX   XXXXXXX 
 XX   XXXXXX   
 X   X   X XX  
 X  XX      X  
XXXXXX  XX XX  
X  XXX  XX XX  
X X XXX   XXX  
X X  XXXXX  XX 
XX           XX
 XXX          X
XXXX  X   XXXXX
XXXXX  XXXXXXX 
XXXXXX       X 
XXXXXXXXXXXXXX 
