X   XXXXXX   XXXXXXX
  XX XXXX  XX XXXXXX
 XXX XXXX XXXX XXXXX
 XXXX    XXXXX XXXXX
X X       XXX  XXXXX
XX         X  XX   X
X  XX   XX  XXX  XXX
X X X   X X XXX XXXX
X  XX   XX  XXX  XXX
X    XXX    XXXX XXX
XX    X    XXXXX  XX
XXXX     XXXXXXXX  X
X XXXXXXXX  XXXXX  X
   X   XX    XXXXX  
   XX XX    XXXXXXX 
X   X X   XXX XXXXX 
XXXXX XXXXX   XXXXX 
XX      XX     XXX  
XXXX   XXXX    X   X
   XX XX       X  XX
