XXXXX XXXXXXXXXXXXXXXXXXX XXXX
XXXX XXXXXXXXX       XXXXX XXX
XXX XXXXXX            XXXX XXX
XXX XXXXXX             XXX XXX
XXX XXXXX              XXX XXX
XX XXXXXX               XX XXX
XX XXXXXX   X        XX XX XXX
XX XXXXX   XXXXX   XXX  X XXXX
XX XXXXX  XX  XXX XXX   X XXXX
XX XXXXX  X XXXX  X XXX XX XXX
X XXXXXX                 X XXX
X XXXXXX                 X XXX
X XXX  XX                X XXX
X XXX  XX        XXX     X XXX
X XXXX  X       XXXX    XX XXX
X XXXXXX                X XXXX
X XXXX X       XXXXXX  XX XXXX
X XXXX XX     XX    XX X XXXXX
X XXXX XX     X XXX  X X XXXXX
 XXXXX XXX   XX      X X XXXXX
XXXXXX  XXX  XXX    XXXX XXXXX
X  XXX  X XXXXXXXXXXXXX XXXXXX
   XXXX XX XXXXXXXXXXXX XXXXXX
  XXXXX XXXX XXXXXXXXX XXXXXXX
    XXXX XXXXXX   X   XXXXXXXX
   XXXXX XXXXX    XXX  XX     
  XXX XX XXXXX   XXXXXX  XXXXX
      X   XXX   XX  XXXXXX  XX
      XX       XX   XXXX      
                      X       
