XX X       XXXXXX             
X X      XXXXXXXXXXXXXXXX     
 X      XXXXXXXXXX     XXXX   
X       XXXXXX  XX      XXXX  
       XXXXXX XX X       XXXX 
       XXXXX X XXX        XXXX
      XXXXXX XXXXXXXXXXXXXXXXX
   XXXXXXXX   XX XXX      XXXX
  XXXXXXXXX     XX XXXX      X
 XXXXXXX XX    XX     XXX     
 XXXXXXXX X   XXXXXX    XX    
XXXXXXXXXXX   X    XXXX  XX   
XXXXXXXXX X   X       XXXXX   
XXXXXXXXX X   X   XXX       XX
XXXXXXXXXXX   X XXXXXXX    XXX
XXXXXXXX XX   X  XXXXXXX   XXX
XXXXXXXX XXX XX   XXXXXXXXXXXX
XXXXXXX XXXXXXX     XX XX  XX 
XXXXXX XXXXXXXX     X  X  XXXX
XXXXXXXXXXXXXX      X  X XX  X
XXXX XXXXXXXXX     XXXXX X    
XXX XXXXXXXXX      X  XXXXXXX 
X  XXXXXXXXX    XXXX   XXX  XX
 XXXXXXXXXXXXXXXXX XX XX XX  X
XXXXXXXXXXX   XXX XXXXX   X XX
XXXXXXXXXX  XX XXXXX XX  XXXX 
XXXX    XXXX XX XX    XXXX    
XXXXX    XXXX X X   XXX   XXXX
XX XXX X X X XXXX  XXXXX  XXXX
    XX X XXXXX    XXXXXX   XXX
