         X  XXXX    
         X XXXXXXX  
         XXXXXXXXXXX
         X          
     XXXX XXXX      
   XXXXXX XXXXXX    
  XXXX XXXXX XXXX   
 XX XXX     XXXXXX  
 X XXXXXXXXXXXXXXX  
X  XXXXXXXXXXXXX XX 
X XXXXXXXXXXXXXXX X 
X XXXXXXXXXXXXXXX X 
XXXXXXXXXXXXXXXXXXX 
XXXXXXXXXXXXXXX XXX 
 XX XXXXXXXXXXX XX  
 XX XX XXXX XX XXX  
  XX X XXX XXX  X   
  XX  X X   X  XX   
   XX         XX    
    XX       XX     
