XX     XXXX    XXXXXXXXXXXXXXX
X    XXXXX     X    XXXXXXXXXX
X  XXX   XXX  XX        XXXXXX
X XX       XXXX            XXX
XXX          XX             XX
XX            XX    X        X
X           X  XX   XXXXX     
       XXX XXX  X   XXXXXXXX  
 X    XX XXX XX X  XXXXXXXXXX 
 X   X XX  XX XXX XXX XXXXXXXX
XX   X  X   X XX  XX XXXXXXXXX
X  X X       XXX   X    XXXXXX
  XX X       X X   X XX  XXXXX
  X  X  XXX  X X   X X   XXXXX
 XX XX   X  XX X  X      XXXXX
 X  XXX    XX  X  X   XX X  XX
 X XX XXX XX  XX  XXX XX    XX
 X XXX  XXX   X    X      XXXX
 XXX XXXX XX  X    X     XXXXX
  XX   X  XX XXX   XXXX   XXXX
  XXX XXX XXXX XX     X XXXXXX
X  XXXXXXXXXXXX XXX   XXX  X  
XXXXXXXXXXXXXXXX  XXX X  XXXX 
XXX      XXXXXXXX  XXXXXXXXXXX
XXXXX         XXXXXX   XXXXXXX
XXXX      X XXXXX X     XXXXXX
XXXX  XXXXXXX   X X     XXXXXX
XXXXX XXXXX   XXX X    XXXXXXX
 XXXXXXX X     XXXX  XXXXXXXXX
X XXXXXX X       XXXXXXXXXXXXX
