          XXX  XXXX    XX
 XXX       XXXXXXXX   XXX
 XXXXX      XXXXXXX XXXX 
  XXXXX     XXXXXXXXXXXX 
   XXXXXX    XXXXXXXXXX  
 XXXXXXXXXX  XXXXXXXXX   
    XXXXX    XXXXXX   XXX
     XXXXX   XXXXXXXXXXX 
      XXXX   XXXXXXXXX   
      XXXXX  XXXXXX      
      XXXXXXXXXXXXXX     
      XXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXX 
 XX   XXXXXXXXXXXXXXXXXX 
 XX    XXXXXXXXXXXXXXXXX 
 XXX   XXXXXXXXXXXXXXXXX 
 XXX   XXXXXXXXXXXXXXXXX 
      XXX    XXX XXXXXXX 
      XXX     XX    XXXX 
     XXX      XX     XX  
     XX       X      XX  
    XXX      XX     XX   
   XXX      XXX    XXX   
  XXX      XXX    XXXX   
