   X   X   X   X   X   X   X  
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                             X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              X X          X X
  XXXXXXXXXX   X    XXXXXX  XX
 XXXXXXXXXXXX     XXXXXXXXX   
XXXXXXXXXXXXXX   XXXXXXXXXXX  
XXXXXXXXXXXXXXX XXXXXXXXXXXXX 
XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
XXXX XX XXXXXXXXXXXX XX XXXXXX
XXXX  X XX XX XXXXX  X X  XXXX
XX           XXXXXXXX   XXXXXX
XX XXX  XXX  XXXX           XX
XX  XX   XX  XXX   XXX  XXX  X
X            XXXXXXX XXXX XXXX
X  XX     XX XXX   XXX  XXX   
XX XX X X XX XXX              
XX    XXX   XXXXX    XXXX    X
XXX        XX XXX    X  X   XX
 XXXXXXXXXXX   XXX   XXXX   XX
      X X   X  X XXX       X X
X    XXXXX    XX   XXXX XXXX X
  XXXX X XXXX X X     X XX X  
 XX XXXXXXX XX   XXXXXXXX XXX 
XX  X     X  XX XX  X  X  X XX
X X X     X X X X   XXXXXXX  X
X X X     X X X X X        X X
X X X     X X X X X    X   X X
X X XXXXXXX X X X X        X X
