XX   XXXX          XXXXXXX    
X   XXXXXX        XXXXXXXX    
   XXXXXXXXX    XXXXXXXXXXX   
   XXXXXXXXXX  XXXXXXXXXXXX   
   XXXXXXXXXXXXXXXXXXXXXXXX   
   XXX   X      X     XXXXX   
   XXXXXXXXXXXXXXXXXXXXXXXXX  
  XXXXXXX   XXXXX    XXXXXXX  
  XXXXXXXXXXXXXXXXXXXXXXXXXXX 
  XXXX     XX XXXXX       XXX 
  XX  XXXXX X XXX   XXXX  XXX 
  XXXXXXXXXXXXXXXXXXXXXXXXXXX 
 XXXXXX    XXXXXXXX    XXXXX  
 XXXXX  X X XXXXXX   X  XXXXX 
 XXXX XX  XXXXX XX X   X XXXX 
 XXXXXXXXXXXXXXXXXXXXXXXXXXX  
  XXXXXXX  XXXX XXX XXXXXXXX  
X XXXXX   XXXXX XXXX  XXXXXX X
X XXXXXXXXXXXXX XXXXXXXXXXXX X
X XXXXXXXXXX XXX XXXXXXXXXXX X
X XXXXXXXXXX XXX XXXXXXXXXXX X
X  XXXXXXXX  XXXX XXXXXXXXXX X
XX XXXXXXXX XXXXX XXXXXXXXX XX
XX XXXXX XXX     XXXX XXXXX XX
XX XXXX XXXXXXXXXXXXXX XXX  XX
XX XXXX XXXXXXXXXXXXXX XXX XXX
XX  XXX XXX  XXX   XXX XXX XXX
XXX XXX X  XXXXXXXX XX XX  XXX
XXX XXXXXXXX      XXX XX  XXXX
XXXX XXXXXXXXXXXXXXXXXXX XXXXX
