   XX   XXXXXXXXX   
   XX  XXX XX XXXX  
   XX  XX      XXX  
  XXXX XXXXXXXX XXXX
 XXX X X X   X XXX X
 X   X XX XXX  XX  X
 XX  XXX   X  X X  X
  XXXXX  X X XX X XX
 XXXXXXX XXXXX XXXX 
XXX  XXXX     XXX   
XX    XXXXXXXXX XXX 
       XXXXXXXX   X 
  XXX XXXXXXXXX  XX 
 XX X XXXXXXXXXXXX  
XX  XXXXXXX XXXXX   
X   XXXXXXX  XXXX XX
X   XXXX X   XXX   X
X    XXX     XXX  XX
XX  XXXXX   XXXXXXX 
 XXXXXXXXXXXXX      
