 XX XXX  XXX                  
XXXXXXXXXXXXXX                
XXXXXXXXXXXXXXXX X XX         
XXXXXXXXXXXXXXXXXX  XXXX XXX X
XXXXXXXXXXXXXXXXXXXXXX XX XXXX
XXXXXXXXXXXXXX  XXXXXXXXXXXXXX
XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
X  XXXXX  XXXXXXXXXXXXXXXXXXXX
     X      XXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXX
XXX    XXXXXXXXXXXXXXXXXXXXXXX
  XX   X   XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXX
XXX    XXXXXXXXXXXX XXXXXXXXXX
X X     X XXXXX  XX  XX XX  X 
 XX     XXX XXXXXXX  XX   XXXX
            X     X      XX   
   XXX      X                 
 X X X   X XX  XXXX     XXXXX 
          XXX X X X    X  X X 
      X   X X   XXX       XX  
   XXXX   X X                 
          XXX     XX          
X          X      X           
XXXXXXXXXXXXX        XX       
   X  X     X     XXXX        
XXXX  XXXXX XX               X
XXXXXXXXXXXX XX             XX
XXXXXXXXXXXXX XXXXXXXXXXXXXXX 
XXXXXXXXXXXXX       X  X      
