     XXXXXXXXXXXXXXXXXXXXXXXXX
   XXXXXXXXXXXXXXXXXXXXXXXXXXX
   XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXXXXXXX  XXXXXXXXXXXXXXXX
XXXXXXXX X      XXXXXXXXXXXXXX
XXXXXX             XXXXXXXXXXX
XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
XXXXXX XXXX  XXX XXXXXXXXXXXXX
XXXXX XXXXX  XXX  XXX XXXXXXXX
XXXXX XXXXX  XXX  XXXX XXXXXXX
 XXXX XXXXX   XXXXXXXX XXXXXXX
 XXXXXXXXX    XX XXXXX XXX XXX
  XXXXXXXX     XXXXXXX XX   XX
  XXXXXXX       XXXXX  XX   XX
   XXXXXX              XX   XX
    XXXX              XXX   XX
      XX            XXXXX  XXX
      X            XXXXX   XXX
      XXXXX   X      XXX  XXXX
       XXXXXXXX       X  XXXXX
        X     X           XXXX
XXXXXXXXXXXXXXX    XX     XXXX
X        XXXXXX   XX      XXXX
XXXXXXXXXXXXX   XXX        XXX
       X       XX          XXX
       XXXXXXXXX           XXX
