    XXXX          XX
   XXXXXXX         X
  XXXXX   XX   XXX X
 XXXXX  X         X 
 XXXXX  XXXX  X     
XXXXX          XXXX 
XXXXX               
X XXX               
 XXX X     X X     X
 XXXXX      XX     X
 XXXXX             X
 XXXXX    XXXX    X 
XXXXXXX      X    XX
XXXXXXX          XXX
 XXXXXXX        XXXX
 XXXXXXXXX    XXXXX 
XXXXXXXXXXXXXXXXXXX 
XXXXXXXXXXXXXXXXXXX 
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
