XXX XXXXXXXX  XXXXX XXXXX
XXXXXX XXXXXXXXXXXXXX  XX
XXX XXXXX X XXXXXXXX    X
XXXXXXXXXXXXXXX XXX      
XXXXXXX XXXXXXXXXXXX    X
XXXXXXXXX XXXXXXXXXXX  XX
XX XXXXXXXXXX XXXX XXXXXX
XXXXXX XXX X XXXXXXXXXXXX
XXXX XXXXXXXXX XXXXXXXXXX
XXXXXXXXXXXXXXXXX XXXXXXX
XXXXXXXXX XXXXXXXXXXXX XX
 XXXXX XXXXXX XXXXXXXXXXX
XXXX XX XXXXXXXXXXXXXXXXX
XXXXXXXXXXX XXXX   XXXX X
XXXXXXXXXXXXXXX XXX XXXXX
XXXXXXXXXXXXXXX XXX XXXXX
XXXXXXXXXXXXXXX XXX XXXXX
XXXXXXX X XXXXXX   XXXXXX
XXXXXX X X XXXXXX XXXXXXX
XXXXX X X X XX XX XXXXXXX
XXXXX       XXX     XXXXX
XXXXX  XXX  XXXXX XXXXXXX
XXXXXXX X XXXXXXX XXXXXXX
XXXXXXX X XXXXXX   XXXXXX
XXXXXXX X XXXXX XXX XXXXX
