X X        XXXXXXXX        X X
  XX         XXXX         XX  
 XXXXXXXXXXX XXXX XXXXXXXXXXX 
 XXXXX     XXXXXXXX     XXXXX 
 XXXX   XXX XXXXXX XXX   XXXX 
 XXX   XXXXX XXXX XXXXX   XXX 
 XXXX  XXXXX XXXX XXXXX  XXXX 
XXXXXX  XXX  XXXX  XXX  XXXXXX
XXXXXXXX   XX XX XX   XXXXXXXX
XXXXXXXXXXXXX XX XXXXXXXXXXXXX
XX   XXXXXXXX XX XXXXXXXX   XX
  XXXXXXXXXX  XX  XXXXXXXXX   
 XXXXXXXXXX  XXXX  XXXXXXXXXX 
XXXXXXXXXX  XXXXXX   XXXXXXXXX
XXXXXX XX XXXXXXXXXX XX XXXXXX
XXXXX  XX  XXXXXXXX  XX  XXXXX
XXXX  XXXX    XX    XXXX  XXXX
XXX  XXXXXXXX    XXXXXXXX  XXX
XXX XXXXXXXXXXXXXXXXXXXXXXX XX
XX XXXXXX     XX     XXXXXXX X
          XXX    XXX          
  XXXXXXXXXXXXXXXXXXXXXXXXXXX 
X X  X   X  X  X  X  X  X  X X
X X  X   X  X  X  X  X  X  X X
XX XXXXXXXXXX  X  XXXXXXXXX XX
XXX  X   X  XXXXXXX  X  X   XX
 XXX XXX X  X  X  X  X  XXX X 
 XXXX  XXX  X  X  X  X XX  XX 
 XXXXXX  XXXX  X  XXXXX  XXXX 
X XXXXXXX   XXXXXXX    XXXXX X
