 XXXXXXXXX  X X  XXX
 XXXXXXXXXXXX XXXXXX
   XXXXXXXXX  XXXXXX
      XXXXX  XXXXXXX
  XXX    X   X   XXX
 X  XX  XX  XXXX    
XX   XX X  XXXXXX   
X   X XXX XXXXXXXX  
X  XX X  XXXXXXXXXX 
XX    XX XXXXXXXXXXX
 XXX  XX XXXXXXXXXXX
 X     XXXXXXXXXXXXX
  XXX   XXXXXXXXXXXX
    XX XXXXXXXXXXXXX
    XXXXX   XXXXXXXX
  XXX  XXXXX       X
  X  XXX  XXXXXXXXX 
 XXXXX X X X X X  XX
X   X  X X  X X X  X
    X X X   XXX  XX 
