XXXXXX         XX   XX     XX 
XXXXXX      XXX XX X      XX  
XXXXXX        XX XXXX  XXXXX  
XXXXX       XXXXXXXXXXX   XXX 
XXXX       XXXXXXXXXXXXXX  XX 
XX X      XXXXXXXXXXXXXXXX XXX
X  XX    XXXXX XXXXXXXXXXX XXX
    XXXXXXXXXX XXXXXXXXXXXX XX
        XXXXX  XXXXXXXXXXXX XX
      X XXXXX   XXX  XXXXXX XX
      XXXXXX    XXXX   XXXX XX
      XXXXXXXXXX  XXXXXXXXX XX
X     X XXX               XXXX
XX    X  XXX XXX    XXX   XXXX
 X    X  XXX  X X    X X  XX X
 XX  XX   XXX XX     XX   X  X
  X  XX   XXX             X  X
  XX XX   XXX                X
   X XXXXXXXXX            X XX
  XXXXXXXXXXXX  XXXXXX    XXXX
 XXXXXXXXXXXXX   XXXXX   XXXXX
XXXXXXXXX  XXXX   XXX   XXXXXX
XXX  XXX  X XXXX       XXXXXXX
XX  X XX  X X XXXX   XXXXXXXX 
XX  X XXX  XX  X XXXXX XX X X 
XXX  XXXXXXX       X   X      
 XXXXXX XXX       XX   XX     
   XXXXXX      XXXXX   XXXXX  
     XXXXX    XXXX       XXXX 
    XXXXXXX  XXXXXX     XXXXXX
