                    
 X X X X X X X X X  
  X XXXXXX XXXXXX X 
 XXX XXXXX XXXXX X  
  XXX XXXX XXXX XXX 
 XXXXX XXX XXX XXX  
  XXXXX XX XX XXXXX 
 XXXXXXX X X XXXXX  
        X   XXXXXXX 
  X X XXXX          
 XX  XXXXX XXXXXXXX 
XXX XXXXXXX  XXXXX  
XXX XXXXXX XX XXXXX 
XXX  XXXX  XXX XXX  
XXX X XX X XXXX XXX 
XX X       XXXXX X  
X X XXXXXX XXXXXX X 
 X XXXXXX  X X X X  
X XXXXXX            
                    
