XXXXXXXXXXXXXXXXXXXX
  XXX      XXXX    X
 X X  X  X X   XX XX
X XX XX XX  XXX  XXX
XX X XX XX  X  XXXXX
XXXX        XXXXXXXX
XXXX  X X   XXXXXXXX
XXXX  XXX   XXXXXXXX
XXXXX     XXXXXXXXXX
XXX XXXXXXX  XXXX XX
XX            XXX XX
XX            XX   X
XX  X         XX   X
XXX X     X   XX   X
XXX X X  XX  XX    X
XXXXX X XXXXX      X
XXX XXXX X  X     XX
XXX  X   X  X     XX
XXX  X   X X     XXX
XXXXXXXXXXXXXXXXXXXX
