X XXXX XX  XXX XXXXXXXXXXXXXX 
 XXXXXX X XXXXX XXX XXXXXXXXXX
 XXXXXXXXXXXXXX XXXXXXX  X  XX
 XXXXX         XXXXXXX       X
  XX             XXXXX       X
X X    XXXXXXXXXX XXXX       X
XX   XXX         XXXXXX     XX
XX  XX        XXX XXXXXX   XXX
X   X  XXX         XXXXXX XXXX
X  XX X        XXX XXXXXXXXXXX
X  X   XXX    XX X  XX XXXXX X
X  X  XX XX   XXX   XXXXXXXXXX
X  X  XXX X   X X   XXXXXXXXXX
X  X  X X X XXXXX   XXX  XXXXX
X  XX XXX    XX     XX    XXXX
XX  X              XXX    XX X
XX  XX   XXX  XX   XXXX  XXX X
XXX  XX    XXXX   XXX XXXXX X 
XXXX  XX    XX   XX    XXXXX X
  XXXXXXXX    XXXX    XXXXXX X
   X   XXXXXXXX X    XXXXXXXXX
   XX    XX   XXX XXXXXXXXXXXX
   XX   XX         XX   XXXXX 
   XX   XXXXXXXXXX X     XXXX 
  XXXXX XX   XX  XXX     XXXX 
XXXXX  XX     X XX X     XXXX 
XXXXX  XX     XXX  X     XXXXX
XXXXXX XX     X    XX   XXXX X
X XXXXX X     X  XXXXXXXXXX XX
XXXXXXXXXX   XXXXXXXXXXX  XXXX
