XXXXXXXXXXXXXXX
XXX  XXXXX  XXX
XX XX XXX XX XX
X XXXX X XXXX X
 XXXXXX XXXXXX 
 XX  XXXXXXXXX 
 X XX XXXXXXXX 
 X XXXXXX  XXX 
 X XX  X XX XX 
 X XXX X XX XX 
 XX   XXX  XXX 
X  XXXXXXXXX  X
XXX  XXXXX  XXX
XXXXX XXX XXXXX
XXXXXX   XXXXXX
