 XXXX XXXX   XXXXXX 
 XX X X XX  XXXXXXXX
 XXXXXXXXX XXX    XX
  XXXXXXXXXXX  XXX X
 XXX XXX XXX  XXX  X
 XX X   X XX  XXXXXX
 X  X   X XX  XXXXX 
 X    XX  XXX  XXX  
 XX       XXXX  XXX 
  XXX XX XXXXX   XXX
 XXXXXXXXXX XXX   XX
 X XX  XX XX XXX   X
 X  XXXX  XXXXXX   X
 XX  XX  XXXXXXX   X
  XXXXXXXX XXXX   XX
 XX XXXX    XX  XXXX
 X   XX     XXXXXXX 
XXXX     XXXXXXXXX  
X  XX   XX     X    
XXXXXXXXXXXXXXXX    
