      X XXXX   X     XXXX X X 
     XXXXXXXXXXXX X XXXXXX  X 
    XXXXX      XXXXXXXXXXXX XX
   X  X  XXXXXXXXXXX  XXXXXX X
     XXXXXXXXXXXXXXXXX  XXXXX 
  XXXXXXXXXXXXXXXXXXXXXX XXX X
XXXXX  X X  XXXXXXXXXXXXXXXXX 
XXXXX  X X XXX  XXXXXXXXX  XX 
XXXX  X XXXXXXXXX XXX X X X X 
XXXX XX XXXX XXXXXX XXX X X XX
XXX XXXXX  XXXXXX X  XXXX X XX
   XXX XXXX  XXXX XXXX  XXXXXX
   X X XXX XX X XXX XXXX XXXXX
   X XXXXX X X  XX X X XXXX  X
     X XX  XXX   X   XXX X X X
     X  XX XX        XX  X X X
         X               X  XX
      XXX      X           XXX
     XXX X     X         XXXXX
    XX XXXXXX           X XXXX
   XXXXX X X   XXXXX   X XXXXX
 XXXXX  XX  XX        X XXXXXX
XX X      XX XX     XX XXXXXXX
  X   XXX    XXX  XXX XXXXXXXX
 XX   X  XX  X XXXX XXXXXXXXXX
XX       XX  X X  X  XXXXXXXXX
XX       X    XX  XXX  XXXXXXX
XX            XXX XXXXX XXXXXX
 X   XX       XXX XXXXXXX    X
 X    X    X  XX X XXXXX XXX  
