         XX  XXXX  XX         
        XX  XXXXXX  XX        
       XX XXXX  XXXX XX       
       XX X XX  XX X XX       
      X XXX X    X XXX X      
       X              X       
        X            X        
       X   XXXXXXXX   X       
       XXXX        XXXX       
      X    XXXXXXXX    X      
      X XXXXXXXXXXXXXX X      
      XXXXXXXXXXXXXXXXXX      
    XXXXXXXXXXXXXXXXXXXXXX    
  XXX XXXXXXXXXXXXXXXXXXXXXX  
 XXX XXXXXX   XX   XXXXXXXXXX 
XXX XXXXXXX X XX X XXXXXXXXXXX
XX XXXXX XX   XX   XX XXXXXXXX
X XXXXXXX XXXXXXXXXX XXXXXXXXX
X XXXXXXX XXXXXXXXXX XXXXXXXXX
XXXXXXXXX  XXXXXXXX  XXXXXXXXX
XXXXXXXX X XXXXXXXX X XXXXXXXX
XXXXX   X   XXXXXX   X   XXXXX
XXXXXXXXXX          XXXXXXXXXX
XXXXXXXXXXX        XXXXXXXXXX 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXX XX
XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
 XXXXXXXXXXXXXXXXXXXXXXX XXXX 
  XXXXXXXXXXXXXXXXXXXXXXXXXX  
