XXXXXXXX  XX XX XX X
XXXXX XXXXX  XX XXX 
X XX  X XX  XXXX XXX
XX   XXX   XXXXXX  X
XXXXXXXXXXXXXXXXXXXX
XXXX   XXXXXX    XXX
XX   X  XXXX  X   XX
 XX  X  XXXX  X  XX 
  XX X XX  XX X XX  
   XXXXX XX XXXXX X 
X X               X 
XXX     XXXXX     XX
  XX   X XXX X    XX
 XXX   XXXXXXX   XX 
XXXXX   XXXXX   XX  
XXXXXXX  XXX  XXX   
   XXXXXX   XXX     
 XX XX XXXXXXXXX    
X X XXX     XXXXX   
X XXXXXXXXXXXXXXXX  
