XXXX XXX    XXXXXXXXXX XX X XX
XX X  XXXXXXXXX         XX X X
X XX   XXXXX             XXX X
X  X   XXXXXX             X X 
X  X X XXXXXX             X X 
XX X XXXXXXX              XXXX
XX XXX XXXXXXX            XX X
X X X XXXXXX              X XX
X X   XXXXXXXXXXXX        XXXX
XXX  XXXXXX     XXX   XXXXXXXX
X XX  XXX   XXXX XX  XX     XX
   XX XX  XXXX XXX  XXXX  X  X
 XX XXXXX  XX   XXXXXXX X X   
 XX  XXXXX   XXXXX   X    X  X
 XXX XXXXXX    XXX          XX
  XXXXXXXX XXXXX XX   XXXXXXXX
X XXXXXXXXXX    XXX   X   XXXX
X  XXXXXXXX   XXXXXX   XX XXXX
XX XXXXXXXX XXXXXXX    XXXXXXX
XXXXXXXXXXX   XXXXXX  XX  XXXX
XXXXXXXXXXXX XXXXXXXXXX X XXXX
XXXXXXXX X X  XXXXXXX XX XXXXX
XXXXXXXXXX  XXX XXXXXX X XXXXX
XXXXXXXX  XXXXXX       XXXXXXX
XXXXXXXXX  XX XXXXXXX XX XXXXX
XXXXXXXX XX    XXXXX     XXXXX
XX  XXXXXX X  X X  X  X XXXXXX
X XX  XXXXXX X   XXXXX  X   XX
  XXX  XXXXXXXX   X X  XX  XXX
XXXXXXX  XXXXXX X     XX  XX  
