XXXXXXXXXXXX             
  XXXXXXXXXXX            
      XXXXXXXX   X       
                XXX      
            XX XXXXX     
    X       XXXXXXXXX    
    X       XXXXXXXXXX   
   XXX      XXXXXXXXXXX  
  XXXXX    XXXXXXXXXXXXX 
   XXX    XXXXXXXXXXXXXXX
  XXXXX    XXXXXXXXXXXXX 
 XXXXXXX   XXXXXX   XXXX 
   XXX     XXXXXX   XXXX 
  XXXXX    XXXXXX   XXXX 
 XXXXXXX   XXXXXX   XXXX 
XXXXXXXXXX XXXXXXXXXXXXX 
  XXXXX    XXXXXXXXXXXXX 
 XXXXXXX   XXXXXXXXXXXXX 
    X      XXXXXXXXXXXXX 
    X      XXXXXXXXXXXXX 
