XXXX  XXX     XXXXXX
XXX    XXX    XXXXXX
XXX     XXX    XXXXX
XXXXXXXXX    XXXXXXX
XXX   XXXXX XXXXXXXX
XXX XXXXXXXXXXXXXXXX
 X     XXX XXX  XXXX
 X    XXX  X XX XXXX
X        X XX   XXX 
X        X XX  XXXX 
X        XXXXX XXX  
XX     XX  XXXXXX   
XXX   XXXXXXXXXXX   
XXXX  XX   XXXXX    
X XXX   XXXXXXX     
X  XXX     XXXX     
XX XXXXX   XXXXXX   
XX  XXXXXXXXXXXXXXX 
 XX  XXXXXXXXXXXXXXX
  XX  XXXXXXXXXXXXXX
