XX XXXXXXXX XXXXXXXXX XX  XX X
XX XXXXXXX   XXXXXXXXXX XX X X
X XXXXXXXX    XX XXXXXXX XXXX 
X XXXXXXX     XX XX XXXXXXXXX 
X XXXXXXX      X  X  XXXXXXXX 
X XXXXXXX      X   XXXXXX XXX 
X XXXXXXXXX      XXXXXXXXX XX 
X XXXXXXXXXXX   XXX   XXXX XX 
XX XXXX    XXX XX      XXXXXXX
XX XXX XXXX XX X  XXXXXX XXXXX
XX XX XX XXX X X X XXXX  XXX X
XX XX  XX      X     XX   XX X
XX XXX  XXX  X XX  XXX   XXX X
XX X X      XX XX        XX  X
XX X XX     X   XX      XXX XX
XX XX XX    X    X   XXXXXXXX 
XXX XXXXX   XXXXX     XXXXXX X
XXXX  XX     XX    X XXX XXXX 
XXXXXX XX       XXXXX X XXXX X
XXXXXX XX X XXXX XX   X X XX X
XXXXXX XXX XX   XXX  XX X X   
XXXXXXX XXX   XXX   X  XX XXXX
XXXXXXX XXX         X  X  XXXX
XXXXXXXX XX        XX XX  X XX
XXXXX    XXX      XXXXX     XX
XX   XXXXX XXXXXXXXXXXX     XX
X XXXXXX  XXXXXXXXXXXX      XX
 XXXXXXX XXXXXXXXXXXXX     XXX
XXXXXXXX  XXXXXXXXXX   XX  XXX
XXXXXXXXX  XXXXXXX XXXXX  XXXX
