   XXXXXXXXXXXXXXXXXXXXX 
  XX  X            X   XX
  X  XXXXX        XXX   X
 X     X       XXXX     X
 X   XXX          XXX    
 X     XXXXXXXXXXXXX     
XX    XX XX X  XX  XX    
XXX  XX   X XX  X   XX  X
XXXXXX    X  X  X    XXXX
XXXX      X  X  X      XX
XXX     XXXXXXXXXXXX    X
XX    XXXXXXXXXXXXXXXX  X
X   XXXXXXXXXXXXXXXXXXX  
X XXXXXXXXXXXXXXXXXXXXXX 
 XXXXXXX           XXXXXX
XXXXXXXX           XXXXXX
XXXXXXX XXXX   XXXX XXXXX
XXXXXXX XX X   X XX XXXXX
XXXXXXX XXXX   XXXX XXXXX
 XXXXX  X         X  XXXX
  XXXX  XXX     XXX  XXXX
XX XXX      XX       XXX 
XX   X  XXXXXXXXXXX   X  
XXX  XX    X X X     XX X
XXXX  X    X X X     X  X
