   XXXXXXXXXX  
  XXXXXXXXXXXX 
  XXXXXXXXXXXX 
  XXXXXXXXXXXXX
 XXXXXXX  XXX  
X XXXXX XXXX XX
 XX XXX XX  XXX
 XXX  X     XXX
X XX        XX 
X  X XXXXX XX X
 XXXX XXX  XXXX
   XXX   XXX   
    XXXXXX XXX 
  XXX X  X XXXX
XXXXX X X  XXXX
