XXXXXX   XXXXXXXXX  
XXXX   XXX       XX 
XX   XXX          XX
XX XXX             X
XX X     XXX       X
XX X    XXXXX     XX
XX XX  XX XXX   XXX 
XX  XX  XXXXX  XX   
XXX XX   XXX  XX  XX
XXX  X  XXXXX XX  XX
XXX  XXXXXXXXXX  XXX
XXXX  XXXXXXXXX  XXX
XXXXX  XXXXXXXX XXXX
XXXXXX  XXXXX   XXXX
XXXXX  XXXXXXX XXXXX
XXXXX  XXXXXXX XXXXX
XXXX  XXX XXX  XXXXX
XXX  XXX XXX  XXXXXX
XXX  XXXXXXXX XXXXXX
XXXX   XX  XX  XXXXX
