   XX     XXXXXXXX       XX   
  XX     XXXXXXXXXXX      XX  
  X   XXXXXXXXXXXXXXXXXX   X  
  X  XXXXXXXXXXXXXXXXX  X  X  
  X   X   XXXXXXXXXXXX X  XX  
XXX    XX XX XXXXXX XXX   XXX 
X     XXXXXX  XXXX  XX      XX
X     XXXXXXXX XX XX XX      X
XX    XXXXX XX XX XX XX      X
XX    XX  X XX    XX XX     XX
X     XX           XXXX       
X    XXXX       XXXXXXX XX    
     XXXXX  X   XXX XX   XXX  
    XXXXXX  X    X  XXX  X XX 
    XXXXXXX  XXXXXXXXXXX X  X 
   XXXXXXXXX XX    XXXXX  X XX
   XXXX XXXXX XX  XXXXXX  X XX
   XXXX  XXXXXXXXXXXXXXX  XXXX
   XXXX  XXXXXXXXXX XXXX  XXXX
   XXXXX XXXXXXXXXX XXXX  XXXX
   XXXXX  XXXXXX    XXXXXXXXXX
   XXXXXX        XXXXXXXXXXXXX
   XXXXXXX      XXXXXXXXXXXXXX
   XXXXXXXXX   XXXXXXXXXXXXXX 
    XXXXXXXX  XXXXXXXXXXXXXX  
    XXXXXXXXXXX XXXXXXXXXXX   
    XXX  XXXXXX X XXXXXXXXX   
    XXX    XXX     XXXXXXXX   
     XX    XXX     XXXXXXXX   
     XX    XXX     XXXXXXXX   
