   XXXXXXX XXX     XXXX  
  XXXXXXX XX XXXXXXXXXXX 
 XXX   XXXXXXX    XX XXX 
 XXX     XX        XX XX 
 XXX               XXXXX 
 XXX               X  XX 
  XXX             XXXXXX 
  XXXXXXX    XXXXX XX  X 
  XX XXXXX  XXXXX   XXXX 
  XX X   XXXX    XX XX XX
   XX XXXX  XXXXXX   XXXX
   X XX XX  XX  XXX  XX X
   X     X   XX      X X 
   X  XXXX  X XXX   XXXX 
   XX   X   XX     XXXXX 
X  XX XXXX XXXX   XXXXXX 
X  XXXXXXXXX  XXXXXXXX  X
X   XXX   X      XX XXXXX
X   XX X XXXXXXX XX XXXX 
XXX XX XXX   XX XX XXX X 
XXX XX  X XXX     XXXX XX
XXXX XXX    XX XXXXXXX XX
XXXXXXX         XXXXX  XX
XXXXXXXX  X   XXXXXX  XXX
XXXXXX XXXXXXXXXXXX   XXX
