XXXXX                    XXXXX
XXX     XXXXX  XX    XXX   XXX
XX  XXXXXXXXXX XXX  XXXX    XX
X  XX  XXXXXXXXXXXXXXXXX     X
   X  XXXXXXXXXXXXXXXXXXXX   X
   X    XXXXX   XXXXXX   XX   
XXXX  XX XXXX  XXXXXXX XX X   
  XXXX  X X XX  X X X   X X XX
XX XXX XX  XX     X      XXX  
 XXXXX XX  XX  XX   XX   XX XX
X  XX  XX  XX X  X X  XX XXXX 
XXX XXX     X X XX XX X XXXX X
  XXX    XX X X XX XX X XXX XX
   XX       XX    X      XXXX 
 X  XXX     X    X X     X X  
 XX  XXXXXXXXX    X     XXXX  
  X  XXXX   XXXX      XXXXX X 
  X  X X X XXXXXXXXXXXXXXXX X 
XXX  X X XXXXXX X XX XX XXX X 
  X XX   XXXXX  XXX XX  XX  XX
  X XX  XXX    X   X   X XX  X
  X  XX  XXX  XX       X   X X
  X  XXXXXXXXXX      X XX XX X
  XX  XXXXXXXX      X X XXX  X
   XXXXXXXXXXX     X X XXX  XX
      XXXXXXXXXXXXXXXXXXXXXXX 
       XXXXXXXXXX X X  X      
     XXX X   X XXXXXXXXXX     
X  XXXXXXXX XXXX   XX   XX   X
XX XXXXXXXX XXX   XX     X  XX
