 XXX       XXX 
XXXXX  X  XXXXX
XXXX  XXX  XXXX
XXX XXX XXX XXX
  XXX XXX XXX  
 XXXXXX XXXXXX 
 XX XXX XXX XX 
XXXXXXX XXXXXXX
X X     XXXXX X
XXXXXXXXXXXXXXX
 XX XXXXXXX XX 
 XXXXXXXXXXXXX 
  XXX XXX XXX  
 X  XXX XXX  X 
XX    XXX    XX
