XXXXXX XX  XXXXXXXX 
X XXXXXXX  XXXX XXXX
XXX XXX      XXXXX X
XXXXXX  X  X  XXXXXX
X XXX  XXXXXX  X XXX
XXXX  XXXXXXXX  XXX 
 XX   XXXXXXXX   XXX
XX     XXXXXX     X 
X       XXXX       X
         XX         
XXXX   XX XXXX   XXX
XX        XXX     XX
XXXX   XX XX X   X X
XXXX   XX XX X   X X
XXXXX XXX XX XX XX X
XXX     X XXX     XX
XX X    X XX X   X X
XX X   X  X  X   X X
XX X   XX X  X   X X
XX X   XX  X X   X X
