X X X XX         XXX XXX 
X      XX       XX       
XX      XX     XX   XXXXX
X X      XX   XX       X 
X         X   X       X  
          XXXXX          
XXX      XXXXXXX      XXX
XXXXX   XXXXXXXXX   XXXXX
XXXXXX XX  XXX  XX XXXXXX
XXXXXX X    X    X XXXXXX
XXXXXXXX XX X XX XXXXXXXX
XXXXXXXX XX X XX XXXXXXXX
XXXXXXXXX  XXX  XXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX XX   XX XXXXXXXX
XXXXXXXX  X   X  XXXXXXXX
XXXXXXXX         XXXXXXXX
 XXXX  XX       XX  XXXX 
 XXX    XX     XX    XXX 
  X     XXXXXXXXX     X  
  X      XXXXXXX         
 XXX  XXXXX X XXXX       
  X  XXXXXX X XXXXXX XXX 
 XXX XXXXX  X  XXXXX     
  X   XXX    X  XXX      
