XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXX  XXXX XXXXXXXXXXXXXX
XXXXXXXX  XXXX  XXXXXXXXXXXXXX
XXXXXXX XXXXXX  XXXXXXXXXXXXXX
XXXXXX     XXXX XXXXXX    X   
 XXX X  XXXXXXXX XXXXXXXXXXXXX
  XX   XX   XXXXXXXXXXXXX     
X XX XXX XXX XXXXXX XXXXXXXXXX
X X XXXX XXX XXXX X XXXXXXXXXX
X   XXXX XXX XXX    XXXXXXXXXX
X  XXXXXX   XXXX  XXXXXXXXXXXX
   XX XXXXXXXXX  XX  XXXXXXXXX
 X XX    XXXX X  X XXXXXXXXXXX
XX X   XXX       X XX XXXXXXXX
XX X              X  XXXXXXXXX
XX X      XX      XXXXXXXXXXXX
XX      XXX   XXXXXXXXXXXX XXX
XX    XXX XXX  XXX  XXX XXX  X
XX   XXX    XXX      XX   XX  
XXX  XXXXX    XXX   XX        
XXX  XXXXXXX XXX   XXXXXX     
XXXX   XXXXXXX    XXX  XXXX   
XXXX     XXXX    XXX     XXX  
XXXXX  XX  X   XXXXX     XXXX 
XX XXX   X   XXXXXX       XXX 
  XXXXX     XXXXXXX       XXX 
  XXXXXX  XXXXXXXXX       XXX 
 XXX  XXXXXXXXXXXXX      XXXX 
 X   XXXXXXX XXXXX       XXXX 
   XXXXXX   XXXXXX     XXXXX  
