XXXXXXXXXXXXXXXX  XXX  XXXXXXXXXXXXXXXXX
X  XXX  XXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
XXX X XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX
XXXX XXXX X X XXXXXXXXXXXXX X X X  XXX  
XXXXXXXXX     XXXXXXXXXXXXX     XXX X XX
XXXXXXXXX XXX XXXXXX  XXXXX XXX XXXX XXX
XXXXXXXXX X X               X X XXXXXXXX
XXXXXXXX      XXXXXXXXXXXXX      XXXXXXX
XXXXXXX   X X XXXXXXXXXXXXX X X   XXXXXX
XXXXXX  X XXX XXXXXXXXXXXXX XXX X  XXXXX
XXXXX  XX X X XXXXXXXXXXXXX X X XX  XXXX
XXX   XXX     XXXXXXXXXXXXX     XXX   XX
X   XXXXX X X XXXXXXXXXXXXX X X XXXXX   
  XXXXXXX XXX XXXXXXXXXXXXX XXX XXXXXXX 
                                        
XXXXXXXX          XXXXXX         XXXXXXX
XXXXXXXX        XXXXXXXXX        XXXXXXX
XXXXXXXX       XXXXXXXXXXX       XXXXXXX
X XX XXX       XXXXXX XXXX       XXXX XX
XX XXXXXXXXXXXXX  XXXXX XXXXXXXXXXXX   X
XXXXX  XXXXXXXX XXXXXXXXXXXXXXXXXXX     
XXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX  X X 
XXXXXXXXXXXXXX          XXXXXXXXX  XX X 
 XXX  XXXXXXX XX XX XX X XXXXXXXX       
X XXXXXXXXXX XX XX XX XX  XXXXXXXXXXX XX
XXXXXXX XXX               XXXXXX        
XXXX XXXXXXX XXXXXXXXXXXX XXXX XXX      
XX  X XXXXXXX            XXX  XXXXXXXXXX
X XXXXXX X XXXXXXXXXXXXXXXXXXXX  XXXXXXX
XXXXXXXXX XXX  XXXXXXXXXXXXXXXXXXXXXXXXX
