XXX    XXX XXX X  XXX XX  XXXX
XXX      X  XX X  X  XXX  XXXX
XX XXXX   XXXX X  XXXXXX  XXXX
X XXX        X    XXXXXX  XXXX
    XXX  XXX X X  XXXXXX  XXXX
   XXXX  XXXXX X  XXXXXX  XXXX
X        X   X X              
X        X   X X              
            XX X  XXXXXX  XXXX
X     X     X     XXXXXX  XXXX
XX    XXXX  X XXXXXXXXXX  XXXX
 XX        XXXXXXXXXXXXX  XXXX
  XX       XXXXXXXXXXXXX  XXXX
  XXX     XXXXXXXXXXXXXXX XXXX
  X XXXXXXXXXXXXXXXXXXXXX XXXX
 XX   XXXXXXXXXXXXXXXXXXXX    
X XX    XXXXXXXXXXXXXXXXXX    
X  XX    XXXXXXXXXX XX XXXXXXX
X    X XXXXXXXXX X X XX XXX   
X  XXXXX  XXXXXX  XX  X XXXXXX
X  X XXX  XXXXX         XXX   
XXXXX  XX XXXX  X      XXXX   
XXXXXXXXX XXXXXXX   X   XX    
XXXXXXXXXXXXXXXX   XX X XX    
XXXXXXXXXXXXXXXXX     X X     
XXXXXXXXXXXX XXXXXXXXX  XXXX  
X XXXXXXXXXXXXXXXXXXX  XXX XXX
X  XXXXXX    XX X XX  XXX     
XX  XXXXXX    XX   X XXX  XX  
XXXXXXXXXXX    XX  XX  X  X   
