 XXX  X X  XXX 
XXXXX XXX XXXXX
XXXXX     XXXXX
XXXXXXXXXXXXXXX
 XXXXXXXXXXXXX 
   XX  X  XX   
XX X   X   X XX
 X X X   X X X 
 X X       X X 
XX XX  X  XX XX
    XX   XX    
 X X XXXXX X X 
  XX  X X  XX  
X   XXXXXXX   X
XXX   XXX   XXX
