XXXXXXXXXXXXXXX    XXX    X XX
XXXXXXXXXXXXX       XXX X XX X
XXXXXXXXX XX         XX XX X X
XXXXXXXX XXX         XXX XXXX 
XXXXXXX  XX XXX       XX XXXX 
XXXXXXX  X    XXXX    XXXXXXXX
XXXXXX          XXXX  XXXXXXXX
XXXXX  X X  X     X    XX XXXX
XXXXX XXX XX  XX X    XXXX XX 
XXXX XXXX  XXX  XX XXX  XXXX  
XX  XXXXXX  XXXX XXXX XXX  XX 
X  XXXX   XX X XXXXX XXX  XXXX
  XXXX     XXXXXXXXX XXXXXXXXX
  XXXX       XXXX XX XX  XXXXX
 XXXX          XX XX  XX XXXXX
 XXX          XXXXXX    XXXXXX
 XXX         XX  XXX    XXXXXX
 XXX        XXX   X     XXXXXX
 XXX          XXX    X XXXXXXX
  XX   XX      XXXX XX XXXXXXX
X XXX XX  XXX    XXX  XXXXXXXX
X  XX XXX X XXXX  X  XXXXXXXXX
X   XXXXX    XXXXXX XXXXXXXXXX
XX X XXXXX     XX  XXXXXXXXXXX
XX XX XXXXXX XXX XXXXXXXXXXXXX
XX  XX XXXX     XXX  XXXXXXXXX
 XX XXX  X     XXXXX  XXXXXXXX
 XX XXXXX      XXXXXX    XXXXX
  X  XXXXXX  XXXXXXX       XXX
  XX XX  XXXXXXXXX          XX
