XXXXXX XXXXXXX 
 XXXXXXXXXXXXXX
XXXXXXXXXXXXXXX
X XXX XX XX XX 
 XXX XX XX   XX
XXX XX     XXX 
X XXXXX   XXXXX
X   XXX   XXXX 
XXX          X 
  XX   XXX  XX 
   XX      XX  
    XXX  XXX   
 XXXX XXXXX    
XX  XX   XXXX  
XXXXXXX XX  XX 
