   XXXXXXXX XXX  XXX
  XXXXX XXX  XXX  XX
 XX X  XXXXX XXXX  X
XX X  XX XXXX XXXX X
XX    X  XXXXX  XXX 
XX X X   XXXXXXXXXX 
X  XXXXXX XXXXXXXXX 
XX XX    XX    XXXXX
XXXX XXX   XXXX XXXX
 XXXXXX X XXX X X XX
 XXX  XX  XXXX XXXXX
 X X      XXXXXXX  X
 XXX      XXXXXXX  X
  XX    XXXXXXXXX XX
  XX      XXXXXX XXX
 XXXX  XXXXXXXXX XX 
   XX   XXXXXXXXXX  
  X XX     XXXXXXX  
 XX  XX   XXXXX X   
XXXX   XXXXXXX  XX  
