XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
XX  XXXXXX    X XXX XXXXXX XXX
X XXXXX         XXXX XXXXXX XX
XXXXXXX         XXXXXXXXXXXXXX
 XXXXXX          XXXX   XXXX X
XXXXXX             XXXX   XX X
XXXX                XXXXX XXXX
XXXX                  XXXXXXXX
X XX XXX      X X X    XXXXXXX
X XX   XXXXX XX X XX  XXXXXXXX
 XXX     XXXXX  X  XXXXXXXXXXX
XXXX  XXXXXXXXX  XXXXXX   XXXX
XXX  XX  X XXX    XXXX X  XXXX
XXX    X XX XXX  XXX XX X XXXX
XX      XXXXXXX  XXXXXXX  XXXX
 X         XXX   XXXX     XXXX
 X       XXX    XXXXXX    XXXX
       XXX   X XXXXX XXX XXXXX
X           X   XX X     XXXX 
X          XXX     X     XXX  
X         XXXXXX  XXX   XXX   
X       XXX  XXXXXXXX   XX    
XX     XX     XXX  XX  XXX    
XXX    X  XX XXX XX X  XX     
X X      XX XXXXXXXX  XXXX    
X          XX   XX    XXXXX   
XX  X       XXXXXXX  XXX XX   
XX  XX    XXX XXXXX XXX  XXX  
 XX  XXX XX    XXX  XX X  XXX 
 XXX  XXX     XXXXXXX  X  XXXX
