  X XXXX   XX XXXX   XXXXXXXXX
 XX   XXX X       X     XXXXXX
XX X    XXX     XXXX  X  XXXXX
X XX   XX          XXXXX XXXXX
X XX              XXXX XX XXXX
X X  X           XXXXXX      X
XX   X             XXXX     X 
    XX    XX  X XX  XXXXX  XXX
 XXXX   XXXXXXX XXXX  XXXXXXX 
  XXX  X   XXXX XX XXXXXXXX  X
    X    XXXXX  X XXXXXX  XXXX
  X X  XXXX X    XX XXXXX   XX
 XX XX          XX XX XXXX   X
XXX XXX          XX  XXXXXX   
X X  XXXX    XX   XX XXX XXXXX
  XX XXX    XX     XXXXXX XXX 
  XX  XX   XXXXXX XX XXXXX    
 XXXX  XX XX   XXXXX XXX XX  X
X  XX   X X     XXXX XXXX   XX
XXXXXX  X    XX  XXX XXXXXXXXX
 XXXXXX     XXXXXXX XXXXXXXXXX
  X XXXXX      XXXXXXXXXXX  XX
    XXX XX   XXX  XXXXXXXXX  X
   XX XX XX XX     XXXXXXXXX X
XX X   XX XX      XXXXXXXXXX X
X  XX   XX XXXXXXXXXXXXXXXXX X
 X  X    XXX XXXXXXXXXXXXXX  X
XXX XX     XXXXXXX XXXXXXX  XX
XX  XX       XXXX   XXXXXX XXX
X XXXXX              XXXXXXXXX
