XXXXXXXXXXXXXXXXXXXX
XXX XXXXXXXXXXXX XXX
XXX  XXXXXXXXXX  XXX
XXX   XXXXXXXX   XXX
XXX  XXX XX XXX  XXX
XXX XX X XX X XX XXX
XXXXX          XXXXX
XXX              XXX
XXXXX XX    XX XXXXX
XXX   XX    XX   XXX
XXXXX  X    X  XXXXX
XXX              XXX
XXX   XXX  XXX   XXX
XXXX     XX     XXXX
XXXXX XX XX XX XXXXX
XXXXX          XXXXX
XXXXXXXX    XXXXXXXX
XXX X X XXXX X X XXX
XXX X X XXXX X X XXX
XXXXXXXXXXXXXXXXXXXX
