XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXX        XXXXXXXX X
XXX X X XXXXXXX  XXXXXXXX  XXXXX X 
XXXX   XXXXXX         XXXXX  XXXX X
XX   X   XXX X   XXXXX   XXXX XXXXX
XXXX   XXXX XX  XXXXXXX    XXX XXXX
XXX X X XX XXX  XX XXXXXX   XXX XXX
XXXXX XXX XXXXX   XXXXXXXX   XXX XX
 XXXXXXXX XXXXXXXXXXXXXXXX    XX XX
XXXXXXXX XXXXXXXXXXXXXXXXX    XXX X
XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX X
XX XXXX XXXXXXXXXXXXXXXX XXXXXXXXX 
 X X XX XXXXXXXXXXXXXXX XXX     XX 
X   XXX XXXXXXXXXXXXXXX XX  XX XXX 
  X   X XXXXXXXXXXXXXXX XX    XXX  
X   XXX XXXXXXXXXXXXXX XX XXXXXX X 
 X X XX XXXXXXXXXXXXXX XXXXXXXX XX 
XX XXXX XXXXXXXXXXXXXX XXXXXXX X   
XXXXXXX XXXXXXXXXXXXX XX XXXX X    
XXXXX XX XX  XXXXXXX XXXX XXXX X  X
 XXXXXXX X XX XXXXXXX     XXXXX X X
X XXXXXXX  X  XXXXXXXXXXX  XXXX  XX
 XXXX XXX  X  XXXXXXXXXX  XXXXX  XX
XXX X X XX  XXXXXXXXXX   XXXXX  XXX
XXXX   XXXX   XXXXXXX XX XXXX  XXXX
XX   X   XXX    XXXX    XXXX  XXXXX
XXXX   XXXXXX       XXXXXXX  XXXX X
XXX X X XXX XXX  XXXXXXXX  XXXXX X 
XXXXX XXXXXXXXXXX        XXXXXXXX X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
