XXX XXX XXX X XXX XXX XXX
X                       X
X                       X
     X       XXXXXX      
 XXXXXX  XXXXXXXXXXX    X
 XXX XXXXXXXXXXXXXXXX   X
  XXXXXXXXXXXXXXXXXXX   X
   XXXXXXXXXXXXXXXXXXX   
    XXXXXXXXXXXXXXXXXX  X
X    XXXXXXXXXXXXXXXXXX X
X     XXXXXXXXXXXXXXXXX X
X     XX XXXXXXXXX XXXXX 
      XXX XXX XXXXX XXXX 
X     XXX XXX   XXXX XXXX
X     XXX XXX    XXX  XXX
X    XXX  XXX   XXX  XXXX
    XXX  XXX   XXXX XXXX 
X                       X
X                       X
XXX XXX XXX X XXX XXX XXX
