    XXX             XXX  
    X X             X X  
     X               X   
     X               X   
     X               X   
     XXXXXXXXXXXXXX  X   
    XXXXXXXXXXXXXXXX X   
   XXXXX  X  X  X  XXX   
  XXXXXX XX XX XX  XXXX  
  XXXXXX  X  X  X XXXXX  
 XXXXXXXXXXXXXXXXXXXXXXX 
 XXXXXXXXXXXXXXXXXXXXXXX 
 XXXXXXXXX         XXXXX 
 XXXXXXXX           XXXX 
XXXXXXXX  XXXX  XXXX XXXX
XXXXXXXX   XX    XX  XXXX
XXXXXXXX   XX    XX  XXXX
XXXXXXXX             XXXX
XXXXXXXX       XX    XXXX
XXXXXXXX             XXXX
 XXXXXXX             XXX 
 XXXXXXX             XXX 
 XXXXXXX   XXXXXXX   XXX 
  XXXXXXX   X  XX   XXXX 
   XXXXXXX  XXXX   XXXX  
    XXXXXXXXXXXXXXXXXX   
     XXXXXXXXXXXXXXXX    
   XXXXXXXXXXXXXXXXXXXX  
  XXXXXXXXXXXXXXXXXXXXXX 
 XXXXXXXXXXXXXXXXXXXXXXXX
