   X             X       
   X             X       
  XXX           XXX      
  XXX           XXX      
  XXX           XXX      
 XXXXX         XXXXX     
 XXXXX    X    XXXXX     
XXXXXXX  XXX  XXXXXXX    
 XX XX    X    XX XX     
 XX XX   XXX   XX XX     
 XXXXX  XXXXX  XXXXX     
 XXXXX XXXXXXX XXXXX     
 XXXXXXXXXXXXXXXXXXXXX   
 XX XXXXX  XXXXXX XXXXXX 
 XX XXXX XX XXXXX XXXXXXX
 XXXXXXX XX XXXXXXXXXXXXX
 XXXXXXXX  XXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXX
 XX XXXXXXXXXXXXX XXXXXXX
 X   XXXXXXXXXXX   XXXXXX
 X   XXXXXXXXXXX   XXXXXX
 XXXXXXXXXXXXXXXXXXXXXXX 
 XXXXXXXX   XXXXXXXXXXX  
 XXXXXXXX   XXXXXXXXXX   
 XXXXXXXX   XXXXXXXXX    
      XXX   XXXXX        
      XXX   XXXX         
