X                        
XXX    XXXXXXXXX       X 
XXXX XXXXXXXXXXXX    XXX 
XXXXXXXXXXXXXXXXXXX XXXX 
XXXXXXXXXXXXXXXXXXXXXXXX 
 XXXXXXXXXXXXXXXXXXXXXXX 
  XXXXXXXXXXXXXXXXXXXXXX 
 XXXXX XXXXXXXXX XXXXXX  
 XXX   XXXXXXX   XXXXXX  
 XXXXXXXXXXXXXXXXXXXXX   
 XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXX
 XX     XXXXXXXXXXXXXXXXX
 X     XXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXX
 XXXXXXX XXXXXXXXXXXXXXXX
 X  XX    XXXXXXXXXXXXXXX
 X  XX    XXXXXXXXXXXXXXX
 XX  XX    XXXXXXXXXXXXXX
  X XXXXX   XXXXXXXXXXXXX
  XXX   XXXXXXXX XXXXXXXX
   X         XX   XXXXXXX
   XX       XXX   XXXXXXX
    XXXXXXXXXX    XXXXXXX
     XXXXXXXX      XXXXXX
                   XXXXXX
                   XXXXXX
                   XXXXXX
                   XXXXXX
