         XXXXXXX         
        XX  XXXXX        
        X    XXXX        
   XXXXXXXXXXXXXXXXXXX   
  XX     XXXXXXXXXXXXXX  
 XX    XXXXXXXXXXXXXXXXX 
 X    XX XXX  XXXXXXXXXX 
 XX   XX   X  X  XXXXXXX 
  XXXXX         XXXXXXX  
      X    X  XXXXX      
       X  XXXXXXXX       
        XXXXXXXXXX       
         XXX  XXX        
          XXXXXX         
     XXXXX XXXX XXXXX    
    XXXXXX  XX XXXXXXX   
   XXXXXXXX   XXXXXXXXX  
  XXXXXXXXX   XXXXXXXXXX 
 XXXXXXXXXX   XXXXXXXXXXX
XXXXXX XXXX   XXXXX XXXXX
XXXXX  XXXX   XXXXX  XXXX
XXXXX  XXXX   XXXXX  XXXX
 XXXXX X          X XXXX 
  XXXXXXX        XXXXXX  
   XXXXXXXXXXXXXXXXXXX   
    XXXXXXXXXXXXXXXXX    
       XXXXXXXXXXXX      
       XXXXXXXXXXXX      
         XXXX XXXX       
         XXXX XXXX       
