             X  X        
        X X XXX XX       
      X XXXXXXXXXX       
    X XX XXXXXXXXX       
    XX XXXXXXXXXXXX      
  XX XXXXXXXXXXXXXX      
X XXXXXXXXXXXXXXXXX      
XXXXXXXXXXXXXXXXXXXX     
XXXXXXXXXXXXXXXXXXXX     
XXXXXXXXXXXXXXXXXXXXX    
XXXXXXXXXXXXXXXXXXXXX    
 XXXXXXXXXXXXXXXXXXXXX   
 XXXXXXXXXXXXXXXXX   X   
  XXXXXXXXXXXXXXX     X  
  XXXXXXXXXXX   XX  X X  
   XXXXXXXXX     XX   X  
   XXXXXXXX       X  XX  
    XXXXXXX    X  XXXXXXX
    XXXXXXX       XXXXXXX
     XXXXXXX     XXXXXXXX
    XXXXXXXXX   XXXXXXXXX
    XXXXXXXXXXXXXXXXXXX  
    XXXXXXXXXXXXXXXXXXX  
       XXXXXX XXXXXXXXX  
       XXXXXX  XXXXXXXX  
       XXXXXXX   XXXXXX  
       XXXXXXXXX         
      XXXXXXXXXXXXX      
      XXXXXXXXXXXX       
     XXXXXXXXXX          
