                  XXX    
                XXXXXX   
                 XXX XXX 
      XX   XX    XXXXXXXX
     XXXX XXXX   XXXXXXXX
     XXXX XXXXX  XXXXXXXX
     XXXXXXXXXX  XXXX XXX
    XXXXXXXXXXX  XXXX    
   XXXXXXXXXXXXX XXXX    
  XXXXXXXXXXXXXXXXXXX    
 XXXXXXXXXXXXXXXXXXXX    
XXXXXXXXXXXXXXXXXXXXX    
X XXXXXXXXXXXXXXXXXXX    
  XXXXXXXXXXXXXXXXXXX    
 XXXXXXXXXXXXXXXXXXXX    
 XXXXXXXXXXXXXXXXXXXX    
 XXXXXXXXXXXXXXXXXXX     
XXXXXXXXXXXXXXXXXXXX     
XXXX XXXXXXXXXXXXXX      
XXX  XXXX XXXXXXXX       
XX   XXX  XXX XXX        
XX   XX   XXX XXX        
XX   XX   XX  XX         
XX   XXX  XX  XX         
XXX   XX  XX  XX         
 XX   XXX XX  XX         
 XXX   XX XX  XX         
  XX      XX  XX         
          XXX XXX        
           XX  XX        
