 X  XX  XX          XX  X  XXX
XXX XXX XXX        XXX XXX XXX
XXX XXX XXX  XXXXX XXX XXX XXX
XXX XXX XXX XX   XXXXX XXX XXX
XXX XXX XXXXX     XXXX XXX XXX
XXX XXX XXXX      XXXX XXX XXX
XXXXXXXXXXX    XXXXXXX XXXXXXX
XXXXXXXXXXX   X    XXXXXXXXXXX
XXXXXXXXXXX  XXXXXXXXXXXXXXXXX
XXXXXXXXXXX  XXXXXXXXXXXXXXXXX
 XXXXXXXXXXX X X XXXXXXXXXXXX 
    X   XXXXXXXXXXXXXX     X  
   XXX  XX X  XXXX XXX    XXX 
   XXX     X  XXXX        XXX 
   XXX    XXXXXXXXX       XXX 
    X     XXXXXXXXX        X  
          XX XXX XX           
          XX  X  XX           
           XXXXXXX            
            XXXXX             
