  XXXXXXXXXXXXX   X X    
 XXXXXXXXXXXXXXXX XXX    
XXXXXXXXXXXXXXXXXX X     
XXXXXXXXXXXXXXXXXXXX     
XXXXXXXXXXXXXXXXXXX X    
XXXXXXXXXXXXXXXXXXX XX   
XXXXXXXXXXXXXXXXXX   XX  
XXXX      XXXXXXXX X XXX 
XXX        XXXXXXXXXXXXX 
XX         XXXXXXXXXXXXXX
 X          XXXXXXXXXXXXX
 X          XXXXXXXXXXXXX
 XXXX XXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXX
 XX X XXX XXXXXXXXXXXXXXX
  XXX  XXXXXXXXXXXXXXXXXX
  XX    XXXX   XXX  XXXXX
  X            XXXX XXXXX
 X     X       XXXX XXXX 
 X     XX    XXXXX XXXX  
 XXXXXXXXXXXXXXXXXXXXX   
  X     XXXXXXXXXXXXX    
  X      XXXXXXXXXXX     
  X       XXXXXXXXXX     
  XXXXXXX XXXXXXXXXXX    
   X     XXXXXXXXXXXXX   
   XXXXXXXXXXXXXXXXXXXX  
    XXXXXXX XXXXXXXXXXXX 
     XXXXX  XXXXXXXXXXXXX
           XXXXXXXXXXXXXX
