XX XXXXXXXXXXXXX XXXXXXXXXXXX 
XX XXXXXXXX XX  XXXX    XXXX X
XX X     XXX  XXXX  XX  XXXX X
X XX XXXX  XXXXXX XX  X XXX XX
X XX    XXX  XX  XX XX XXX XXX
X XXX XX   XX  XX  XXX XXX X X
XX XX XXXXX         XX XXX X  
X XXX XXX   XXXX       XXX XX 
X XXXX     XXXXXXXX    XXXX  X
 XX XX    XXXXXXXXXX   XXXXXXX
 XX XX   XXX XXXX XXXX XXXXXXX
X X XX  XXXX XXXX XXXX  XXXXXX
XX XX   XXX XXXX XXXXXX  XX  X
XXXXX  XXX XXXXX XXXXXXX     X
X  X  XXXX XX X XXXXXXX     XX
     XXXXXX  XX XX XXX     XXX
X       XXXXXXX XXX X    XXXXX
XXX      XXXXXXX X XXX  XXXXXX
XXXXXX   XXXXXXX   XXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
