                 XX XXX       
     X XX XX XX XX XXXX       
  XXXXXX XX XX XX XXXXXXXXXXXX
 XXXXXX XX XX XX XXXXXXX     X
 XXXXXX  XX X XX XXXXXXXXXX  X
XXXXXXX  XX XX X XXXXXXXXXX  X
XXXXXXXX  XX X XXXXXXXXX     X
 XXXXXXX  XX XXX XXXXXXXXXX  X
 XXXXXXXXX XX XX XXXXXXX     X
  XXXXXXX  XX XX XXXXXXXXXX  X
  XXXXXXX XXXXXX XXXXXXXXXX  X
   XXXX XXXXXXXX XX XXXX     X
   XXXXXXX X X XXXXXXXXXXXX  X
    XXXXXXXX X XXXXXXXXXXXX  X
    XXXXXXXX X X XXXXXXX     X
     XXXXXXXXX X XXXXXXXXXX  X
     XXXXXXXXXXXXXXXXXXX     X
      XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX     XXXX         
       XX         X           
