XXXXXXXXX                               
XXXXXXXX          XXXXXXXXXXXX          
XXXXXXX        XXXXXXXXXXXXXXXXX        
XXXXXX        XXXXXXXXXXXXXXXXXXX       
XXXXX       XXXXXXXXXXXXXXXXXX  X       
XXXX       XXXXXXXXXXXXXXXXX X  XX      
XXX       XXXXXXXXXXXXXXXXX  X  XXXXXXX 
XX       XXX          XXXXX  X  XXXXXXXX
X       XXX            XXXX  X XXXXXXXXX
       XXX              XXX  XXXXXXXXXXX
      XXX               XXXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX 
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XX  XXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXX 
XX  XXXXXXXXXXXXXXXXXXX  XXXXXXXXX XXXX 
XX  XXXXXXXXXXXXXXXXXXX  XXXXXXXX   XX  
XXX XXXXX       XXXXXXX XXXXXXX         
X XXXXXXX X X X XXXXXXXXX XXXX         X
X                         XX          XX
XX                       XX          XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXX         XXXX
   XXXXXX            XXXXXX        XXXXX
   XXXXX             XXXXX        XXXXXX
    XXX              XXXXX       XXXXXXX
                      XXX       XXXXXXXX
                               XXXXXXXXX
