XXXXXXX XXXX    XXXXXXXX   XXXXXXXX  XXX
XXXXXXX X   XXX   XXXXXXXX  XXXXXXXXX   
XXXXXX   X  XXXXX  XXXXXXXX XXXXXXXX  XX
XXX   X XXX  XXXXX  XXXXXXXX XXXXX  XX  
   XXXX XXXX  XXXXX XXXXXXXX XXX   XXXX 
XXXXXXX XXXXX  XXXX  XXXXXXX XX  XXXXXXX
XXXXXXX XXXXXX  XXXX  XXXXXX   XXXXXXXXX
XXXXXXX XXXXXXX XXXXX XXXXX    XXXXXXXXX
XXXXXXX XXXXXXX  XXXX XXX  XXX   XXXXXX 
XXXXXXX XXXXXXXX XXXX X  XXXXXXX  XXXX X
XXXXX     XXXXXX XXXX  XXXXXXXXXX  XX XX
XXXX   X   XXXX XXXX      XXXXXXXX X XXX
XXX    X    XXX XX  XXXXX  XXXXXXX  XXXX
 X   XXXXX   X X  XXXXXXXX XXXXXXX XXXXX
 X     X X   X    XXXXXXXX  XXXXX   XXXX
 X  X  X       XXX XXXXXXXX XXXX  XX XXX
 XX      X  XX XXXX  XXXXXX XXX XXXXX XX
X  X  XXX  XX XXXXX  XXXXXX XX XXXXXX  X
XXX XXX XXX  XXXXX  X  XXXX X  XXXXXXX  
XXXX       XXXXX  XXXX XXXX   XXXXXXXXX 
XX  XX    XXXXX XXXXXXX XXX   XXXXXXXXX 
               XXXXXXXX  X XX  XXXXXXXX 
XXXXX      XXXXXXXXXXXXX  XXXX  XXXXXXX 
XXXXX     XXXXXXXXXXXXXX XXXXXX  XXXXX X
XXX         XXXXXXXXXX   XXXXXXX XXXX XX
XX XX XXX XX XXXXXXXX  X  XXXXXX  XX XXX
  XX XXXXX XX  XXXXX  XXX XXXXXXX X XXXX
XXXXXXXXXXXXXXXXXX  XXXXXX XXXXXX  XXXXX
XXXXXXXXXXXXXXXXX  XXXXXXX  XXXX  XXXXXX
XXXXXXXXXXXXXXXX XXXXXXXXXX XXX  XXXXXXX
