XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X    XXX    XXXXX    XXX    XX
 XX   XX XXX XXX XXX XX   XX X
 XXXX    XXX XXX XXX    XXXX X
  XXX     XXX X XXX     XXX  X
X  XX     XXX   XXX     XX  XX
XX XXX   XXX     XXX   XXX XXX
XX XXXX  XXX     XXX  XXXX XXX
XX  XXXX  XXX   XXX  XXXX  XXX
XXX   XX    X   X    XX   XXXX
XXXXX  XXX         XXX  XXXXXX
XXXXXX XXX X     X XXX XXXXXXX
XXXXXX  XXXXX   XXXXX  XXXXXXX
XXXXXXX   XXX   XXX   XXXXXXXX
XXXXXXXXX           XXXXXXXXXX
XXXXXXXXXXX       XXXXXXXXXXXX
XXXXXXXXXXX  XXX  XXXXXXXXXXXX
XXXXXXXXXXXX XXX XXXXXXXXXXXXX
XXXXXXXXXXXX XXX XXXXXXXXXXXXX
XXXXXXXXXXX XXXXX XXXXXXXXXXXX
