      XXXXXX      XXXXXX      
   XXXXXXXXXX X  XXXXX        
     XXXXXXXXXXXXXXXXXXXX     
   XXXXXXXXXXXXXXXXXXXXXXXX   
  XXXXX   XXXXXXXXX   XXXXXX  
 XXXXX     XXXXXXX     XXXXXX 
XXXXXX     XXXXXXX     XXXXXXX
XXXXXXX   XXXXXXXXX   XXXXXXXX
 XXXXXXX             XXXXXXX X
 XXXXXXX             XXXXXXX  
XXXXXXX               XXXXXXX 
XXXXXXX               XXXXXXX 
XXXXXXX XX X     X XX XXXXXXX 
XXXXXXX  X XX   XX X  XXXXXXXX
XXXXXXX     X   X     XXXXXXXX
XXXXXXX     X   X     XXXXXXXX
X XXXXXX    X   X    XXXXXX XX
 XXXXXXXX   X   X   XXXXXXX  X
 XXXXXXX    XXXXX    XXXXXX   
XXXXXXXX     XXX     XXXXXX   
XXXXXXXX      X      XXXXXX   
XX  XXXX    XXXXX    XXXXXX   
X   XXXXX XXX   XXX XXXXXX    
   XXXXXXXX       XXXXXXXX    
  XX  XXXXXXXXXXXXXXXXX  XX   
XXX    XXXXXXXXXXXXXXXX   XXXX
        XXXXXXXXXXXXXX        
         XXXXXXXXXXXX         
  X  X  X XXXXXXXXXX  X  X  X 
  X  X  X  XXXXXXXX   X  X  X 
