XXXXXX XXXXXXXX XXXXXXXXXXXXXX
XXXXXX XXX XXXXXXXXXXX XXXXXXX
XXX XX XXX XXXX XXXXXX XXX XXX
XXX XX XXXXXXXXXXXXXXX XXX XXX
XXX XX XXXX        XXX XXX XXX
XXX XXXXXX XXX  XXX XX XXX XXX
XXXXXX XX X  X X  X XXXXXXXXXX
XXX XXXXX XX XXXX X XX XXXXXXX
XXX XXXX XXX X XX XX XXXXX XXX
XXXXXXX XX         X XXXXX XXX
XXX     X          XX XXXXXXXX
XX XX   XXXXXX      X XXXXXXXX
    XX    XXXXXXXX  XX        
 XXXXXX  XXXXXXX     X        
   XXXXX X           XX       
  X XX XXXX           X       
     XX XX            XXXX    
      XXX             X  XX   
      XXX          X      X   
     XXXX      X   XX XX  X   
     X XX      XX   XXX   X   
     X  X       XX  XX   XX   
     XX XX       XX  X  XX    
      XX XX       X  X XXXXX  
     XXXX XXXXXXXXX  X XX  XX 
   XXX  XX XXXXX     X   XXXXX
  XXXXXXX XXXXXXXX   X     XXX
 XXXXXXXXXX    XX X XXX XXXXXX
      XXXXXXXXXXXXX XXXX XXXXX
     XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXX
   XXXXXXX XXXXX XXXXXXXXXXXXX
    XXXXX XXXXX XXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXX 
        XXXXXXXXXXXXXXXXXX    
