XXXXX           XXXXXXXX      
XXXX         XXXXXX    XX     
XXXXX      XXXXXX       X    X
XXXXX    XXXXX           X   X
XXXX   XXXXXX XXXXXX    XX  XX
XXX   XXXXX XXX  XX     XX XXX
     XXXXX  XX     XX  X XXXXX
   XXXXXX  XXX      XX X  XXXX
 XXXXXXXX   XX   XX XX XXXXXXX
XXXXXXX     X   XXX  X  XXXXXX
XXXXXXXX       XX X  X  X XXXX
XXXXXXXXXXX              XXXXX
XXX XXXXXXXXX            XXXXX
X X  XXXXXXXX             XXXX
X XX XXXXXXXX        XXX   XXX
X XXXXXXXXXXX       X  X    XX
X   XXXXXXXXXX      X       XX
XXX XXXXXXXXXX      XXXXXXXXXX
  X XXXXXXXXXX       XXXX XXXX
X   XXXXXXXXXXX        XX XXXX
XX  XXXXXXXXXXX       XX XXXXX
XXXXXXXXXXXXXXX     XX    XXXX
 XXXXXXXXXXXXXX    XX XX XXXXX
  XXXXXXXXXXXXX   XXXXXXXXXXXX
  XXXXXXXXXXXXX   X      XXXXX
   XXXXXXXXXXXX          XXXXX
    XXXXXXXXXXXX         XXXXX
    XXXXXXXXXXXX        XXXXXX
     XXXXXXXXXXXX       XXXXXX
      XXXXXXXXXXXX      XXXXXX
