    X                    XXXXX
    X                    XXXXX
    X                    XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X                            X
X                            X
XX                         XXX
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
   XXXXXX         XXXX XXXXXXX
   XXXXXXXX      XX    XXXXXXX
  XXXXXXXXXXX  XXXXXXX XX XXXX
  XXXXXXX XXX  XX XX   X  XXXX
  XXXXX    XX  X       X  XXXX
 XXXXXX     X  X       X  XXXX
 XXXXXX     X  X       X XXXXX
XXXXXXXX               X XXXXX
XXXXXXXX    X  X       XXXXXXX
XXXX XXX               XXXXXXX
XXXX XXX               XXXXXXX
XXXX XXXX              XXXXXXX
X XX XX X  XXXXXXX    XXXXXXXX
X XX XX X   XXXXX    XXXXXXXXX
X XX XX X           XXXX   XXX
X XX  X XXX        XX XXX    X
X  XX X  XXX  X   XX  XXXX   X
XX XX XX XXXXXXXXXX   XXXXX  X
XX XX XX XXXXXXXXXXXXXXXXXXXXX
