XXXXXXXXXXXXXXXX   XXXXXXXXXXX
XXXXXXXXXXXXXXX     XXXXXXXXXX
XXXXXXXXXXXXXXX        XXXXXXX
XXXXXXXXXXXXXX XX   X X  XXXXX
XXXXXXXXXXXXXX X X  X XX XXXXX
XXXXXXXXXXXXX X   X X   X XXXX
XXXXXXXXXXXXX  XXXXXXXXX  XXXX
XXXXXXXXXXXX               XXX
XXXXXXXXXXXX               XXX
XXXXXXXXXXXX               XXX
XXXXXXX  XXX               XXX
XXXXXX XX XXX             XXXX
XXXXXX XXXXXX             XXXX
XXXXXX                      XX
XXXXXX                      XX
XXXXXX                      XX
X  XXXX                    XXX
 XX XXXXX XXXXXXXXXXXXXX XXXXX
 XXXXXXX X XXXXXXXXXXXX X XXXX
X                             
