        XXXX        
      XXXXXXXX      
        XXXXXXXX    
   X  X  XXXXXXXX   
  X  X X  XXXXXXXX  
  X  X X  XXXXXXXX  
 XX   X   XXXXXXXXX 
 XX  X X  XXXXXXXXX 
XXX  X X  XXXXXXXXXX
XXXX  X  XXXXXXXXXXX
XXXXX   XXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXX 
 XXXXXXXXXXXXXXXXXX 
  XXXXXXXXXXXXXXXX  
  XXXXXXXXXXXXXXXX  
   XXXXXXXXXXXXXX   
    XXXXXXXXXXXX    
      XXXXXXXX      
        XXXX        
