    XXXX    XXXX         X    
  XXXXXXXXXXXXXXX   X    X    
 XXXXXXXXXXXXXXXXX  XX    X   
 XXXXXXXXXXXXXXXXXX  X XX X   
XXXXXXXXXXXXXXXXXXXXXXXX  X   
XXXXXXXXXXXXXXXXXXXXXX    XX  
XXXXXXXXXXXXXXXXXXXXXXX   XX  
XXXXXXXXXXXXXXXXXXXXXXX   XX  
XXXXXXXXXXXXXXXXXXXXXXXX  XX  
XXXXXXXXXXXXXXXXXXXXXXXXXXXX  
XXXXXXXXXXXXXXXXXXXXXXXX XXXX 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
X XXXXXXXXXXXXXXXXXXXXXXXXXX  
  XXXXXX     XXX XXX XXXX  XX 
  XXXXXX    XXXX XXX  X       
  XXX XXX  XXXXX XXX          
  XXX XXX   XXX  XXX          
  XXX XXXX   X   XXXX         
  XXX  XXX        XXX         
