   XX  X  XX             X    
    XX X XX           XXXX    
     X X X         XXXXX      
     XXXXX      XXXXXXX       
     XXXXX    XXXXXXXX        
     X X X  XXXXXXXX          
     XXXXXXXX XXXXXXX     XX  
    XXXXXX XXX XXX XXX   XXXX 
XX XXX  XXX XXX X XXXXX XXXXXX
XXXXX X   X XX XXX XXXXXXXXXXX
  XXXX  XXX X XXXXX XXXXXXXXXX
 XXXXXXXXX XXX XXX XXXXXXXXXXX
XXXXXXXXXX XXXX X XXXXX XXXXXX
XX XXXXXX XXXX XXX XXX  XXXXXX
    XXXXXXX X XXXXX X   XXXXXX
     XXXXXXXXX XXX X    XXXXXX
      XXXXXXXXX X X    XXXXXXX
     XXXX              XXXXXXX
     XXXX             XXXXXXXX
    XXX     XXXX     XXXXXXXXX
   XXX     XXXXXXXXXXXXXXXXXX 
       XXXXXXXXXXXXXXXXXXXXXX 
X    XXXXXXXXXX XXXXXX XXXXX  
 XX  XX  XXX   X  XX  XXXXX   
  XXX        XXXX   XXXXXX    
            XXXXXXXXXXXXX     
          XXXXXXXXXXXXXXX     
      XXXXXXXXXXXXXXXXXX      
X  XXX   XXXX  XXXXXXX        
 XX               XXX         
