        XXX         
   XXX XXXX   XXX   
  XXXXX  XX  XXXXX  
 XXXXXXXXXXXXXXXXXX 
XXXXXXX XXXX XXXXXXX
XXXXXXXX    XXXXXXXX
XXXXXX XX  XX XXXXXX
XXXXXX XXXXXX XXXXXX
XXXXXX XXXXXX XXXXXX
XXXXXX XXXXXX XXXXXX
XXXXXX XXXXXX XXXXXX
XXX XX XXXXXX XX XXX
X X X   X  X   X X X
X X      XX      X X
X       XXXX       X
