  XXXXXXXXXXX  XXX  
  X         XXXX X  
  XXXXXXXXXXXX   X  
  X   XXXX        XX
 XXXX      XXXXXXX  
XXXXXXXXXXXXXXX X   
XXXXXXXXXXXX XXX X  
XX XXXXXXXX XX XX   
X  XXXXXXXX XX  XX  
XXXXXXXXXXX XX   XX 
 XXXXXXXXXXXX     XX
 XXXXXXXXXX      XXX
XXXXXXXXXX      XXXX
XXXXXXXX   XX   XXXX
XXXXXXXX  XX      X 
XXXXXXXX XXXX    XX 
XXXXXXXX X  XX  XX  
XXXXXXXX     XX X   
 XXXXXXX      XXX   
 XXXXXXXX    XX     
  XXXXXXXX  XX      
XXXXXXXXXXXXX       
X       XXXXXXXXX   
XXXXXXX         XX  
 XXXXXXXXXXXXXX XXX 
