             XXXXXXX          
         XXXXXX   XXXXXXXXX   
     XXXXXX   XXXXXXXXX  XXX  
 XXXXXX   XXXXXXXXX   XXX   XX
X     XXXXXXXXX   XXXX    XXXX
XXXXX        XXXXXXX   XXXX XX
XX  XXXXXXXX     X   XXXXXX  X
X    XXXXXXXXXXXX XXXXXXXXX  X
X    XXXXXXXX  XX XX XXXXXX  X
X    XXXXXXX    X X   XXXXX XX
XX  XXXXXXXX    X X   XXXXXXXX
XXXXXXXXXXXX    X X   XXXXXXXX
XXXXXXXXXXXXX  XX XX XXX XXXXX
XXXXXXXXXXXXXXXXX XXXXX   XXXX
XXXXXXXXXXXXXXXXX XXXXX   XXXX
XXXXXXXXXXXXXXXXX XXXXX   XXXX
XXXXXXXXXXXXXXXXX XXXXXX XX XX
XXXXXXXXXXXXXXXXX XXXXXXXXX  X
XX  XXXXXXXXXXXXX XXXXXXXXX  X
X    XXXXXXXXXXXX XXXXXXXXX  X
X    XXXXXXXXXXXX XX XXXXXX XX
X    XXXXXXXX  XX X   XXXXXXX 
XX  XXXXXXXX    X X   XXXXX   
XXXXXXXXXXXX    X X   XXXX    
XXXXXXXXXXXX    X XX XXXX     
    XXXXXXXXX  XX XXXXX       
       XXXXXXXXXX XXX         
            XXXXX XX          
                XXX           
                 X            
