XXX  XXXXXXXXXX  XXX
X      XXXXXX      X
 XX      XX      XX 
 XXXX    XX    XXXX 
 XXXXXX      XXXXXX 
 XXXXXXXX  XXXXXXXX 
 XXXXXXX XX XXXXXXX 
 XXXXXXX XX XXXXXXX 
 XXXXXXX XX XXXXXXX 
 XXXXXXX XX XXXXXXX 
 XXXXXXX XX XXXXXXX 
 XXXXXXX XX XXXXXXX 
 XXXXXXX XX XXXXXXX 
 XXXXXXX XX XXXXXXX 
 XXXXXXX XX XXXXXXX 
X  XXXXX XX XXXXX  X
XXX  XXX XX XXX  XXX
XXXXX  X XX X  XXXXX
XXXXXXX  XX  XXXXXXX
XXXXXXXXX  XXXXXXXXX
