XX       XXXXXXXX       X
X   XXXXXXXXXXXX  XXXX XX
    XXXX XXXXXX  XXXX XXX
XX  XXXX XXXXXXX XXXX XXX
XX  XXXX XXXXXX  XXXX XXX
XX  XXXXX XXXXX XXXXX XXX
XX  XXXXX XXXXX XXXXX XXX
XX  XXX X XXXX  XX XX XXX
XX  XX  XX XXX XX  XX XXX
XX  XX  XX XXX XX  XX XXX
XX  XX   X XX  XX  XX XXX
XX  XX   XX X XX   XX XXX
XX  XX   XX X XX   XX XXX
XX  XX    XX XXXX  XX XXX
XX  XX    XXXXX X  XX XXX
XX  XX X  XXXXX X  XX XXX
XX  XX X   XXXXXX  XX XXX
XX XXXX    XXX XX XXXX  X
X       X     XX       XX
       XX    XX       XXX
