                              
     XXXX                     
     XXXXXX           XX      
    XXXXXXXX         XXXXX    
   XXXXXXXXXX        XXXXXX   
   XXXXXXXXXXXX    XXXXXXXXX  
  XXXXXXXXXXXXX   XXXXXXXXXXX 
  XXXXXXXXXXXXXXXXXXXXXXXXXXX 
  XXXXXXXXXXXX XXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 XXXXXX  X  XXXXXXXXXXXXXXXXXX
 XXXX        XXXXXXXXXXXXXXXXX
 XXXX       XXXXXXXXXXXXXXXXXX
XXXXX       XXXXXXXXXXXXXXXXXX
XXXXX        XXXXXXXXXXXXXXXXX
XXXXX         XXXXXXXXXXXXXXX 
XXXXX          XXXXXXXXXXXXXX 
XXXXX         XXXXXXXXXXXXX   
XXXXX         XXXXXXXXXX      
XXXX          XXXXXXXXX       
