               
   XXX   XXX   
   X X   X X   
   XXX   XXX   
  XXXXX XXXXX  
  XXX X XXX X  
 XXXXXXXXXXXXX 
XXXXX XX XXX XX
XXXXX XX XXX XX
XXXXX XXXXXX XX
XXXXXXX XXXXXXX
XXX X     XXX X
XXX X     XXX X
XXXXX     XXXXX
               
