                               XX X
     XXXXXXX                 XXX XX
    XXXXXXXXXXX           XXXXX XX 
  XXXXXXXXXXXXXXXX   XXXXXXXXX XXX 
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   X
XXXXXXXXXXXXXXXXXXXX  XXXXXXXX  XX 
XXXXXXXXXX          XXXXXXXXXXXXX  
XXXXXXXX    XXXXXXXXXXXXXXXXXXXX   
XXXXXXX    XXXXXXXXXXXXXXXXXXX     
XXXXXXX   XXXXXXXXXXXXXXXXXX       
XXXXX X   XXXXXXXXXXXXXXXX         
XXXXX XX  XXXX    XXXXX     XXXX   
XXXXX  X  XXX               XXXX   
 XXXXX X  XXX    X          XXXX   
  XXXX  X  XX   XXXX         XX    
  XXXXX    XX  XXXXX     XXXXXXXXXX
   XXXXX    XXXXXXXX     XXXXXXXXXX
     XXXX    XXXXXXX     XXXXXXXXXX
       XXXX XXXXXXXX     XX  XX  XX
        XXXXXXXXXXX      XX  XX  XX
          XXXXXXXX       XX  XX  XX
         XXXXXXXXXXXX    XXXXXXXXXX
        XXXXXXXXXXXXX    XXXXXXXXXX
       XXXXXXXXXXXXXXX   XXXXXXXXXX
        XXXXXX XXXXXXX       XX    
         XXXX  XXXXXXXX     XXXX   
               XXXXXXXXX    XXXX   
                XXXXXXXXX   XXXX   
