XXXXX XXXXXXX XXXXXX
XX               XXX
XXXXXX XXXX XXXXX  X
XXX           X    X
XXXXXX XX XXXX     X
XXXXXXXXXXXX    XX X
XXXX       X  XXXX X
XXXX XXXXX X  XX X X
XXXX X   X X  X  X X
XXXX X   X X  XXXX X
XXXX X   X X  XXXX X
XXXX XX  X X       X
XXXX X   X X       X
XXXX X   X X       X
XXXX X   X XXXX    X
XXXXXXXXXXXXXXXXX  X
XXX  XXXXX  XXXXXXXX
XX   XXXXXX   XXXXXX
XX   XXXXXX     XXXX
X    XXXXXXX      XX
