XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX       XXXXXXXXX
XXXXXX             XXXXXX
XXXX                 XXXX
XXX   XX X     X XX   XXX
XX   XX  XX   XX  XX   XX
X   XXX  XXXXXXX  XXX   X
X  XXXXX XXXXXXX XXXXX  X
  XXXXXXXXXXXXXXXXXXXXX  
  XXXXXXXXXXXXXXXXXXXXX  
  XXXXXXXXXXXXXXXXXXXXX  
  XXXXXXXXXXXXXXXXXXXXX  
X XXXXXXXXXXXXXXXXXXXXX X
X  XXX XX  XXX  XX XXX  X
XX  XX  X   X   X  XX  XX
XXX  X      X      X  XXX
XXXX        X        XXXX
XXXXXX             XXXXXX
XXXXXXXXX       XXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXX
