XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX        XXXXXXXXX
XXXXXX             XXXXXX
XXXXXXXX            XXXXX
XXXXXXXXX            XXXX
XX XXXX XXX           XXX
XX  XXXX XXX          XXX
X    XXXX  XXX         XX
X     XXXX  XXX        XX
X     XXXX    XXX      XX
X      XXXX    XXX     XX
X    XXXXXXXXXXXXXXX   XX
XX   XXXXXXXXXXXXXXXX XXX
XX       XXXX         XXX
XXX       XXXX       XXXX
XXXX       XXXX     XXXXX
XXXXX       XXXX   XXXXXX
XXXXXXXX    XXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXX
