XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX       XXXXXXX
XXXXXXXXXXXX    XXXXXXX   XXXX
X           XXXXXXXXXXXXXX  XX
 XXXXXXXX XXX X X X XXXXXXXX X
   X X X XX XX X X XX XXXXXXX 
XX      XX X       X X XXXXXX 
XXXXXX  X X         X XXXXXXX 
XXXXXX X             X  XXXXX 
XXXXXX                XX X XX 
XXXXXXX                 X XXX 
XXXXXXX XXXXXXX X X  XXXXXXXX 
XXXXXXX  X X X   X XXXXXXXXXX 
XXXXXXXX       X  XXXXXXXXXX  
XXXXXXXX XXXXXXX XXXXXXX X X X
XXXXXXXX          X X X X   XX
XXXXXXXXXXXXXXXX       XXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
