XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX  X     XXXXXXXXX
XXXXXX X  X        XXXXXX
XXXXX  XXXXXXXXX     XXXX
XXX  XXXXX  X  XXX    XXX
XXX XXX  X  X    XXX   XX
XXXXXX   XXXXX    XX   XX
XXXXXXXXXXXXXXX    XX   X
XX                 XX   X
XX                 XX   X
XX   XXXXXXXXXXXXXXXX   X
XX   XX                 X
XX   XX                 X
XX   XX    XXXXXXXXXXXXXX
XXX   XX    XXXXX   XXXXX
XXX   XXX    X  X  XXX XX
XXXX    XXX  X  XXXXX  XX
XXXXX     XXXXXXXXX  XXXX
XXXXXXX        X  X XXXXX
XXXXXXXXXX     X  XXXXXXX
