XXXXXXXXXXXXXXXXXXXX
XXXXXXX       XXXXXX
XXXXXX  XXXXX   XXXX
  XXX  XXXXXXXX  XXX
  XX  XXXX   XXX  XX
XXXX  XXX XXX XXX  X
XXXX  XXX   XX XX  X
  XX  XXX   XX XX  X
  XXX  XXXXXX XXX  X
XXXXXX  XXXX XXXX  X
XXXXXXX     XXXX  XX
XXX XXXXXXXXXXX  XXX
XXXX XXXXXXXXX  XXXX
XXXXX          XXXXX
XXXXXXXXXXXXXXXXXXXX
