XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
XX  XXXX       XXX      XXXXXX
XXX  X                   XXXXX
XXXX            X     X  XXXXX
XXXXX          X         XXXXX
XXXX           X         XXXXX
XXXX           X  XX  XX  XXXX
XXXX            XXX  X  XX   X
XXXXX                X    XXXX
XXXXXX               XXX    XX
XXXXXX               XXXXXXXXX
XXXXXX               XXXX  XXX
XXXXXX    XX    XX    XXX  XXX
XXXXXX    XXXXXXXX    XXX  XXX
XXXXXX    XXXXXXXX     XXXXXXX
XXXXXX    XXXXXXXXX    XXXXXXX
XXXXXX    XXXXXXXXX    XXXXXXX
