XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX X X XXXXX
XXXXXXXXXXX   XXXXXX
XXXXXXXXXXX     XXXX
XXXX    XXX    XXXXX
XXX XXXX XX     XXXX
XX XX            XXX
XXXX XXXX        XXX
XXX X  X         XXX
XXXXXXX         XXXX
XXXXXXXXX      XXXXX
XXXXXXXXXXX XX XXXXX
XXXXXXXXXXX XXX XXXX
XXXXXXXXXXX XXXX XXX
XXXXXXXXXX X XX X XX
