        XX               
       XXX               
       XX          XXXX  
      XX         XXXXXXX 
    XX          XXXXXXXXX
    XX XXX     XXXXXXXXXX
  XX  XXXXXX  XXXXXXXXXXX
 XX  XXXXX  XXXXXXXXXXXXX
XXX  XXXXX   XXXXXXXXXXX 
XX   XXXXXX   XXXXXXXXX  
      XXXXXX   XXXXXXX   
       XXXXXX  XXXXXX    
       X  XXXXXX XXX     
      XXXX XXXXXX X      
     XXXXXX XXXXXX       
    XXXXXXXX XXXXXX XXXX 
   XXXXXXXXX XXXXXXXXXXXX
  XXXXXXXXXX XXXXXX XXXXX
 XXXXXXXXXXXX XXXXXX XXXX
 XXXXXXXXXXXX   XXXXX XXX
 XXXXXXXXXXX     XXXXX X 
 XXXXXXXXXX      X XXXX  
 XXXXXXXXX       XX XX   
  XXXXXXX        XXXX    
   XXXX           XX     
