XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X     XXX  XXXXXXXX          X
X     XX  XX     XXXX        X
X     XXX X        XXXX      X
X   XXXXXXXXXXXXXX   XXX     X
X  XXXX XXXXXXXXXXX   XXX    X
X XXX    X       XXX   XX    X
XXXX              XXX  XXX   X
XXX XX     XXX     XXX  XX   X
XXXXXXX   XXXXXX    XXX XXX  X
XXXXXXXX  XXXXXXX    XX XXX  X
X XXXXXXX XXXXXXX    XX XXX  X
X XX   XX X   XXXX   XX XXX  X
X XX X XX X X XXXX  XXX XXX  X
X XX  XX  X   XXXX  XX  XXX  X
XXXXXXX   XXXXXXX   X X XXX  X
XXXXXX    XXXXXX    XXX XXX  X
XXX X              XXXX  XXX X
XX  XXX  XXX        X XX  XX X
XX   XXXXXX      XXX  XX  XXXX
XXX            XXXX  XXX   XXX
XXX X         XX  X  XX  X  XX
XXX XXX   XXXXX XXX XXX  XX XX
X X  XXXXXXXX X XX  XX   XXXXX
XXXX    XXX X XXX   XX   XX  X
XXXX     XXXXXXX   XX     X  X
XX XX              XX     XX X
XX  XX            XXX      XXX
X    XX        XXXXXX XXX   XX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
