       XXXXXXXXXXXXXXXX       
       XXX  XXXXXX  XXX       
       XXX  XXXXXX  XXX       
       XXXXXXXXXXXXXXXX       
       XXXXXXXXXXXXXXXX       
       XXXXXXXXXXXXXXXX       
       XXXXXXXXXXXXXXXX       
        X            X        
        X  XX    XX  X        
        X XXXX  XXXX X        
XX      X XXXX  XXXX X      XX
XXXXXX  X  XX    XX  X  XXXXXX
XXXXXXXXXX          XXXXXXXXXX
X XXXXXXXXXXXXXXXXXXXXXXXXXX X
X XX  XXXXXXXXXXXXXXXXXX  XX X
XX  X  X  XXXXXXXXXX  X  X  XX
 XXX XX XX XX XX XX XX XX XXX 
 X  X  X  X  X  X  X  X  X  X 
 XXX XX XX XX XX XX XX XX XXX 
  X X  X  X  X  X  X  X  X X  
  XX XX XX XX XX XX XX XX XX  
   XXXXXXXXXXXXXXXXXXXXXXXX   
   XXXXXXXXXXXXXXXXXXXXXXXX   
    XXXXXXXXXXXXXXXXXXXXXX    
     XXXXXXXXXXXXXXXXXXXX     
