XXXXXXXXXXXXXXX
XXXXXXXXXXXXX  
XXXXXXXXXXXX XX
XXXXXXXXXXX  XX
            XXX
  X X X X X XXX
X           XXX
X X X X X X XXX
X           XXX
XX XXXXXXX XXXX
XX XXXXXXX XXXX
XX XXXXXXX XXXX
X   XXXXX   XXX
X X XXXXX X XXX
XX XXXXXXX XXXX
