XXXXXXXXXXXXXXXXXXXX
XX  XXXXXXXXXXXX  XX
XXX  XXXXXXXXXX  XXX
XXXX  XXXXXXXX  XXXX
XXXX  XXXXXXXX  XXXX
XXXXX  XXXXXX  XXXXX
XXXXX  XXXXXX  XXXXX
XXXXXX        XXXXXX
XXXXXX        XXXXXX
XXXXX  XXXXXX  XXXXX
XXXXX  XXXXXX  XXXXX
XXXX  XXXXXXXX  XXXX
XXXX  XXXXXXXX  XXXX
XXX  XXXXXXXXXX  XXX
XX  XXXXXXXXXXXX  XX
