XXXXXXXXXXXXXXXX    XXXXXXXXXX
XXXXXXXXXXXXXXX XXX  XXXXXXXXX
XXXXXXXXXX        XX XXXXXXXXX
XXXXXXXXXX         X XXXXXXXXX
XXXXXXXXXX XXXXXXX   XXXXXXXXX
XXXXXXXXXX  XXXXX  XXXXXXXXXXX
XXXXXXXXXX XXXXXX     XXXXXXXX
XXXXXXXXX   XXXXX XX  XXXXXXXX
XXXXX     XXXXXXX X  XXXXXXXXX
XXXX   X X XXXXXX X  XXXXXXXXX
XXX  X X XXXXXXXX XX XXXXXXXXX
XXX XXXXXXXXXXXXXX X XXXXXXXXX
XXX XXXXXXXXXXXXXX   XXXXXXXXX
XXX XXXXXXXXXXXXX  X    XXXXXX
X    XXXXXXXXXXXX XXXXX  XXXXX
   X XXXXXXXXXXX  XXXXXX  XXXX
 XXXX           XXXXXXXXX XXXX
  XXXXXXX X X X XXXXXXXXX XXXX
X   XX    X XX  XXXXXXXXX XXXX
XX         XX   XXXXXXXX  XXXX
XXXXXXXXX     X    XXXX    XXX
XXXXXXXXXXX    XX       XX  XX
XXXXXXXXXXXXXX     XXXXXXX  XX
XXXXXXXXXXXXXXXXX     XXXX  XX
XXXXXXXXXXXXXXXXXXXXX      XXX
