     XXX      XXX   
   XXXXXXX  XXXXXXX 
   XXXXXXX  XXXXXXX 
  XXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX
   XXXXXXXXXXXXXXXX 
   XXXXXXXXXXXXXXXX 
 X  XXXXXXXXXXXXXX  
 XX XXXXXXXXXXXXXX  
 XXXXXXXXXXXXXXXXX  
 XXXXXXXXXXXXXXXXX  
 XXXXXXXXXXXXXXXXX  
 XXXXXXXXXXXXXXXXX  
 XX XXXXXXXXXXXXXX  
 X  XXXXXXXXXXXXXX  
          XX        
          XX        
          XX        
          XX        
