XXXXX      XXX  XXXX     XXXXX
X    X   XX   XX   XX   X    X
X XXX XXX  XXX  XXX  XXX XXX X
X X X    XX   XX   XX    X X X
XX XXXXXXXXXXXXXXXXXXXXXXXX XX
  X X      XXXXXXX       X X  
  X X     XXXXXXXXX      X X  
  X X    XXXX     XX     X X  
 X XX   XX X       X     XX X 
XX XX   XXXX       XX    XX XX
X X X   XXXX  X   XXX    X X X
X X X   XXXXXX X X XX    X X X
X X X   XXXX    X  XX    X X X
XX XX   XXXX    X  XXX   XX XX
 X XX   XXXX   XX  XXX   XX X 
 X XX   XXXX  X    XXX   XX X 
XX XXX XXXXX   XX XXXX X XX XX
X X X X XXXXXX   XXXXXX XX X X
X X XX XXXXXXXXXXXXXXX X X X X
X X X X XXXXXX  XXXXXXX XX X X
XX XXX XXXXXX   XXXXXX X XX XX
 X XX XXXXXXX    XXXXXX XXX X 
  X XX XXXXXX      XXX X X X  
  X X XXXXXXX   X XXXXX XX X  
  X XXXXXXXXXXXXXXXXXXXX X X  
 X XX XXXXXXXXXXXXXXXXX XXX X 
X X X    XX   XX   XX    X X X
X XXX XXX  XXX  XXX  XXX XXX X
X    X   XX   XX   XX   X    X
XXXXX      XXX  XXX      XXXXX
