   XXXXXX  XXXXXXXXX  X  XXXXX
   XXXX X  XXXXXXXXXX X   XXXX
    XX  XXX     XXX XXX    XXX
        X          XXXX    XXX
      XX          XXXXX     XX
    XXX            XXXXX X   X
   XXXX             XXXXXX XXX
  XXXXX               X XXXX X
  XXXXX XXXX   XXXXX   X XX   
  XXXXXX  XXX   XX    XXXXX   
  XXXXXXX   X       XXXXXX    
 XXXXXXXXXXX     XXXXX XX     
XXXXXXX XX             XXXXX X
XX XXXX                XXXX  X
XX XXXX     XXX        XXXXXXX
XXXXXXX     XXXX       XXXXXXX
XXXXXXX  X             XXXXX X
XXXXXXX    XXXXXX       XXXXXX
XXXXXXX    XX   XX      XXXXXX
XXXXXXX    XXXXXX     XXXXXXXX
XXXXXXXX     XX       XXXXXXXX
XXXXXXXX             XXXXXXXXX
XXXXXXXXXX         XXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
XXXXXXXXXXXXXXXXXXX  XXXXXXXXX
XXXXXXXXXXXXXXXXXX   XXXXXXXXX
XXXXXXXXXXXXXXXXX    XXXX     
XXXXXXXXXXXXXXXX    X         
 XXXXXXXXXXXXX      X         
