X XXXX  XX  XXXXXXXX          
 XX  XXXX  XXX  XX XX         
XX        XX  XXX  X XX     XX
   X      X  XX   XX XX     X 
  XXX     XXXX  XXX XXXX   XX 
 XX XX       XXXX   XXXX   X  
XX   XX            XXXXXX  XX 
X     X           XXXXXXXX XXX
X     XX       X  XXXXXXXX    
X   XXXXX     XXX  XXXXXX     
X XXXX  X    XX XXXXXXXXXX    
 XX     XX   X XX XXXXXXXX    
XX       XX XX X XXXXXXXXXX   
X         XXX XX XXXXXXXXXX   
X        XX XXX   XXXXXXXX    
X       XX       XXXXXXXXXX   
XX   XXXX        XXXXXXXXXXX  
XXXXXXX      XXXXXXXXXXXXXXXX 
XXXX       XXX  XXXXXXXXXXXX  
XXX      XXX   XXXXXXXXXXXXXX 
  X     XX XX  XXXXXXXXXXXXXX 
 XXX XXXX XXXX  XXXXXXXXXXXX  
 XXXXX X XXXXX  XXXXXXXXXXXX  
XXXXX XXX  X   XXXXXXXXXXXXXX 
  X   XXX      XXXXXXXXXXXXXXX
     XXXXX    XXXXXXXXXXXXXXXX
  X    X      XXXXXXXXXXXXXXXX
 XXX           XXXXXXXXXXXXXX 
XXXXX          XXXXXXXXXXXXXX 
XXXXXX        XXXXXXXXXXXXXXXX
